abstract final class LegalConsentStrings {
  static const Map<String, Map<String, String>> _values = {
    'tr': {'title':'Devam Etmeden Önce','intro':'MİZAN’ı kullanmadan önce Gizlilik Politikası, Kullanım Koşulları ve Satın Alma Koşullarını okuman ve kabul etmen gerekir.','readAll':'Üç belgeyi de sonuna kadar açıp incele.','privacy':'Gizlilik Politikasını Oku','terms':'Kullanım Koşullarını Oku','purchase':'Satın Alma Koşullarını Oku','accept':'Okudum, Anladım ve Kabul Ediyorum','blocked':'Kabul düğmesi, üç belge de okunmadan etkinleşmez.','readDone':'Okundu','masterNotice':'Belgeler Türkçe ve İngilizce tam metin olarak sunulur. Hukukun izin verdiği ölçüde İngilizce metin esas alınır.'},
    'en': {'title':'Before You Continue','intro':'Before using MIZAN, you must read and accept the Privacy Policy, Terms of Use and Purchase Terms.','readAll':'Open and review all three documents through to the end.','privacy':'Read Privacy Policy','terms':'Read Terms of Use','purchase':'Read Purchase Terms','accept':'I Have Read, Understood and Accept','blocked':'The acceptance button remains unavailable until all three documents have been read.','readDone':'Read','masterNotice':'The documents are provided in full in Turkish and English. To the extent permitted by law, the English text controls.'},
    'es': {'title':'Antes de continuar','intro':'Antes de usar MIZAN, debes leer y aceptar la Política de privacidad, los Términos de uso y las Condiciones de compra.','readAll':'Abre y revisa los tres documentos hasta el final.','privacy':'Leer la política de privacidad','terms':'Leer los términos de uso','purchase':'Leer las condiciones de compra','accept':'He leído, entendido y acepto','blocked':'El botón de aceptación no se habilita hasta que hayas leído los tres documentos.','readDone':'Leído','masterNotice':'Los documentos se ofrecen íntegramente en turco e inglés. En la medida permitida por la ley, prevalece el texto inglés.'},
    'pt-BR': {'title':'Antes de continuar','intro':'Antes de usar o MIZAN, você deve ler e aceitar a Política de Privacidade, os Termos de Uso e os Termos de Compra.','readAll':'Abra e revise os três documentos até o final.','privacy':'Ler Política de Privacidade','terms':'Ler Termos de Uso','purchase':'Ler Termos de Compra','accept':'Li, entendi e aceito','blocked':'O botão de aceite só é liberado depois que os três documentos forem lidos.','readDone':'Lido','masterNotice':'Os documentos são apresentados integralmente em turco e inglês. Na medida permitida por lei, prevalece o texto em inglês.'},
    'pt-PT': {'title':'Antes de continuar','intro':'Antes de utilizar o MIZAN, tem de ler e aceitar a Política de Privacidade, os Termos de Utilização e os Termos de Compra.','readAll':'Abra e reveja os três documentos até ao fim.','privacy':'Ler Política de Privacidade','terms':'Ler Termos de Utilização','purchase':'Ler Termos de Compra','accept':'Li, compreendi e aceito','blocked':'O botão de aceitação só fica disponível depois de os três documentos terem sido lidos.','readDone':'Lido','masterNotice':'Os documentos são apresentados integralmente em turco e inglês. Na medida permitida por lei, prevalece o texto inglês.'},
    'fr': {'title':'Avant de continuer','intro':'Avant d’utiliser MIZAN, vous devez lire et accepter la Politique de confidentialité, les Conditions d’utilisation et les Conditions d’achat.','readAll':'Ouvrez et consultez les trois documents jusqu’à la fin.','privacy':'Lire la politique de confidentialité','terms':'Lire les conditions d’utilisation','purchase':'Lire les conditions d’achat','accept':'J’ai lu, compris et j’accepte','blocked':'Le bouton d’acceptation reste indisponible tant que les trois documents n’ont pas été lus.','readDone':'Lu','masterNotice':'Les documents sont fournis intégralement en turc et en anglais. Dans la mesure permise par la loi, le texte anglais prévaut.'},
    'de': {'title':'Bevor Sie fortfahren','intro':'Bevor Sie MIZAN verwenden, müssen Sie die Datenschutzerklärung, die Nutzungsbedingungen und die Kaufbedingungen lesen und akzeptieren.','readAll':'Öffnen und prüfen Sie alle drei Dokumente bis zum Ende.','privacy':'Datenschutzerklärung lesen','terms':'Nutzungsbedingungen lesen','purchase':'Kaufbedingungen lesen','accept':'Ich habe gelesen, verstanden und stimme zu','blocked':'Die Zustimmungsschaltfläche wird erst aktiviert, nachdem alle drei Dokumente gelesen wurden.','readDone':'Gelesen','masterNotice':'Die Dokumente werden vollständig auf Türkisch und Englisch bereitgestellt. Soweit gesetzlich zulässig, ist der englische Text maßgeblich.'},
    'it': {'title':'Prima di continuare','intro':'Prima di usare MIZAN devi leggere e accettare l’Informativa sulla privacy, le Condizioni d’uso e le Condizioni di acquisto.','readAll':'Apri e consulta tutti e tre i documenti fino alla fine.','privacy':'Leggi l’informativa sulla privacy','terms':'Leggi le condizioni d’uso','purchase':'Leggi le condizioni di acquisto','accept':'Ho letto, compreso e accetto','blocked':'Il pulsante di accettazione resta disattivato finché non hai letto tutti e tre i documenti.','readDone':'Letto','masterNotice':'I documenti sono forniti integralmente in turco e inglese. Nei limiti consentiti dalla legge, prevale il testo inglese.'},
    'nl': {'title':'Voordat u doorgaat','intro':'Voordat u MIZAN gebruikt, moet u het Privacybeleid, de Gebruiksvoorwaarden en de Aankoopvoorwaarden lezen en accepteren.','readAll':'Open en bekijk alle drie de documenten tot het einde.','privacy':'Privacybeleid lezen','terms':'Gebruiksvoorwaarden lezen','purchase':'Aankoopvoorwaarden lezen','accept':'Ik heb gelezen, begrepen en ga akkoord','blocked':'De akkoordknop wordt pas actief nadat alle drie de documenten zijn gelezen.','readDone':'Gelezen','masterNotice':'De documenten worden volledig in het Turks en Engels aangeboden. Voor zover wettelijk toegestaan, is de Engelse tekst leidend.'},
    'pl': {'title':'Zanim przejdziesz dalej','intro':'Przed rozpoczęciem korzystania z MIZAN musisz przeczytać i zaakceptować Politykę prywatności, Warunki użytkowania oraz Warunki zakupu.','readAll':'Otwórz i przeczytaj wszystkie trzy dokumenty do końca.','privacy':'Przeczytaj Politykę prywatności','terms':'Przeczytaj Warunki użytkowania','purchase':'Przeczytaj Warunki zakupu','accept':'Przeczytałem(-am), rozumiem i akceptuję','blocked':'Przycisk akceptacji zostanie włączony dopiero po przeczytaniu wszystkich trzech dokumentów.','readDone':'Przeczytano','masterNotice':'Pełne dokumenty są dostępne po turecku i angielsku. W zakresie dozwolonym przez prawo rozstrzygający jest tekst angielski.'},
    'ro': {'title':'Înainte de a continua','intro':'Înainte de a utiliza MIZAN, trebuie să citești și să accepți Politica de confidențialitate, Condițiile de utilizare și Condițiile de achiziție.','readAll':'Deschide și parcurge toate cele trei documente până la final.','privacy':'Citește Politica de confidențialitate','terms':'Citește Condițiile de utilizare','purchase':'Citește Condițiile de achiziție','accept':'Am citit, am înțeles și accept','blocked':'Butonul de acceptare devine disponibil numai după citirea tuturor celor trei documente.','readDone':'Citit','masterNotice':'Documentele sunt oferite integral în turcă și engleză. În măsura permisă de lege, textul în limba engleză prevalează.'},
    'el': {'title':'Πριν συνεχίσετε','intro':'Πριν χρησιμοποιήσετε το MIZAN, πρέπει να διαβάσετε και να αποδεχτείτε την Πολιτική απορρήτου, τους Όρους χρήσης και τους Όρους αγοράς.','readAll':'Ανοίξτε και διαβάστε και τα τρία έγγραφα μέχρι το τέλος.','privacy':'Διαβάστε την Πολιτική απορρήτου','terms':'Διαβάστε τους Όρους χρήσης','purchase':'Διαβάστε τους Όρους αγοράς','accept':'Τα διάβασα, τα κατανόησα και συμφωνώ','blocked':'Το κουμπί αποδοχής ενεργοποιείται μόνο αφού διαβαστούν και τα τρία έγγραφα.','readDone':'Διαβάστηκε','masterNotice':'Τα πλήρη έγγραφα παρέχονται στα τουρκικά και στα αγγλικά. Στον βαθμό που επιτρέπεται από τον νόμο, υπερισχύει το αγγλικό κείμενο.'},
    'ru': {'title':'Перед продолжением','intro':'Перед использованием MIZAN необходимо прочитать и принять Политику конфиденциальности, Условия использования и Условия покупки.','readAll':'Откройте и прочитайте все три документа до конца.','privacy':'Прочитать Политику конфиденциальности','terms':'Прочитать Условия использования','purchase':'Прочитать Условия покупки','accept':'Я прочитал(а), понял(а) и принимаю','blocked':'Кнопка принятия станет доступна только после прочтения всех трех документов.','readDone':'Прочитано','masterNotice':'Полные тексты документов представлены на турецком и английском языках. В пределах, разрешенных законом, приоритет имеет английский текст.'},
    'uk': {'title':'Перед продовженням','intro':'Перед використанням MIZAN потрібно прочитати й прийняти Політику конфіденційності, Умови використання та Умови придбання.','readAll':'Відкрийте та прочитайте всі три документи до кінця.','privacy':'Прочитати Політику конфіденційності','terms':'Прочитати Умови використання','purchase':'Прочитати Умови придбання','accept':'Я прочитав(ла), зрозумів(ла) і приймаю','blocked':'Кнопка прийняття стане доступною лише після прочитання всіх трьох документів.','readDone':'Прочитано','masterNotice':'Повні тексти документів подано турецькою та англійською мовами. У межах, дозволених законом, переважну силу має англійський текст.'},
    'ar': {'title':'قبل المتابعة','intro':'قبل استخدام MIZAN، يجب قراءة سياسة الخصوصية وشروط الاستخدام وشروط الشراء والموافقة عليها.','readAll':'افتح المستندات الثلاثة واقرأها حتى النهاية.','privacy':'قراءة سياسة الخصوصية','terms':'قراءة شروط الاستخدام','purchase':'قراءة شروط الشراء','accept':'قرأت وفهمت وأوافق','blocked':'لن يتفعّل زر الموافقة قبل قراءة المستندات الثلاثة.','readDone':'تمت القراءة','masterNotice':'تُعرض النصوص الكاملة بالتركية والإنجليزية. وفي الحدود التي يسمح بها القانون يكون النص الإنجليزي هو المرجع الحاكم.'},
    'fa': {'title':'پیش از ادامه','intro':'پیش از استفاده از MIZAN باید سیاست حریم خصوصی، شرایط استفاده و شرایط خرید را بخوانید و بپذیرید.','readAll':'هر سه سند را باز کنید و تا انتها مطالعه کنید.','privacy':'مطالعه سیاست حریم خصوصی','terms':'مطالعه شرایط استفاده','purchase':'مطالعه شرایط خرید','accept':'خواندم، درک کردم و می‌پذیرم','blocked':'دکمه پذیرش تا زمانی که هر سه سند خوانده نشوند فعال نمی‌شود.','readDone':'مطالعه شد','masterNotice':'متن کامل اسناد به زبان ترکی و انگلیسی ارائه می‌شود. تا حدی که قانون اجازه دهد، متن انگلیسی ملاک است.'},
    'he': {'title':'לפני שממשיכים','intro':'לפני השימוש ב-MIZAN יש לקרוא ולאשר את מדיניות הפרטיות, תנאי השימוש ותנאי הרכישה.','readAll':'יש לפתוח ולקרוא את שלושת המסמכים עד סופם.','privacy':'קריאת מדיניות הפרטיות','terms':'קריאת תנאי השימוש','purchase':'קריאת תנאי הרכישה','accept':'קראתי, הבנתי ואני מסכים/ה','blocked':'כפתור האישור יופעל רק לאחר קריאת כל שלושת המסמכים.','readDone':'נקרא','masterNotice':'המסמכים המלאים מוצגים בטורקית ובאנגלית. ככל שהדין מתיר, הנוסח האנגלי הוא הקובע.'},
    'hi': {'title':'आगे बढ़ने से पहले','intro':'MIZAN का उपयोग करने से पहले आपको गोपनीयता नीति, उपयोग की शर्तें और खरीद की शर्तें पढ़कर स्वीकार करनी होंगी।','readAll':'तीनों दस्तावेज़ खोलें और अंत तक पढ़ें।','privacy':'गोपनीयता नीति पढ़ें','terms':'उपयोग की शर्तें पढ़ें','purchase':'खरीद की शर्तें पढ़ें','accept':'मैंने पढ़ा, समझा और स्वीकार किया','blocked':'तीनों दस्तावेज़ पढ़े बिना स्वीकार बटन सक्रिय नहीं होगा।','readDone':'पढ़ा गया','masterNotice':'दस्तावेज़ों का पूरा पाठ तुर्की और अंग्रेज़ी में दिया गया है। कानून की अनुमति की सीमा तक अंग्रेज़ी पाठ प्रभावी रहेगा।'},
    'bn': {'title':'এগিয়ে যাওয়ার আগে','intro':'MIZAN ব্যবহার করার আগে গোপনীয়তা নীতি, ব্যবহারের শর্তাবলি এবং ক্রয়ের শর্তাবলি পড়ে গ্রহণ করতে হবে।','readAll':'তিনটি নথিই খুলে শেষ পর্যন্ত পড়ুন।','privacy':'গোপনীয়তা নীতি পড়ুন','terms':'ব্যবহারের শর্তাবলি পড়ুন','purchase':'ক্রয়ের শর্তাবলি পড়ুন','accept':'আমি পড়েছি, বুঝেছি এবং গ্রহণ করছি','blocked':'তিনটি নথি পড়া না হওয়া পর্যন্ত গ্রহণ বোতাম সক্রিয় হবে না।','readDone':'পড়া হয়েছে','masterNotice':'নথিগুলোর পূর্ণ পাঠ তুর্কি ও ইংরেজিতে দেওয়া হয়। আইন যতটুকু অনুমতি দেয়, ইংরেজি পাঠ প্রাধান্য পাবে।'},
    'ur': {'title':'آگے بڑھنے سے پہلے','intro':'MIZAN استعمال کرنے سے پہلے رازداری کی پالیسی، استعمال کی شرائط اور خریداری کی شرائط پڑھنا اور قبول کرنا ضروری ہے۔','readAll':'تینوں دستاویزات کھول کر آخر تک پڑھیں۔','privacy':'رازداری کی پالیسی پڑھیں','terms':'استعمال کی شرائط پڑھیں','purchase':'خریداری کی شرائط پڑھیں','accept':'میں نے پڑھا، سمجھا اور قبول کیا','blocked':'تینوں دستاویزات پڑھے بغیر قبول کرنے کا بٹن فعال نہیں ہوگا۔','readDone':'پڑھا گیا','masterNotice':'دستاویزات کا مکمل متن ترکی اور انگریزی میں دیا جاتا ہے۔ قانون کی اجازت کی حد تک انگریزی متن حاکم ہوگا۔'},
    'id': {'title':'Sebelum melanjutkan','intro':'Sebelum menggunakan MIZAN, Anda wajib membaca dan menyetujui Kebijakan Privasi, Ketentuan Penggunaan, dan Ketentuan Pembelian.','readAll':'Buka dan baca ketiga dokumen sampai selesai.','privacy':'Baca Kebijakan Privasi','terms':'Baca Ketentuan Penggunaan','purchase':'Baca Ketentuan Pembelian','accept':'Saya sudah membaca, memahami, dan menyetujui','blocked':'Tombol persetujuan baru aktif setelah ketiga dokumen dibaca.','readDone':'Sudah dibaca','masterNotice':'Dokumen lengkap tersedia dalam bahasa Turki dan Inggris. Sejauh diizinkan hukum, teks bahasa Inggris yang berlaku.'},
    'ms': {'title':'Sebelum meneruskan','intro':'Sebelum menggunakan MIZAN, anda mesti membaca dan menerima Dasar Privasi, Terma Penggunaan dan Terma Pembelian.','readAll':'Buka dan baca ketiga-tiga dokumen hingga selesai.','privacy':'Baca Dasar Privasi','terms':'Baca Terma Penggunaan','purchase':'Baca Terma Pembelian','accept':'Saya telah membaca, memahami dan bersetuju','blocked':'Butang persetujuan hanya diaktifkan selepas ketiga-tiga dokumen dibaca.','readDone':'Telah dibaca','masterNotice':'Dokumen penuh disediakan dalam bahasa Turki dan Inggeris. Setakat yang dibenarkan undang-undang, teks bahasa Inggeris adalah terpakai.'},
    'fil': {'title':'Bago magpatuloy','intro':'Bago gamitin ang MIZAN, kailangan mong basahin at tanggapin ang Patakaran sa Privacy, Mga Tuntunin ng Paggamit, at Mga Tuntunin sa Pagbili.','readAll':'Buksan at basahin hanggang dulo ang lahat ng tatlong dokumento.','privacy':'Basahin ang Patakaran sa Privacy','terms':'Basahin ang Mga Tuntunin ng Paggamit','purchase':'Basahin ang Mga Tuntunin sa Pagbili','accept':'Nabasa ko, naunawaan ko, at tinatanggap ko','blocked':'Magiging aktibo lamang ang pindutan ng pagtanggap kapag nabasa na ang tatlong dokumento.','readDone':'Nabasa na','masterNotice':'Ibinibigay nang buo ang mga dokumento sa Turkish at English. Hangga’t pinahihintulutan ng batas, ang tekstong English ang masusunod.'},
    'ko': {'title':'계속하기 전에','intro':'MIZAN을 사용하기 전에 개인정보 처리방침, 이용약관 및 구매 조건을 읽고 동의해야 합니다.','readAll':'세 문서를 모두 열어 끝까지 확인하세요.','privacy':'개인정보 처리방침 읽기','terms':'이용약관 읽기','purchase':'구매 조건 읽기','accept':'읽고 이해했으며 동의합니다','blocked':'세 문서를 모두 읽기 전에는 동의 버튼이 활성화되지 않습니다.','readDone':'읽음','masterNotice':'문서 전문은 터키어와 영어로 제공됩니다. 법이 허용하는 범위에서는 영어 원문이 우선합니다.'},
    'ja': {'title':'続行する前に','intro':'MIZANを使用する前に、プライバシーポリシー、利用規約、購入条件を読み、同意する必要があります。','readAll':'3つの文書をすべて開き、最後まで確認してください。','privacy':'プライバシーポリシーを読む','terms':'利用規約を読む','purchase':'購入条件を読む','accept':'読み、理解したうえで同意します','blocked':'3つの文書をすべて読むまで同意ボタンは有効になりません。','readDone':'確認済み','masterNotice':'文書全文はトルコ語と英語で提供されます。法律で認められる範囲では英語原文が優先されます。'},
    'zh': {'title':'继续之前','intro':'使用 MIZAN 前，你必须阅读并接受《隐私政策》《使用条款》和《购买条款》。','readAll':'请打开三份文件并阅读至末尾。','privacy':'阅读隐私政策','terms':'阅读使用条款','purchase':'阅读购买条款','accept':'我已阅读、理解并同意','blocked':'三份文件全部阅读后，同意按钮才会启用。','readDone':'已阅读','masterNotice':'文件全文以土耳其语和英语提供。在法律允许的范围内，以英文文本为准。'},
    'vi': {'title':'Trước khi tiếp tục','intro':'Trước khi sử dụng MIZAN, bạn phải đọc và chấp nhận Chính sách quyền riêng tư, Điều khoản sử dụng và Điều khoản mua hàng.','readAll':'Mở và đọc hết cả ba tài liệu.','privacy':'Đọc Chính sách quyền riêng tư','terms':'Đọc Điều khoản sử dụng','purchase':'Đọc Điều khoản mua hàng','accept':'Tôi đã đọc, hiểu và đồng ý','blocked':'Nút đồng ý chỉ được bật sau khi bạn đã đọc cả ba tài liệu.','readDone':'Đã đọc','masterNotice':'Toàn văn tài liệu được cung cấp bằng tiếng Thổ Nhĩ Kỳ và tiếng Anh. Trong phạm vi pháp luật cho phép, bản tiếng Anh được ưu tiên.'},
    'th': {'title':'ก่อนดำเนินการต่อ','intro':'ก่อนใช้ MIZAN คุณต้องอ่านและยอมรับนโยบายความเป็นส่วนตัว ข้อกำหนดการใช้งาน และข้อกำหนดการซื้อ','readAll':'เปิดและอ่านเอกสารทั้งสามฉบับจนจบ','privacy':'อ่านนโยบายความเป็นส่วนตัว','terms':'อ่านข้อกำหนดการใช้งาน','purchase':'อ่านข้อกำหนดการซื้อ','accept':'ฉันได้อ่าน เข้าใจ และยอมรับ','blocked':'ปุ่มยอมรับจะใช้งานได้หลังจากอ่านเอกสารครบทั้งสามฉบับแล้วเท่านั้น','readDone':'อ่านแล้ว','masterNotice':'เอกสารฉบับเต็มมีทั้งภาษาตุรกีและภาษาอังกฤษ และเท่าที่กฎหมายอนุญาต ให้ข้อความภาษาอังกฤษเป็นหลัก'},
    'sw': {'title':'Kabla ya kuendelea','intro':'Kabla ya kutumia MIZAN, lazima usome na ukubali Sera ya Faragha, Masharti ya Matumizi na Masharti ya Ununuzi.','readAll':'Fungua na usome nyaraka zote tatu hadi mwisho.','privacy':'Soma Sera ya Faragha','terms':'Soma Masharti ya Matumizi','purchase':'Soma Masharti ya Ununuzi','accept':'Nimesoma, nimeelewa na ninakubali','blocked':'Kitufe cha kukubali kitawezeshwa baada ya nyaraka zote tatu kusomwa.','readDone':'Imesomwa','masterNotice':'Nyaraka kamili zinatolewa kwa Kituruki na Kiingereza. Kwa kiwango kinachoruhusiwa na sheria, maandishi ya Kiingereza ndiyo yanayotawala.'},
  };

  static String text(String languageTag, String key) {
    final map = _values[languageTag] ?? _values['en']!;
    return map[key] ?? _values['en']![key] ?? key;
  }

  static Set<String> get supportedTags => _values.keys.toSet();
}
