import 'legal_documents.dart';

abstract final class LegalLocaleSummaries {
  static const Map<String, String> _terms = {
    'tr':
        'MİZAN kişisel finansal kayıt ve hatırlatma aracıdır; banka, yatırım, vergi, hukuk, muhasebe veya düzenlemeye tabi mali danışmanlık hizmeti değildir. Kullanıcı tutarları, vadeleri, faizleri, vergileri ve dış ödeme yükümlülüklerini ilgili kurumdan kendisi doğrular. Ücretsiz sürüm internet bağlantısı gerektirir, reklam gösterebilir ve PDF raporu vermez. Geçerli Premium uygulama içi reklamları kaldırır, çevrimdışı kullanıma ve PDF raporlarına izin verir. Satın alma, reklam, promosyon, Play Integrity veya diğer güvenlik kontrollerini aşmak; sahte Premium hakkı üretmek; değiştirilmiş sürümle hak taklidi yapmak yasaktır. Yerel kayıtların ve dışa aktarılan CSV/PDF dosyalarının yedeklenmesi ve korunması kullanıcı sorumluluğundadır. İade edilmiş veya geçersiz olduğu güvenilir biçimde doğrulanan Premium hakkı geri çekilebilir; finansal kayıtlar bunun için silinmez. Kanunen vazgeçilemeyen tüketici hakları ve sorumluluklar saklıdır. İngilizce esas metin, hukukun izin verdiği ölçüde yorum referansıdır.',
    'en':
        'MIZAN is a personal financial record and reminder utility, not banking, investment, tax, legal, accounting or regulated financial advice. Users must independently verify amounts, due dates, interest, taxes and external payment duties. Free mode requires internet access, may show advertising and excludes PDF reports. Valid Premium removes App-served ads, enables offline use and PDF reports. Bypassing purchase, advertising, promotion, Play Integrity or other security controls; forging Premium entitlement; or distributing deceptive modified builds is prohibited. Users are responsible for protecting local records and exported CSV/PDF files. Premium may be revoked when a refund, cancellation, chargeback or invalid purchase is reliably verified, without deleting the user’s financial records. Mandatory consumer rights and non-excludable liabilities remain unaffected. The English master is the interpretation reference to the extent permitted by law.',
    'es':
        'MIZAN es una herramienta personal de registro y recordatorio financiero; no presta servicios bancarios ni asesoramiento de inversión, fiscal, jurídico, contable o financiero regulado. El usuario debe verificar por su cuenta importes, vencimientos, intereses, impuestos y obligaciones externas. La versión gratuita requiere Internet, puede mostrar publicidad y no permite informes PDF. Un Premium válido elimina los anuncios servidos por la aplicación y habilita el uso sin conexión y los PDF. Está prohibido eludir controles de compra, publicidad, promociones, Play Integrity o seguridad, falsificar derechos Premium o distribuir versiones modificadas engañosas. El usuario es responsable de proteger sus registros locales y archivos exportados. Un derecho Premium puede retirarse si se verifica de forma fiable un reembolso, cancelación, contracargo o compra inválida, sin borrar los registros financieros. Se conservan los derechos obligatorios del consumidor. El texto maestro en inglés es la referencia de interpretación en la medida permitida por la ley.',
    'pt-BR':
        'O MIZAN é uma ferramenta pessoal de registro financeiro e lembretes; não oferece serviços bancários nem aconselhamento de investimento, tributário, jurídico, contábil ou financeiro regulado. O usuário deve confirmar valores, vencimentos, juros, impostos e obrigações externas. A versão gratuita exige internet, pode exibir anúncios e não gera relatórios PDF. Um Premium válido remove anúncios servidos pelo app e libera uso offline e PDF. É proibido contornar controles de compra, publicidade, promoção, Play Integrity ou segurança, falsificar direito Premium ou distribuir versões modificadas enganosas. O usuário é responsável por proteger registros locais e arquivos exportados. O Premium pode ser retirado quando reembolso, cancelamento, chargeback ou compra inválida forem confirmados de forma confiável, sem apagar os registros financeiros. Direitos obrigatórios do consumidor permanecem preservados. O texto mestre em inglês é a referência de interpretação quando a lei permitir.',
    'pt-PT':
        'O MIZAN é uma ferramenta pessoal de registo financeiro e lembretes; não presta serviços bancários nem aconselhamento de investimento, fiscal, jurídico, contabilístico ou financeiro regulado. O utilizador deve confirmar valores, prazos, juros, impostos e obrigações externas. A versão gratuita exige Internet, pode apresentar anúncios e não disponibiliza relatórios PDF. Um Premium válido remove anúncios servidos pela aplicação e permite utilização offline e PDF. É proibido contornar controlos de compra, publicidade, promoção, Play Integrity ou segurança, falsificar direitos Premium ou distribuir versões modificadas enganosas. O utilizador é responsável por proteger registos locais e ficheiros exportados. O Premium pode ser retirado quando um reembolso, cancelamento, chargeback ou compra inválida forem confirmados de forma fiável, sem apagar os registos financeiros. Mantêm-se os direitos obrigatórios do consumidor. O texto mestre inglês é a referência de interpretação quando a lei o permite.',
    'fr':
        'MIZAN est un outil personnel de suivi financier et de rappels ; il ne fournit pas de services bancaires ni de conseil en investissement, fiscal, juridique, comptable ou financier réglementé. L’utilisateur doit vérifier lui-même montants, échéances, intérêts, taxes et obligations externes. La version gratuite nécessite Internet, peut afficher des publicités et n’inclut pas les rapports PDF. Un Premium valide supprime les publicités servies par l’application et autorise l’usage hors ligne et les PDF. Il est interdit de contourner les contrôles d’achat, publicité, promotion, Play Integrity ou sécurité, de falsifier un droit Premium ou de distribuer une version modifiée trompeuse. L’utilisateur doit protéger ses données locales et fichiers exportés. Le Premium peut être retiré si un remboursement, une annulation, un rejet de paiement ou un achat invalide est vérifié de manière fiable, sans supprimer les données financières. Les droits impératifs du consommateur restent applicables. Le texte anglais sert de référence dans la mesure autorisée par la loi.',
    'de':
        'MIZAN ist ein persönliches Finanzaufzeichnungs- und Erinnerungswerkzeug und keine Bank-, Anlage-, Steuer-, Rechts-, Buchhaltungs- oder regulierte Finanzberatung. Nutzer müssen Beträge, Fälligkeiten, Zinsen, Steuern und externe Zahlungspflichten selbst prüfen. Die kostenlose Version benötigt Internet, kann Werbung anzeigen und enthält keine PDF-Berichte. Gültiges Premium entfernt App-Werbung und erlaubt Offline-Nutzung sowie PDFs. Das Umgehen von Kauf-, Werbe-, Promotions-, Play-Integrity- oder Sicherheitskontrollen, das Fälschen von Premium-Rechten oder die Verbreitung irreführend veränderter Builds ist untersagt. Nutzer sind für den Schutz lokaler Daten und exportierter Dateien verantwortlich. Premium kann nach zuverlässig bestätigter Erstattung, Stornierung, Rückbuchung oder ungültigem Kauf entzogen werden, ohne Finanzdaten zu löschen. Zwingende Verbraucherrechte bleiben unberührt. Soweit gesetzlich zulässig ist der englische Mastertext Auslegungsreferenz.',
    'it':
        'MIZAN è uno strumento personale di registrazione finanziaria e promemoria; non fornisce servizi bancari né consulenza in materia di investimenti, tasse, diritto, contabilità o finanza regolamentata. L’utente deve verificare autonomamente importi, scadenze, interessi, imposte e obblighi esterni. La versione gratuita richiede Internet, può mostrare pubblicità e non include i report PDF. Un Premium valido elimina gli annunci serviti dall’app e abilita uso offline e PDF. È vietato aggirare controlli di acquisto, pubblicità, promozione, Play Integrity o sicurezza, falsificare diritti Premium o distribuire versioni modificate ingannevoli. L’utente deve proteggere dati locali e file esportati. Il Premium può essere revocato quando un rimborso, annullamento, chargeback o acquisto non valido è verificato in modo affidabile, senza cancellare i dati finanziari. Restano validi i diritti inderogabili del consumatore. Il testo inglese è il riferimento interpretativo nei limiti consentiti dalla legge.',
    'nl':
        'MIZAN is een hulpmiddel voor persoonlijke financiële registratie en herinneringen, geen bankdienst of gereguleerd beleggings-, belasting-, juridisch, boekhoudkundig of financieel advies. Gebruikers moeten bedragen, vervaldata, rente, belastingen en externe betalingsverplichtingen zelf controleren. De gratis versie vereist internet, kan advertenties tonen en bevat geen PDF-rapporten. Geldig Premium verwijdert door de app geserveerde advertenties en maakt offline gebruik en PDF mogelijk. Het omzeilen van aankoop-, advertentie-, promotie-, Play Integrity- of beveiligingscontroles, het vervalsen van Premium-rechten of het verspreiden van misleidend aangepaste builds is verboden. Gebruikers zijn verantwoordelijk voor de beveiliging van lokale gegevens en exports. Premium kan worden ingetrokken wanneer een terugbetaling, annulering, chargeback of ongeldige aankoop betrouwbaar is vastgesteld, zonder financiële gegevens te wissen. Dwingende consumentenrechten blijven gelden. De Engelse hoofdtekst is de interpretatiereferentie voor zover wettelijk toegestaan.',
    'pl':
        'MIZAN jest narzędziem do osobistego prowadzenia zapisów finansowych i przypomnień; nie jest usługą bankową ani regulowaną poradą inwestycyjną, podatkową, prawną, księgową lub finansową. Użytkownik sam weryfikuje kwoty, terminy, odsetki, podatki i zewnętrzne zobowiązania. Wersja bezpłatna wymaga Internetu, może wyświetlać reklamy i nie obejmuje raportów PDF. Ważny Premium usuwa reklamy aplikacji i umożliwia działanie offline oraz PDF. Zabronione jest obchodzenie kontroli zakupów, reklam, promocji, Play Integrity lub zabezpieczeń, fałszowanie Premium i rozpowszechnianie wprowadzających w błąd zmodyfikowanych wersji. Użytkownik odpowiada za ochronę danych lokalnych i eksportów. Premium może zostać cofnięte po wiarygodnym potwierdzeniu zwrotu, anulowania, chargebacku lub nieważnego zakupu, bez usuwania danych finansowych. Bezwzględnie obowiązujące prawa konsumenta pozostają zachowane. Angielski tekst główny jest referencją interpretacyjną w zakresie dozwolonym prawem.',
    'ro':
        'MIZAN este un instrument personal de evidență financiară și mementouri, nu un serviciu bancar și nici consultanță reglementată de investiții, fiscală, juridică, contabilă sau financiară. Utilizatorul trebuie să verifice independent sumele, scadențele, dobânzile, taxele și obligațiile externe. Versiunea gratuită necesită Internet, poate afișa reclame și nu include rapoarte PDF. Premium valid elimină reclamele servite de aplicație și permite utilizarea offline și PDF. Este interzisă ocolirea controalelor de cumpărare, publicitate, promoții, Play Integrity sau securitate, falsificarea dreptului Premium ori distribuirea unor versiuni modificate înșelătoare. Utilizatorul răspunde de protejarea datelor locale și a exporturilor. Premium poate fi retras după confirmarea fiabilă a unei rambursări, anulări, chargeback sau cumpărări invalide, fără ștergerea datelor financiare. Drepturile obligatorii ale consumatorilor rămân valabile. Textul principal în engleză este referința de interpretare în limita permisă de lege.',
    'el':
        'Το MIZAN είναι εργαλείο προσωπικής οικονομικής καταγραφής και υπενθυμίσεων και όχι τραπεζική υπηρεσία ή ρυθμιζόμενη επενδυτική, φορολογική, νομική, λογιστική ή οικονομική συμβουλή. Ο χρήστης πρέπει να επαληθεύει ποσά, προθεσμίες, τόκους, φόρους και εξωτερικές υποχρεώσεις. Η δωρεάν έκδοση απαιτεί Internet, μπορεί να εμφανίζει διαφημίσεις και δεν παρέχει PDF. Έγκυρο Premium αφαιρεί τις διαφημίσεις της εφαρμογής και επιτρέπει offline χρήση και PDF. Απαγορεύεται η παράκαμψη ελέγχων αγοράς, διαφήμισης, προσφορών, Play Integrity ή ασφάλειας, η πλαστογράφηση Premium και η διανομή παραπλανητικών τροποποιημένων εκδόσεων. Ο χρήστης είναι υπεύθυνος για την προστασία τοπικών δεδομένων και εξαγωγών. Το Premium μπορεί να ανακληθεί όταν επιβεβαιωθεί αξιόπιστα επιστροφή, ακύρωση, αντιλογισμός ή άκυρη αγορά, χωρίς διαγραφή οικονομικών δεδομένων. Τα υποχρεωτικά δικαιώματα καταναλωτή διατηρούνται. Το αγγλικό κύριο κείμενο αποτελεί σημείο αναφοράς όπου το επιτρέπει ο νόμος.',
    'ru':
        'MIZAN — инструмент для личного финансового учета и напоминаний, а не банковская услуга и не регулируемая инвестиционная, налоговая, юридическая, бухгалтерская или финансовая консультация. Пользователь самостоятельно проверяет суммы, сроки, проценты, налоги и внешние обязательства. Бесплатная версия требует интернет, может показывать рекламу и не включает PDF-отчеты. Действующий Premium убирает рекламу приложения и разрешает офлайн-режим и PDF. Запрещено обходить контроль покупок, рекламы, промокодов, Play Integrity и безопасности, подделывать Premium или распространять вводящие в заблуждение измененные сборки. Пользователь отвечает за защиту локальных данных и экспортов. Premium может быть отозван после надежного подтверждения возврата, отмены, chargeback или недействительной покупки, без удаления финансовых записей. Обязательные права потребителя сохраняются. Английский основной текст является ориентиром толкования в пределах, разрешенных законом.',
    'uk':
        'MIZAN — інструмент особистого фінансового обліку та нагадувань, а не банківська послуга чи регульована інвестиційна, податкова, юридична, бухгалтерська або фінансова консультація. Користувач самостійно перевіряє суми, строки, відсотки, податки та зовнішні зобов’язання. Безкоштовна версія потребує Інтернету, може показувати рекламу й не включає PDF-звіти. Чинний Premium прибирає рекламу застосунку та дозволяє офлайн-режим і PDF. Заборонено обходити контроль покупок, реклами, промокодів, Play Integrity або безпеки, підробляти Premium чи поширювати оманливі змінені збірки. Користувач відповідає за захист локальних даних і експортів. Premium може бути відкликаний після надійного підтвердження повернення, скасування, chargeback або недійсної покупки без видалення фінансових записів. Обов’язкові права споживача зберігаються. Англійський основний текст є орієнтиром тлумачення в межах, дозволених законом.',
    'ar':
        'MIZAN أداة شخصية لتسجيل الشؤون المالية والتذكير، وليس خدمة مصرفية ولا استشارة استثمارية أو ضريبية أو قانونية أو محاسبية أو مالية خاضعة للتنظيم. يجب على المستخدم التحقق بنفسه من المبالغ والمواعيد والفوائد والضرائب والالتزامات الخارجية. تتطلب النسخة المجانية اتصالاً بالإنترنت وقد تعرض إعلانات ولا تشمل تقارير PDF. يزيل Premium الساري إعلانات التطبيق ويسمح بالاستخدام دون اتصال وتقارير PDF. يُحظر تجاوز ضوابط الشراء أو الإعلانات أو العروض أو Play Integrity أو الأمان، أو تزوير حق Premium، أو توزيع نسخ معدلة مضللة. يتحمل المستخدم مسؤولية حماية البيانات المحلية والملفات المصدرة. يمكن سحب Premium عند التحقق الموثوق من استرداد أو إلغاء أو اعتراض مالي أو شراء غير صالح، دون حذف السجلات المالية. تبقى حقوق المستهلك الإلزامية محفوظة. النص الإنجليزي الرئيسي هو مرجع التفسير بالقدر الذي يسمح به القانون.',
    'fa':
        'MIZAN ابزار شخصی ثبت مالی و یادآوری است و خدمت بانکی یا مشاوره سرمایه‌گذاری، مالیاتی، حقوقی، حسابداری یا مالیِ تحت نظارت نیست. کاربر باید مبلغ‌ها، سررسیدها، بهره، مالیات و تعهدات بیرونی را مستقلاً بررسی کند. نسخه رایگان به اینترنت نیاز دارد، ممکن است تبلیغ نمایش دهد و PDF ارائه نمی‌کند. Premium معتبر تبلیغات برنامه را حذف می‌کند و استفاده آفلاین و PDF را فعال می‌سازد. دور زدن کنترل خرید، تبلیغ، کد تخفیف، Play Integrity یا امنیت، جعل Premium یا توزیع نسخه دستکاری‌شده گمراه‌کننده ممنوع است. مسئولیت حفاظت از داده محلی و فایل‌های خروجی با کاربر است. در صورت تأیید معتبر بازپرداخت، لغو، برگشت وجه یا خرید نامعتبر، Premium می‌تواند بدون حذف سوابق مالی لغو شود. حقوق اجباری مصرف‌کننده محفوظ می‌ماند. متن اصلی انگلیسی در حد مجاز قانون مرجع تفسیر است.',
    'he':
        'MIZAN הוא כלי אישי לרישום פיננסי ולתזכורות, ולא שירות בנקאי או ייעוץ השקעות, מס, משפטי, חשבונאי או פיננסי מפוקח. המשתמש חייב לבדוק בעצמו סכומים, מועדים, ריבית, מסים והתחייבויות חיצוניות. הגרסה החינמית דורשת אינטרנט, עשויה להציג פרסומות ואינה כוללת דוחות PDF. Premium תקף מסיר פרסומות שמוגשות על ידי האפליקציה ומאפשר שימוש לא מקוון ו-PDF. אסור לעקוף בקרות רכישה, פרסום, קידום, Play Integrity או אבטחה, לזייף זכאות Premium או להפיץ גרסאות משונות ומטעות. המשתמש אחראי להגנת נתונים מקומיים וקבצים מיוצאים. ניתן לבטל Premium לאחר אימות אמין של החזר, ביטול, chargeback או רכישה לא תקפה, בלי למחוק רשומות פיננסיות. זכויות צרכניות מחייבות נשמרות. הטקסט האנגלי הראשי הוא מקור הפרשנות ככל שהחוק מתיר.',
    'hi':
        'MIZAN व्यक्तिगत वित्तीय रिकॉर्ड और रिमाइंडर टूल है; यह बैंकिंग सेवा या निवेश, कर, कानूनी, लेखांकन अथवा विनियमित वित्तीय सलाह नहीं है। उपयोगकर्ता को राशि, देय तिथि, ब्याज, कर और बाहरी दायित्व स्वयं सत्यापित करने होंगे। मुफ़्त संस्करण को इंटरनेट चाहिए, विज्ञापन दिखा सकता है और PDF रिपोर्ट नहीं देता। वैध Premium ऐप-प्रदत्त विज्ञापन हटाता है और ऑफ़लाइन उपयोग व PDF सक्षम करता है। खरीद, विज्ञापन, प्रोमो, Play Integrity या सुरक्षा नियंत्रण को दरकिनार करना, Premium अधिकार जाली बनाना या भ्रामक संशोधित बिल्ड वितरित करना निषिद्ध है। स्थानीय डेटा और निर्यात की सुरक्षा उपयोगकर्ता की जिम्मेदारी है। विश्वसनीय रूप से सत्यापित refund, cancellation, chargeback या अमान्य खरीद पर Premium हटाया जा सकता है, वित्तीय रिकॉर्ड मिटाए बिना। अनिवार्य उपभोक्ता अधिकार बने रहते हैं। कानून की अनुमति तक अंग्रेज़ी master interpretation reference है।',
    'bn':
        'MIZAN ব্যক্তিগত আর্থিক রেকর্ড ও রিমাইন্ডার টুল; এটি ব্যাংকিং সেবা বা বিনিয়োগ, কর, আইন, হিসাবরক্ষণ কিংবা নিয়ন্ত্রিত আর্থিক পরামর্শ নয়। ব্যবহারকারীকে পরিমাণ, তারিখ, সুদ, কর ও বাইরের দায় নিজে যাচাই করতে হবে। বিনামূল্যের সংস্করণে ইন্টারনেট লাগে, বিজ্ঞাপন দেখাতে পারে এবং PDF রিপোর্ট নেই। বৈধ Premium অ্যাপের বিজ্ঞাপন সরায় এবং অফলাইন ব্যবহার ও PDF চালু করে। ক্রয়, বিজ্ঞাপন, প্রোমো, Play Integrity বা নিরাপত্তা নিয়ন্ত্রণ পাশ কাটানো, Premium জাল করা বা বিভ্রান্তিকর পরিবর্তিত build বিতরণ নিষিদ্ধ। স্থানীয় ডেটা ও export রক্ষা ব্যবহারকারীর দায়িত্ব। নির্ভরযোগ্যভাবে refund, cancellation, chargeback বা অবৈধ ক্রয় নিশ্চিত হলে Premium প্রত্যাহার হতে পারে, আর্থিক রেকর্ড না মুছে। বাধ্যতামূলক ভোক্তা অধিকার অক্ষুণ্ণ থাকে। আইন অনুমোদন করলে ইংরেজি master ব্যাখ্যার মূল রেফারেন্স।',
    'ur':
        'MIZAN ذاتی مالی ریکارڈ اور یاددہانی کا ٹول ہے، بینکاری سروس یا سرمایہ کاری، ٹیکس، قانونی، اکاؤنٹنگ یا باقاعدہ مالی مشورہ نہیں۔ صارف کو رقم، تاریخ، سود، ٹیکس اور بیرونی واجبات خود تصدیق کرنا ہوں گے۔ مفت ورژن کو انٹرنیٹ درکار ہے، اشتہار دکھا سکتا ہے اور PDF رپورٹ نہیں دیتا۔ درست Premium ایپ کے اشتہارات ختم کرتا اور آف لائن استعمال و PDF فعال کرتا ہے۔ خریداری، اشتہارات، پرومو، Play Integrity یا سکیورٹی کنٹرول کو بائی پاس کرنا، Premium حق جعلی بنانا یا گمراہ کن ترمیم شدہ build پھیلانا ممنوع ہے۔ مقامی ڈیٹا اور exports کی حفاظت صارف کی ذمہ داری ہے۔ قابل اعتماد طور پر refund، cancellation، chargeback یا غلط خرید کی تصدیق ہو تو Premium مالی ریکارڈ مٹائے بغیر واپس لیا جا سکتا ہے۔ لازمی صارف حقوق برقرار رہتے ہیں۔ قانون کی اجازت تک انگریزی master تشریح کا بنیادی حوالہ ہے۔',
    'id':
        'MIZAN adalah alat pencatatan dan pengingat keuangan pribadi, bukan layanan perbankan atau nasihat investasi, pajak, hukum, akuntansi, maupun keuangan yang diatur. Pengguna harus memverifikasi sendiri jumlah, tanggal jatuh tempo, bunga, pajak, dan kewajiban eksternal. Versi gratis memerlukan internet, dapat menampilkan iklan, dan tidak menyediakan laporan PDF. Premium yang valid menghapus iklan yang disajikan aplikasi serta mengaktifkan penggunaan offline dan PDF. Dilarang melewati kontrol pembelian, iklan, promosi, Play Integrity atau keamanan, memalsukan hak Premium, atau menyebarkan build modifikasi yang menyesatkan. Pengguna bertanggung jawab melindungi data lokal dan ekspor. Premium dapat dicabut ketika refund, pembatalan, chargeback, atau pembelian tidak valid diverifikasi secara andal, tanpa menghapus catatan keuangan. Hak konsumen wajib tetap berlaku. Master bahasa Inggris menjadi referensi interpretasi sejauh diizinkan hukum.',
    'ms':
        'MIZAN ialah alat rekod kewangan dan peringatan peribadi, bukan perkhidmatan perbankan atau nasihat pelaburan, cukai, undang-undang, perakaunan atau kewangan terkawal. Pengguna mesti mengesahkan sendiri amaun, tarikh akhir, faedah, cukai dan kewajipan luar. Versi percuma memerlukan internet, boleh memaparkan iklan dan tidak menyediakan laporan PDF. Premium yang sah membuang iklan yang disampaikan aplikasi serta membolehkan penggunaan luar talian dan PDF. Dilarang memintas kawalan pembelian, iklan, promosi, Play Integrity atau keselamatan, memalsukan hak Premium atau mengedarkan binaan diubah suai yang mengelirukan. Pengguna bertanggungjawab melindungi data tempatan dan eksport. Premium boleh ditarik balik apabila refund, pembatalan, chargeback atau pembelian tidak sah disahkan secara boleh dipercayai, tanpa memadam rekod kewangan. Hak pengguna mandatori kekal. Teks induk bahasa Inggeris menjadi rujukan tafsiran setakat dibenarkan undang-undang.',
    'fil':
        'Ang MIZAN ay personal na financial-record at reminder tool, hindi banking service o regulated investment, tax, legal, accounting o financial advice. Kailangang sariling i-verify ng user ang halaga, due date, interest, buwis at external obligations. Kailangan ng internet ang free version, maaaring magpakita ng ads at walang PDF reports. Ang valid Premium ay nag-aalis ng app-served ads at nagbibigay ng offline use at PDF. Bawal lampasan ang purchase, ad, promo, Play Integrity o security controls, pekein ang Premium entitlement, o mamahagi ng mapanlinlang na modified build. Responsibilidad ng user ang pagprotekta sa local data at exports. Maaaring alisin ang Premium kapag mapagkakatiwalaang nakumpirma ang refund, cancellation, chargeback o invalid purchase, nang hindi binubura ang financial records. Nananatili ang mandatory consumer rights. Ang English master ang interpretation reference kung pinapayagan ng batas.',
    'ko':
        'MIZAN은 개인 금융 기록 및 알림 도구이며 은행 서비스나 투자·세무·법률·회계 또는 규제 금융 자문이 아닙니다. 사용자는 금액, 납기, 이자, 세금 및 외부 지급 의무를 직접 확인해야 합니다. 무료 버전은 인터넷이 필요하고 광고를 표시할 수 있으며 PDF 보고서를 제공하지 않습니다. 유효한 Premium은 앱 광고를 제거하고 오프라인 사용과 PDF를 허용합니다. 구매·광고·프로모션·Play Integrity·보안 통제를 우회하거나 Premium 권한을 위조하거나 오해를 유발하는 수정 빌드를 배포하는 행위는 금지됩니다. 로컬 데이터와 내보낸 파일의 보호는 사용자 책임입니다. 환불, 취소, chargeback 또는 무효 구매가 신뢰성 있게 확인되면 금융 기록을 삭제하지 않고 Premium을 회수할 수 있습니다. 강행 소비자 권리는 유지됩니다. 법이 허용하는 범위에서 영어 master가 해석 기준입니다.',
    'ja':
        'MIZAN は個人向けの金融記録・リマインダー用ツールであり、銀行サービス、投資、税務、法律、会計または規制対象の金融助言ではありません。金額、期限、利息、税金、外部の支払義務は利用者自身で確認してください。無料版はインターネット接続が必要で、広告を表示する場合があり、PDF レポートは利用できません。有効な Premium はアプリ配信広告を除去し、オフライン利用と PDF を有効にします。購入、広告、プロモーション、Play Integrity、セキュリティ制御の回避、Premium 権利の偽造、誤解を招く改変ビルドの配布は禁止です。ローカルデータとエクスポートの保護は利用者の責任です。返金、取消、チャージバック、無効購入が確実に確認された場合、金融記録を削除せず Premium を取り消すことがあります。強行法上の消費者権利は維持されます。法令が許す範囲で英語 master が解釈の基準です。',
    'zh':
        'MIZAN 是个人财务记录和提醒工具，不是银行服务，也不提供受监管的投资、税务、法律、会计或金融建议。用户应自行核对金额、到期日、利息、税费和外部付款义务。免费版需要联网，可能显示广告，并不提供 PDF 报告。有效 Premium 会移除应用内广告并启用离线使用和 PDF。禁止绕过购买、广告、促销、Play Integrity 或安全控制，伪造 Premium 权限，或分发具有误导性的修改版本。用户负责保护本地数据和导出文件。若可靠确认发生退款、取消、拒付或无效购买，可撤销 Premium，但不会因此删除财务记录。法律规定不得放弃的消费者权利继续有效。在法律允许范围内，英文 master 是解释基准。',
    'vi':
        'MIZAN là công cụ ghi chép tài chính và nhắc nhở cá nhân, không phải dịch vụ ngân hàng hay tư vấn đầu tư, thuế, pháp lý, kế toán hoặc tài chính được quản lý. Người dùng phải tự xác minh số tiền, hạn thanh toán, lãi, thuế và nghĩa vụ bên ngoài. Bản miễn phí cần Internet, có thể hiển thị quảng cáo và không có báo cáo PDF. Premium hợp lệ loại bỏ quảng cáo do ứng dụng phục vụ và cho phép dùng ngoại tuyến cùng PDF. Cấm vượt qua kiểm soát mua hàng, quảng cáo, khuyến mãi, Play Integrity hoặc bảo mật, giả mạo quyền Premium hoặc phát hành bản sửa đổi gây hiểu nhầm. Người dùng chịu trách nhiệm bảo vệ dữ liệu cục bộ và file xuất. Premium có thể bị thu hồi khi refund, hủy, chargeback hoặc giao dịch không hợp lệ được xác minh đáng tin cậy, mà không xóa dữ liệu tài chính. Quyền người tiêu dùng bắt buộc vẫn được bảo lưu. Bản master tiếng Anh là tham chiếu diễn giải trong phạm vi pháp luật cho phép.',
    'th':
        'MIZAN เป็นเครื่องมือบันทึกการเงินและแจ้งเตือนส่วนบุคคล ไม่ใช่บริการธนาคารหรือคำแนะนำด้านการลงทุน ภาษี กฎหมาย บัญชี หรือการเงินที่อยู่ภายใต้การกำกับ ผู้ใช้ต้องตรวจสอบจำนวนเงิน วันครบกำหนด ดอกเบี้ย ภาษี และภาระภายนอกด้วยตนเอง รุ่นฟรีต้องใช้อินเทอร์เน็ต อาจแสดงโฆษณา และไม่มีรายงาน PDF Premium ที่ถูกต้องจะลบโฆษณาที่แอปให้บริการและเปิดใช้งานออฟไลน์กับ PDF ห้ามหลีกเลี่ยงการควบคุมการซื้อ โฆษณา โปรโมชัน Play Integrity หรือความปลอดภัย ปลอมสิทธิ Premium หรือเผยแพร่ build ที่ดัดแปลงเพื่อหลอกลวง ผู้ใช้รับผิดชอบการปกป้องข้อมูลในเครื่องและไฟล์ส่งออก Premium อาจถูกเพิกถอนเมื่อยืนยันได้อย่างน่าเชื่อถือว่ามีการคืนเงิน ยกเลิก chargeback หรือการซื้อไม่ถูกต้อง โดยไม่ลบข้อมูลการเงิน สิทธิผู้บริโภคที่กฎหมายบังคับยังคงอยู่ และข้อความ master ภาษาอังกฤษเป็นเกณฑ์ตีความเท่าที่กฎหมายอนุญาต',
    'sw':
        'MIZAN ni zana ya kumbukumbu za fedha binafsi na vikumbusho, si huduma ya benki wala ushauri wa uwekezaji, kodi, sheria, uhasibu au fedha unaodhibitiwa. Mtumiaji lazima athibitishe mwenyewe kiasi, tarehe za mwisho, riba, kodi na wajibu wa nje. Toleo la bure linahitaji intaneti, linaweza kuonyesha matangazo na halitoi ripoti za PDF. Premium halali huondoa matangazo ya programu na kuruhusu matumizi nje ya mtandao na PDF. Hairuhusiwi kupita vidhibiti vya ununuzi, matangazo, ofa, Play Integrity au usalama, kughushi haki ya Premium au kusambaza build iliyobadilishwa kwa udanganyifu. Mtumiaji anawajibika kulinda data ya ndani na mafaili yaliyohamishwa. Premium inaweza kuondolewa pale refund, kufutwa, chargeback au ununuzi batili unapothibitishwa kwa kuaminika bila kufuta rekodi za fedha. Haki za lazima za watumiaji zinaendelea. Maandishi kuu ya Kiingereza ndiyo rejea ya tafsiri kadiri sheria inavyoruhusu.',
  };

  static const Map<String, String> _purchase = {
    'tr':
        'Ömür boyu Premium Google Play üzerinden tek seferlik ve tüketilmeyen bir ürün olarak sunulur; abonelik değildir, otomatik yenilenmez ve tekrarlayan ücret doğurmaz. Ticari hedef yaklaşık 5 USD olsa da bağlayıcı fiyat ve para birimi satın alma anında Google Play ödeme ekranında görünen değerdir; uygulama sabit 5 USD metniyle tahsilat yapmaz. Satın alma, aynı geçerli Google Play hesabının sahipliği doğrulandığında uygulama açılışında/öne gelişinde sessizce geri yüklenir; görünür restore düğmesi yoktur. Doğrulanmış Premium, kullanıcının her açılışta internete zorlanmaması için cihazda önbelleğe alınabilir. Google Play bir iade, iptal, chargeback, revoke veya geçersiz sahiplik bildirirse Premium güvenilir doğrulamadan sonra kaldırılabilir. Üç tamamlanmış ödüllü reklam 24 saat geçici Premium verir. ESMANUR 7 gün, LEFFERION 3 gün geçici Premium verir; her kod uygun cihazda en fazla bir kez backend ve production Play Integrity doğrulamasıyla kullanılabilir. Promosyonların nakit değeri yoktur. Kanunen zorunlu iade, cayma ve tüketici hakları sözleşmeyle ortadan kaldırılamaz.',
    'en':
        'Lifetime Premium is sold through Google Play as a one-time non-consumable product; it is not a subscription, does not auto-renew and creates no recurring charge. The commercial target may be approximately USD 5, but the binding price and currency are those shown by Google Play at checkout, not a hard-coded USD amount in the App. Ownership is silently synchronized when the same valid Google Play account is verified at startup or resume; there is no visible restore button. A verified entitlement may be cached so an existing Premium user is not forced online at every launch. Premium may be removed after reliable confirmation of a Google Play refund, cancellation, chargeback, revocation or invalid ownership. Three completed rewarded ads grant 24 hours of temporary Premium. ESMANUR grants seven days and LEFFERION three days; each code may be redeemed at most once per eligible device through backend and production Play Integrity verification. Promotions have no cash value. Mandatory refund, withdrawal and consumer rights cannot be removed by contract.',
    'es':
        'Premium de por vida se vende en Google Play como producto no consumible de pago único; no es una suscripción, no se renueva automáticamente y no genera cargos recurrentes. El objetivo comercial puede rondar los 5 USD, pero el precio y la moneda vinculantes son los que muestra Google Play al pagar, no una cifra fija en la aplicación. La propiedad se sincroniza silenciosamente al verificar la misma cuenta válida de Google Play al iniciar o reanudar; no hay botón visible de restauración. El derecho verificado puede guardarse localmente para que un usuario Premium existente no necesite Internet en cada inicio. Premium puede retirarse tras confirmar de forma fiable un reembolso, cancelación, contracargo, revocación o propiedad inválida. Tres anuncios con recompensa completados otorgan 24 horas de Premium temporal. ESMANUR concede siete días y LEFFERION tres; cada código puede usarse como máximo una vez por dispositivo elegible mediante backend y Play Integrity en producción. Las promociones no tienen valor en efectivo. Los derechos obligatorios de reembolso, desistimiento y consumo no pueden eliminarse por contrato.',
    'pt-BR':
        'O Premium vitalício é vendido pelo Google Play como produto não consumível de pagamento único; não é assinatura, não renova automaticamente e não gera cobrança recorrente. A meta comercial pode ser próxima de USD 5, mas o preço e a moeda vinculantes são os mostrados pelo Google Play no checkout, não um valor fixo escrito no app. A propriedade é sincronizada silenciosamente quando a mesma conta válida do Google Play é verificada na abertura ou retomada; não existe botão visível de restauração. O direito verificado pode ser mantido localmente para que um usuário Premium não seja obrigado a ficar online a cada abertura. O Premium pode ser removido após confirmação confiável de reembolso, cancelamento, chargeback, revogação ou propriedade inválida. Três anúncios recompensados concluídos concedem 24 horas de Premium temporário. ESMANUR concede sete dias e LEFFERION três; cada código pode ser usado no máximo uma vez por dispositivo elegível, com backend e Play Integrity em produção. Promoções não têm valor em dinheiro. Direitos obrigatórios de reembolso, arrependimento e consumidor não podem ser eliminados por contrato.',
    'pt-PT':
        'O Premium vitalício é vendido pelo Google Play como produto não consumível de pagamento único; não é subscrição, não renova automaticamente e não cria cobrança recorrente. O objetivo comercial pode rondar 5 USD, mas o preço e moeda vinculativos são os apresentados pelo Google Play no checkout e não um valor fixo na aplicação. A propriedade é sincronizada silenciosamente quando a mesma conta Google Play válida é verificada no arranque ou regresso à aplicação; não existe botão visível de restauro. O direito verificado pode ser guardado localmente para que um utilizador Premium não tenha de estar online em cada abertura. O Premium pode ser removido após confirmação fiável de reembolso, cancelamento, chargeback, revogação ou propriedade inválida. Três anúncios recompensados concluídos dão 24 horas de Premium temporário. ESMANUR concede sete dias e LEFFERION três; cada código pode ser utilizado no máximo uma vez por dispositivo elegível, com backend e Play Integrity em produção. As promoções não têm valor monetário. Direitos obrigatórios de reembolso, desistência e consumidor não podem ser afastados por contrato.',
    'fr':
        'Le Premium à vie est vendu via Google Play comme produit non consommable à paiement unique ; ce n’est pas un abonnement, il ne se renouvelle pas automatiquement et n’entraîne aucun paiement récurrent. L’objectif commercial peut être d’environ 5 USD, mais le prix et la devise contractuels sont ceux affichés par Google Play au paiement, et non une valeur fixe écrite dans l’application. La propriété est synchronisée silencieusement lorsque le même compte Google Play valide est vérifié au démarrage ou à la reprise ; aucun bouton de restauration visible n’est prévu. Un droit vérifié peut être mis en cache pour qu’un utilisateur Premium existant ne soit pas obligé d’être en ligne à chaque lancement. Le Premium peut être retiré après confirmation fiable d’un remboursement, d’une annulation, d’un rejet de paiement, d’une révocation ou d’une propriété invalide. Trois publicités récompensées terminées donnent 24 heures de Premium temporaire. ESMANUR donne sept jours et LEFFERION trois ; chaque code est utilisable au maximum une fois par appareil éligible avec vérification backend et Play Integrity en production. Les promotions n’ont pas de valeur monétaire. Les droits impératifs de remboursement, rétractation et consommation restent applicables.',
    'de':
        'Lifetime Premium wird über Google Play als einmaliges, nicht verbrauchbares Produkt verkauft; es ist kein Abonnement, verlängert sich nicht automatisch und verursacht keine wiederkehrenden Gebühren. Das kommerzielle Ziel kann ungefähr 5 USD sein, maßgeblich sind jedoch Preis und Währung, die Google Play beim Checkout anzeigt, nicht ein fest in der App eingetragener Dollarbetrag. Die Eigentümerschaft wird beim Start oder Zurückkehren still synchronisiert, wenn dasselbe gültige Google-Play-Konto bestätigt wird; eine sichtbare Wiederherstellen-Schaltfläche gibt es nicht. Ein bestätigtes Recht darf lokal zwischengespeichert werden, damit Premium-Nutzer nicht bei jedem Start online sein müssen. Premium kann nach zuverlässiger Bestätigung einer Erstattung, Stornierung, Rückbuchung, Widerrufung oder ungültigen Eigentümerschaft entzogen werden. Drei abgeschlossene Rewarded Ads geben 24 Stunden temporäres Premium. ESMANUR gibt sieben Tage, LEFFERION drei; jeder Code ist pro geeignetem Gerät höchstens einmal mit Backend- und Production-Play-Integrity-Prüfung nutzbar. Promotions haben keinen Geldwert. Zwingende Erstattungs-, Widerrufs- und Verbraucherrechte bleiben bestehen.',
    'it':
        'Il Premium a vita viene venduto tramite Google Play come prodotto non consumabile con pagamento una tantum; non è un abbonamento, non si rinnova automaticamente e non genera addebiti ricorrenti. L’obiettivo commerciale può essere circa 5 USD, ma prezzo e valuta vincolanti sono quelli mostrati da Google Play al checkout, non un importo fisso scritto nell’app. La proprietà viene sincronizzata silenziosamente quando lo stesso account Google Play valido è verificato all’avvio o alla ripresa; non è previsto un pulsante di ripristino visibile. Il diritto verificato può essere memorizzato localmente per evitare di obbligare un utente Premium a collegarsi a Internet a ogni avvio. Il Premium può essere rimosso dopo conferma affidabile di rimborso, annullamento, chargeback, revoca o proprietà non valida. Tre annunci con premio completati concedono 24 ore di Premium temporaneo. ESMANUR concede sette giorni e LEFFERION tre; ogni codice è utilizzabile al massimo una volta per dispositivo idoneo con verifica backend e Play Integrity in produzione. Le promozioni non hanno valore in denaro. I diritti inderogabili di rimborso, recesso e tutela del consumatore restano validi.',
    'nl':
        'Levenslang Premium wordt via Google Play verkocht als een eenmalig niet-verbruikbaar product; het is geen abonnement, wordt niet automatisch verlengd en veroorzaakt geen terugkerende kosten. Het commerciële doel kan ongeveer USD 5 zijn, maar de bindende prijs en valuta zijn wat Google Play bij het afrekenen toont, niet een vast bedrag in de app. Eigendom wordt stil gesynchroniseerd wanneer hetzelfde geldige Google Play-account bij starten of hervatten wordt bevestigd; er is geen zichtbare herstelknop. Een bevestigd recht mag lokaal worden gecachet zodat een bestaande Premium-gebruiker niet bij elke start online hoeft te zijn. Premium kan worden verwijderd na betrouwbare bevestiging van terugbetaling, annulering, chargeback, intrekking of ongeldig eigendom. Drie voltooide beloonde advertenties geven 24 uur tijdelijk Premium. ESMANUR geeft zeven dagen en LEFFERION drie; elke code kan maximaal eenmaal per geschikt apparaat worden gebruikt met backend- en production Play Integrity-verificatie. Promoties hebben geen geldwaarde. Verplichte rechten op terugbetaling, herroeping en consumentenbescherming blijven gelden.',
    'pl':
        'Premium bezterminowe jest sprzedawane w Google Play jako jednorazowy produkt niekonsumpcyjny; nie jest subskrypcją, nie odnawia się automatycznie i nie powoduje opłat cyklicznych. Cel handlowy może wynosić około 5 USD, lecz wiążące są cena i waluta pokazane przez Google Play podczas płatności, a nie stała kwota wpisana w aplikacji. Własność jest synchronizowana po cichu po potwierdzeniu tego samego ważnego konta Google Play przy uruchomieniu lub powrocie do aplikacji; nie ma widocznego przycisku przywracania. Potwierdzone uprawnienie może być zapisane lokalnie, aby istniejący użytkownik Premium nie musiał łączyć się z Internetem przy każdym starcie. Premium może zostać usunięte po wiarygodnym potwierdzeniu zwrotu, anulowania, chargebacku, cofnięcia lub nieważnej własności. Trzy ukończone reklamy z nagrodą dają 24 godziny tymczasowego Premium. ESMANUR daje siedem dni, LEFFERION trzy; każdy kod można wykorzystać najwyżej raz na kwalifikującym się urządzeniu przy weryfikacji backendu i Play Integrity w produkcji. Promocje nie mają wartości pieniężnej. Bezwzględnie obowiązujące prawa do zwrotu, odstąpienia i ochrony konsumenta pozostają zachowane.',
    'ro':
        'Premium pe viață este vândut prin Google Play ca produs neconsumabil cu plată unică; nu este abonament, nu se reînnoiește automat și nu generează taxe recurente. Ținta comercială poate fi aproximativ 5 USD, însă prețul și moneda obligatorii sunt cele afișate de Google Play la plată, nu o valoare fixă scrisă în aplicație. Proprietatea este sincronizată silențios când același cont Google Play valid este verificat la pornire sau revenire; nu există buton vizibil de restaurare. Dreptul verificat poate fi memorat local pentru ca un utilizator Premium existent să nu fie obligat să fie online la fiecare lansare. Premium poate fi eliminat după confirmarea fiabilă a unei rambursări, anulări, chargeback, revocări sau proprietăți invalide. Trei reclame cu recompensă finalizate oferă 24 de ore Premium temporar. ESMANUR oferă șapte zile și LEFFERION trei; fiecare cod poate fi folosit cel mult o dată pe dispozitiv eligibil cu verificare backend și Play Integrity în producție. Promoțiile nu au valoare în numerar. Drepturile obligatorii de rambursare, retragere și protecție a consumatorului rămân valabile.',
    'el':
        'Το Premium εφ’ όρου ζωής πωλείται μέσω Google Play ως εφάπαξ μη αναλώσιμο προϊόν· δεν είναι συνδρομή, δεν ανανεώνεται αυτόματα και δεν δημιουργεί επαναλαμβανόμενη χρέωση. Ο εμπορικός στόχος μπορεί να είναι περίπου 5 USD, όμως δεσμευτική τιμή και νόμισμα είναι αυτά που εμφανίζει το Google Play στο checkout, όχι σταθερό ποσό μέσα στην εφαρμογή. Η ιδιοκτησία συγχρονίζεται σιωπηρά όταν επαληθεύεται ο ίδιος έγκυρος λογαριασμός Google Play κατά την έναρξη ή επιστροφή· δεν υπάρχει ορατό κουμπί επαναφοράς. Ένα επαληθευμένο δικαίωμα μπορεί να αποθηκευτεί τοπικά ώστε ο υπάρχων Premium χρήστης να μη χρειάζεται Internet σε κάθε εκκίνηση. Το Premium μπορεί να αφαιρεθεί μετά από αξιόπιστη επιβεβαίωση επιστροφής, ακύρωσης, αντιλογισμού, ανάκλησης ή άκυρης ιδιοκτησίας. Τρεις ολοκληρωμένες διαφημίσεις με ανταμοιβή δίνουν 24 ώρες προσωρινού Premium. Το ESMANUR δίνει επτά ημέρες και το LEFFERION τρεις· κάθε κωδικός χρησιμοποιείται το πολύ μία φορά ανά επιλέξιμη συσκευή με backend και Play Integrity στην παραγωγή. Οι προσφορές δεν έχουν χρηματική αξία. Τα υποχρεωτικά δικαιώματα επιστροφής, υπαναχώρησης και καταναλωτή διατηρούνται.',
    'ru':
        'Бессрочный Premium продается через Google Play как разовый непотребляемый товар; это не подписка, он не продлевается автоматически и не создает регулярных списаний. Коммерческая цель может быть около 5 USD, однако обязательными являются цена и валюта, показанные Google Play при оплате, а не фиксированная сумма в приложении. Право собственности тихо синхронизируется при подтверждении того же действующего аккаунта Google Play при запуске или возврате в приложение; видимой кнопки восстановления нет. Подтвержденное право может кэшироваться локально, чтобы действующий Premium-пользователь не был вынужден выходить в интернет при каждом запуске. Premium может быть снят после надежного подтверждения возврата, отмены, chargeback, отзыва или недействительного владения. Три завершенные рекламы с наградой дают 24 часа временного Premium. ESMANUR дает семь дней, LEFFERION три; каждый код можно использовать не более одного раза на подходящем устройстве с backend- и production Play Integrity-проверкой. Промо не имеют денежной стоимости. Обязательные права на возврат, отказ и защиту потребителя сохраняются.',
    'uk':
        'Безстроковий Premium продається через Google Play як одноразовий невитратний товар; це не підписка, він не поновлюється автоматично й не створює регулярних списань. Комерційна ціль може бути близько 5 USD, але обов’язковими є ціна та валюта, показані Google Play під час оплати, а не фіксована сума в застосунку. Право власності тихо синхронізується після підтвердження того самого чинного акаунта Google Play при запуску або поверненні до застосунку; видимої кнопки відновлення немає. Підтверджене право може кешуватися локально, щоб чинний Premium-користувач не був змушений виходити в Інтернет під час кожного запуску. Premium може бути знятий після надійного підтвердження повернення, скасування, chargeback, відкликання або недійсного володіння. Три завершені реклами з винагородою дають 24 години тимчасового Premium. ESMANUR дає сім днів, LEFFERION три; кожен код можна використати не більше одного разу на придатному пристрої з backend- і production Play Integrity-перевіркою. Промо не мають грошової вартості. Обов’язкові права на повернення, відмову й захист споживача зберігаються.',
    'ar':
        'يُباع Premium مدى الحياة عبر Google Play كمنتج غير قابل للاستهلاك بدفعة واحدة؛ ليس اشتراكًا، ولا يتجدد تلقائيًا، ولا ينشئ رسومًا دورية. قد يكون الهدف التجاري نحو 5 دولارات أمريكية، لكن السعر والعملة الملزمان هما ما يعرضه Google Play عند الدفع، وليس مبلغًا ثابتًا داخل التطبيق. تتم مزامنة الملكية بصمت عند التحقق من الحساب نفسه في Google Play عند بدء التطبيق أو العودة إليه؛ ولا يوجد زر استعادة ظاهر. يمكن تخزين الاستحقاق المتحقق منه محليًا حتى لا يُجبر مستخدم Premium الحالي على الاتصال بالإنترنت في كل تشغيل. يمكن إزالة Premium بعد التحقق الموثوق من استرداد أو إلغاء أو اعتراض مالي أو سحب أو ملكية غير صالحة. تمنح ثلاثة إعلانات بمكافأة مكتملة 24 ساعة من Premium المؤقت. يمنح ESMANUR سبعة أيام وLEFFERION ثلاثة؛ ويمكن استخدام كل رمز مرة واحدة كحد أقصى لكل جهاز مؤهل بعد تحقق الخادم وPlay Integrity في الإنتاج. العروض ليس لها قيمة نقدية. لا يمكن للعقد إلغاء حقوق الاسترداد والعدول وحماية المستهلك الإلزامية.',
    'fa':
        'Premium مادام‌العمر از طریق Google Play به‌صورت محصول غیرمصرفی با پرداخت یک‌باره فروخته می‌شود؛ اشتراک نیست، خودکار تمدید نمی‌شود و هزینه دوره‌ای ایجاد نمی‌کند. هدف تجاری می‌تواند حدود ۵ دلار باشد، اما قیمت و ارز معتبر همان چیزی است که Google Play هنگام پرداخت نمایش می‌دهد، نه مبلغ ثابت داخل برنامه. مالکیت هنگام شروع یا بازگشت برنامه و با تأیید همان حساب معتبر Google Play به‌صورت بی‌صدا همگام می‌شود و دکمه بازیابی نمایان وجود ندارد. حق تأییدشده می‌تواند محلی ذخیره شود تا کاربر Premium مجبور نباشد در هر اجرا آنلاین باشد. پس از تأیید معتبر بازپرداخت، لغو، chargeback، revoke یا مالکیت نامعتبر، Premium قابل حذف است. سه تبلیغ جایزه‌دار کامل‌شده ۲۴ ساعت Premium موقت می‌دهد. ESMANUR هفت روز و LEFFERION سه روز می‌دهد؛ هر کد برای هر دستگاه واجد شرایط حداکثر یک بار با تأیید backend و Play Integrity در production قابل استفاده است. پروموشن ارزش نقدی ندارد. حقوق اجباری بازپرداخت، انصراف و مصرف‌کننده با قرارداد حذف نمی‌شود.',
    'he':
        'Premium לכל החיים נמכר דרך Google Play כמוצר לא-מתכלה בתשלום חד-פעמי; הוא אינו מנוי, אינו מתחדש אוטומטית ואינו יוצר חיוב חוזר. היעד המסחרי עשוי להיות כ-5 דולר, אך המחיר והמטבע המחייבים הם אלה שמוצגים ב-Google Play בעת התשלום, ולא סכום קבוע באפליקציה. הבעלות מסונכרנת בשקט כאשר אותו חשבון Google Play תקף מאומת בהפעלה או בחזרה לאפליקציה; אין כפתור שחזור גלוי. ניתן לשמור זכאות מאומתת מקומית כדי שמשתמש Premium קיים לא יידרש לאינטרנט בכל הפעלה. ניתן להסיר Premium לאחר אימות אמין של החזר, ביטול, chargeback, שלילה או בעלות לא תקפה. שלוש פרסומות מתוגמלות שהושלמו מעניקות 24 שעות Premium זמני. ESMANUR מעניק שבעה ימים ו-LEFFERION שלושה; כל קוד ניתן למימוש לכל היותר פעם אחת בכל מכשיר זכאי באמצעות backend ו-Play Integrity ב-production. למבצעים אין ערך כספי. זכויות החזר, ביטול והגנת צרכן מחייבות אינן ניתנות לביטול בחוזה.',
    'hi':
        'आजीवन Premium Google Play के माध्यम से एक बार खरीदे जाने वाले non-consumable product के रूप में बेचा जाता है; यह subscription नहीं है, auto-renew नहीं होता और recurring charge नहीं बनाता। व्यावसायिक लक्ष्य लगभग USD 5 हो सकता है, लेकिन बाध्यकारी कीमत और मुद्रा वही है जो checkout पर Google Play दिखाता है, ऐप में लिखा कोई स्थिर USD मूल्य नहीं। उसी वैध Google Play खाते की ownership startup या resume पर सत्यापित होने पर चुपचाप sync होती है; कोई visible restore button नहीं है। सत्यापित entitlement local cache हो सकता है ताकि मौजूदा Premium user को हर launch पर online न होना पड़े। विश्वसनीय Google Play refund, cancellation, chargeback, revocation या invalid ownership के बाद Premium हटाया जा सकता है। तीन पूर्ण rewarded ads 24 घंटे का temporary Premium देते हैं। ESMANUR सात दिन और LEFFERION तीन दिन देता है; backend और production Play Integrity verification के साथ प्रत्येक code eligible device पर अधिकतम एक बार redeem हो सकता है। Promo का cash value नहीं है। अनिवार्य refund, withdrawal और consumer rights contract से हटाए नहीं जा सकते।',
    'bn':
        'আজীবন Premium Google Play-এর মাধ্যমে একবার কেনা যায় এমন non-consumable product; এটি subscription নয়, auto-renew হয় না এবং recurring charge তৈরি করে না। ব্যবসায়িক লক্ষ্য প্রায় USD 5 হতে পারে, তবে বাধ্যতামূলক মূল্য ও মুদ্রা হলো checkout-এ Google Play যা দেখায়, অ্যাপে লেখা স্থির USD অঙ্ক নয়। একই বৈধ Google Play account-এর ownership startup বা resume-এ যাচাই হলে নীরবে sync হয়; দৃশ্যমান restore button নেই। যাচাই করা entitlement local cache হতে পারে যাতে বিদ্যমান Premium ব্যবহারকারীকে প্রতিবার launch-এ online হতে না হয়। নির্ভরযোগ্য refund, cancellation, chargeback, revocation বা invalid ownership নিশ্চিত হলে Premium সরানো হতে পারে। তিনটি সম্পূর্ণ rewarded ad ২৪ ঘণ্টা temporary Premium দেয়। ESMANUR সাত দিন এবং LEFFERION তিন দিন দেয়; backend ও production Play Integrity verification-এর মাধ্যমে প্রতিটি code eligible device-এ সর্বোচ্চ একবার redeem করা যাবে। Promo-এর cash value নেই। বাধ্যতামূলক refund, withdrawal ও consumer rights চুক্তি দিয়ে বাতিল করা যায় না।',
    'ur':
        'تاحیات Premium Google Play کے ذریعے ایک بار خریدے جانے والے non-consumable product کے طور پر فروخت ہوتا ہے؛ یہ subscription نہیں، auto-renew نہیں ہوتا اور recurring charge نہیں بناتا۔ تجارتی ہدف تقریباً USD 5 ہو سکتا ہے مگر لازمی قیمت اور کرنسی وہی ہے جو checkout پر Google Play دکھاتا ہے، ایپ میں لکھا مستقل USD نمبر نہیں۔ اسی درست Google Play account کی ownership startup یا resume پر تصدیق ہو تو خاموشی سے sync ہوتی ہے؛ کوئی visible restore button نہیں۔ تصدیق شدہ entitlement مقامی طور پر cache ہو سکتا ہے تاکہ موجودہ Premium صارف ہر launch پر online ہونے پر مجبور نہ ہو۔ قابل اعتماد refund، cancellation، chargeback، revocation یا invalid ownership کی تصدیق پر Premium ہٹایا جا سکتا ہے۔ تین مکمل rewarded ads 24 گھنٹے temporary Premium دیتے ہیں۔ ESMANUR سات دن اور LEFFERION تین دن دیتا ہے؛ backend اور production Play Integrity verification کے ساتھ ہر code eligible device پر زیادہ سے زیادہ ایک بار redeem ہو سکتا ہے۔ Promo کی cash value نہیں۔ لازمی refund، withdrawal اور consumer rights contract سے ختم نہیں کیے جا سکتے۔',
    'id':
        'Lifetime Premium dijual melalui Google Play sebagai produk non-consumable sekali bayar; bukan langganan, tidak memperbarui otomatis, dan tidak menimbulkan biaya berulang. Target komersial dapat sekitar USD 5, tetapi harga dan mata uang yang mengikat adalah yang ditampilkan Google Play saat checkout, bukan angka USD tetap di aplikasi. Kepemilikan disinkronkan secara diam-diam ketika akun Google Play valid yang sama diverifikasi saat startup atau resume; tidak ada tombol restore yang terlihat. Hak terverifikasi dapat dicache lokal agar pengguna Premium yang sudah sah tidak diwajibkan online di setiap pembukaan. Premium dapat dicabut setelah refund, pembatalan, chargeback, revocation, atau kepemilikan tidak valid diverifikasi secara andal. Tiga rewarded ad yang selesai memberikan 24 jam Premium sementara. ESMANUR memberi tujuh hari dan LEFFERION tiga hari; setiap kode dapat ditukar maksimal sekali per perangkat yang memenuhi syarat melalui backend dan verifikasi Play Integrity production. Promosi tidak memiliki nilai tunai. Hak refund, pembatalan, dan konsumen yang wajib tidak dapat dihapus oleh kontrak.',
    'ms':
        'Premium seumur hidup dijual melalui Google Play sebagai produk tidak boleh habis guna dengan bayaran sekali; ia bukan langganan, tidak diperbaharui automatik dan tidak mewujudkan caj berulang. Sasaran komersial boleh sekitar USD 5, tetapi harga dan mata wang yang mengikat ialah yang dipaparkan Google Play ketika checkout, bukan nilai USD tetap dalam aplikasi. Pemilikan disegerakkan secara senyap apabila akaun Google Play sah yang sama disahkan ketika startup atau resume; tiada butang restore yang kelihatan. Hak yang disahkan boleh dicache secara tempatan supaya pengguna Premium sedia ada tidak dipaksa online setiap kali membuka aplikasi. Premium boleh ditarik balik selepas refund, pembatalan, chargeback, revocation atau pemilikan tidak sah disahkan secara boleh dipercayai. Tiga rewarded ads yang lengkap memberikan 24 jam Premium sementara. ESMANUR memberi tujuh hari dan LEFFERION tiga hari; setiap kod boleh ditebus maksimum sekali bagi setiap peranti layak melalui backend dan pengesahan Play Integrity production. Promosi tiada nilai tunai. Hak refund, penarikan diri dan pengguna yang mandatori tidak boleh dihapuskan oleh kontrak.',
    'fil':
        'Ang Lifetime Premium ay ibinebenta sa Google Play bilang one-time non-consumable product; hindi ito subscription, hindi auto-renewing at walang recurring charge. Maaaring humigit-kumulang USD 5 ang commercial target, pero ang binding na presyo at currency ay ang ipinapakita ng Google Play sa checkout, hindi fixed USD na nakasulat sa app. Tahimik na sini-sync ang ownership kapag nabe-verify ang parehong valid Google Play account sa startup o resume; walang visible restore button. Maaaring i-cache locally ang verified entitlement para hindi kailangang online ang existing Premium user sa bawat launch. Maaaring alisin ang Premium matapos mapagkakatiwalaang makumpirma ang refund, cancellation, chargeback, revocation o invalid ownership. Ang tatlong completed rewarded ads ay nagbibigay ng 24 oras na temporary Premium. Ang ESMANUR ay pitong araw at LEFFERION ay tatlong araw; bawat code ay maaaring i-redeem nang isang beses lamang bawat eligible device sa pamamagitan ng backend at production Play Integrity verification. Walang cash value ang promos. Hindi maaaring alisin ng kontrata ang mandatory refund, withdrawal at consumer rights.',
    'ko':
        '평생 Premium은 Google Play에서 1회 결제하는 비소모성 상품으로 판매됩니다. 구독이 아니며 자동 갱신되지 않고 반복 결제가 발생하지 않습니다. 상업적 목표 가격은 약 USD 5일 수 있지만 실제 구속력 있는 가격과 통화는 앱에 고정된 금액이 아니라 결제 시 Google Play가 표시하는 값입니다. 동일한 유효 Google Play 계정의 소유권이 시작 또는 앱 복귀 시 확인되면 자동으로 조용히 동기화되며, 별도의 복원 버튼은 없습니다. 이미 확인된 Premium 사용자가 매번 온라인일 필요가 없도록 entitlement를 로컬 캐시할 수 있습니다. Google Play 환불, 취소, chargeback, 철회 또는 무효 소유권이 신뢰성 있게 확인되면 Premium을 제거할 수 있습니다. 완료된 보상형 광고 3개는 24시간 임시 Premium을 제공합니다. ESMANUR는 7일, LEFFERION은 3일을 제공하며, 각 코드는 backend 및 production Play Integrity 검증을 거쳐 적격 기기당 최대 1회 사용할 수 있습니다. 프로모션은 현금 가치가 없습니다. 강행 환불·철회·소비자 권리는 계약으로 배제할 수 없습니다.',
    'ja':
        '永久 Premium は Google Play で一回払いの非消費型商品として販売されます。サブスクリプションではなく、自動更新も継続課金もありません。商業上の目標価格は約 5 USD でも、拘束力のある価格と通貨はアプリに固定記載した金額ではなく、購入時に Google Play が表示するものです。同じ有効な Google Play アカウントの所有権が起動時または復帰時に確認されると、表示される復元ボタンなしで自動的に同期されます。既存の Premium 利用者が毎回オンラインになる必要がないよう、確認済み entitlement をローカルにキャッシュできます。返金、取消、チャージバック、権利取消、無効な所有権が確実に確認された場合、Premium を取り消すことがあります。完了したリワード広告 3 本で 24 時間の一時 Premium を付与します。ESMANUR は 7 日、LEFFERION は 3 日で、各コードは backend と production Play Integrity 検証により適格端末ごとに最大 1 回利用できます。プロモーションに換金価値はありません。法令上必須の返金、撤回、消費者権利は契約で排除できません。',
    'zh':
        '终身 Premium 通过 Google Play 以一次性非消耗型商品出售；它不是订阅，不会自动续费，也不会产生周期性收费。商业目标价格可以约为 5 美元，但具有约束力的价格和币种是结账时 Google Play 显示的内容，而不是应用中写死的美元金额。启动或恢复应用时，只要验证到同一个有效 Google Play 账号的所有权，就会静默同步；不会提供可见的恢复按钮。已验证的权限可在本地缓存，使现有 Premium 用户无需每次启动都联网。若可靠确认发生 Google Play 退款、取消、拒付、撤销或无效所有权，可移除 Premium。完成 3 个激励广告可获得 24 小时临时 Premium。ESMANUR 提供 7 天，LEFFERION 提供 3 天；每个代码通过 backend 和 production Play Integrity 验证后，每台符合条件的设备最多使用一次。促销没有现金价值。法律规定不得放弃的退款、撤回和消费者权利不能通过合同排除。',
    'vi':
        'Lifetime Premium được bán qua Google Play dưới dạng sản phẩm không tiêu hao thanh toán một lần; không phải thuê bao, không tự gia hạn và không tạo phí định kỳ. Mục tiêu thương mại có thể khoảng 5 USD, nhưng giá và đơn vị tiền tệ có hiệu lực là giá Google Play hiển thị khi thanh toán, không phải số USD cố định trong ứng dụng. Quyền sở hữu được đồng bộ âm thầm khi cùng một tài khoản Google Play hợp lệ được xác minh lúc khởi động hoặc quay lại ứng dụng; không có nút khôi phục hiển thị. Quyền đã xác minh có thể được cache cục bộ để người dùng Premium hiện có không buộc phải online mỗi lần mở. Premium có thể bị gỡ sau khi xác minh đáng tin cậy refund, hủy, chargeback, revocation hoặc quyền sở hữu không hợp lệ. Ba quảng cáo có thưởng hoàn tất cấp 24 giờ Premium tạm thời. ESMANUR cấp bảy ngày và LEFFERION ba ngày; mỗi mã chỉ được đổi tối đa một lần trên mỗi thiết bị đủ điều kiện qua backend và production Play Integrity. Khuyến mãi không có giá trị tiền mặt. Quyền refund, rút lại và bảo vệ người tiêu dùng bắt buộc không thể bị loại bỏ bằng hợp đồng.',
    'th':
        'Lifetime Premium จำหน่ายผ่าน Google Play เป็นผลิตภัณฑ์แบบ non-consumable ชำระครั้งเดียว ไม่ใช่ subscription ไม่ต่ออายุอัตโนมัติ และไม่มีค่าบริการซ้ำ เป้าหมายทางการค้าอาจอยู่ราว 5 USD แต่ราคาและสกุลเงินที่มีผลคือค่าที่ Google Play แสดงตอน checkout ไม่ใช่จำนวน USD ที่เขียนตายตัวในแอป เมื่อยืนยันการเป็นเจ้าของด้วยบัญชี Google Play ที่ถูกต้องบัญชีเดิมตอน startup หรือ resume ระบบจะซิงก์แบบเงียบโดยไม่มีปุ่ม restore ที่มองเห็นได้ สิทธิที่ยืนยันแล้วอาจ cache ในเครื่องเพื่อไม่บังคับผู้ใช้ Premium เดิมให้ online ทุกครั้งที่เปิด หากยืนยัน refund การยกเลิก chargeback การเพิกถอน หรือ ownership ไม่ถูกต้องได้อย่างน่าเชื่อถือ Premium อาจถูกนำออก โฆษณาแบบมีรางวัลที่ดูครบ 3 รายการให้ Premium ชั่วคราว 24 ชั่วโมง ESMANUR ให้ 7 วัน และ LEFFERION ให้ 3 วัน แต่ละรหัสใช้ได้สูงสุดหนึ่งครั้งต่ออุปกรณ์ที่เข้าเกณฑ์ผ่าน backend และ production Play Integrity โปรโมชันไม่มีมูลค่าเป็นเงิน สิทธิคืนเงิน ถอนตัว และคุ้มครองผู้บริโภคที่กฎหมายบังคับไม่สามารถตัดออกด้วยสัญญาได้',
    'sw':
        'Lifetime Premium inauzwa kupitia Google Play kama bidhaa isiyotumika mara moja kwa malipo ya mara moja; si usajili, haijisasishi kiotomatiki na haisababishi malipo ya kurudia. Lengo la kibiashara linaweza kuwa karibu USD 5, lakini bei na sarafu zinazofunga ni zile zinazoonyeshwa na Google Play wakati wa checkout, si kiasi cha USD kilichowekwa moja kwa moja kwenye programu. Umiliki unasawazishwa kimya pale akaunti ileile halali ya Google Play inapothibitishwa wakati wa startup au resume; hakuna kitufe cha restore kinachoonekana. Haki iliyothibitishwa inaweza kuhifadhiwa kifaani ili mtumiaji wa Premium asihitajike kuwa online kila kufungua. Premium inaweza kuondolewa baada ya refund, kughairi, chargeback, revocation au umiliki batili kuthibitishwa kwa kuaminika. Matangazo matatu yenye zawadi yaliyokamilika hutoa saa 24 za Premium ya muda. ESMANUR hutoa siku saba na LEFFERION siku tatu; kila msimbo unaweza kutumika mara moja tu kwa kila kifaa kinachostahiki kupitia backend na production Play Integrity. Ofa hazina thamani ya pesa. Haki za lazima za refund, kujiondoa na ulinzi wa mtumiaji haziwezi kuondolewa kwa mkataba.',
  };

  static String overview(LegalDocumentType type, String languageTag) {
    final normalized = switch (languageTag) {
      'pt_BR' || 'pt-br' => 'pt-BR',
      'pt_PT' || 'pt-pt' => 'pt-PT',
      'de-DE' => 'de',
      'it-IT' => 'it',
      'nl-NL' => 'nl',
      'pl-PL' => 'pl',
      'ro-RO' => 'ro',
      'el-GR' => 'el',
      'ru-RU' => 'ru',
      'uk-UA' => 'uk',
      'ar-SA' => 'ar',
      'fa-IR' => 'fa',
      'he-IL' => 'he',
      'hi-IN' => 'hi',
      'bn-BD' => 'bn',
      'ur-PK' => 'ur',
      'id-ID' => 'id',
      'ms-MY' => 'ms',
      'fil-PH' => 'fil',
      'ko-KR' => 'ko',
      'ja-JP' => 'ja',
      'zh-CN' => 'zh',
      'vi-VN' => 'vi',
      'th-TH' => 'th',
      'sw-TZ' => 'sw',
      _ => languageTag,
    };
    return switch (type) {
      LegalDocumentType.terms => _terms[normalized] ?? _terms['en']!,
      LegalDocumentType.purchase => _purchase[normalized] ?? _purchase['en']!,
      LegalDocumentType.privacy => MizanLegalDocuments.document(
        type,
        normalized,
      ).localizedOverview,
    };
  }

  static Set<String> get supportedLanguageTags => _terms.keys.toSet();
}
