enum LegalDocumentType { privacy, terms, purchase }

class LegalDocument {
  const LegalDocument({
    required this.type,
    required this.title,
    required this.localizedOverview,
    required this.englishMaster,
  });

  final LegalDocumentType type;
  final String title;
  final String localizedOverview;
  final String englishMaster;
}

abstract final class MizanLegalDocuments {
  static const String effectiveDate = '2026-08-16';

  static const String _privacyEnglish = '''
PRIVACY POLICY — LEFFERION PRIME - MIZAN
Effective date: 16 August 2026

1. Scope and publisher. This Privacy Policy explains how the LEFFERION PRIME - MIZAN application (the “App”) handles information. The publisher and support contact are the developer identity and contact details displayed on the App’s current Google Play listing. Those listing details must be kept accurate before public release.

2. Core financial records. The App is designed so that the user’s people, debts, bills, subscriptions, rents, installments, expenses, income, payment history, notes, categories and related financial tracking records are stored locally on the user’s device unless the user deliberately exports, saves or shares them. The publisher does not need the contents of those records to provide ordinary local tracking functionality.

3. Exports and sharing. CSV backups and PDF reports are created at the user’s request. When the user chooses a destination or sharing application, the selected file is transferred to that destination under the receiving service’s own privacy terms. The user is responsible for protecting exported files because they may contain sensitive financial information.

4. Free-mode connectivity and advertising. The free version requires an internet connection. The App may perform small reachability requests to determine whether real internet access is available. These requests do not intentionally include the user’s financial ledger. As with ordinary internet communication, the endpoint and network providers can receive technical information such as IP address, time and basic request metadata. Free users may receive advertising through Google Mobile Ads. Where legally required, the App uses Google’s User Messaging Platform or another required consent mechanism before requesting personalized or otherwise regulated advertising and provides a privacy-options entry point when required.

5. Premium purchase information. Lifetime Premium is sold through Google Play as a one-time in-app product. The App receives Google Play purchase information and a purchase token needed to verify ownership and restore entitlement. For production verification, the purchase token is sent to the publisher’s monetization backend, which validates the purchase with Google Play. The backend stores a cryptographic hash or other minimized record needed for entitlement, fraud prevention, refund/revocation handling and support; it should not store raw payment-card information. Payment credentials are processed by Google Play, not by the App.

6. Promotions and device-abuse prevention. To enforce the rule that a promotion code may be used only once per eligible device, the App derives a pseudonymous device identifier from Android’s app-scoped device identifier and hashes it before transmission. A production promotion request is also intended to be protected by Google Play Integrity so the backend can reject unrecognized or materially tampered installations. The backend stores keyed cryptographic representations of the device and promotion identifiers, redemption time and temporary-Premium expiry. These records are retained for as long as needed to enforce the relevant promotion, prevent repeated redemption, resolve disputes and meet applicable legal obligations. If a promotion is permanently retired and the uniqueness record is no longer needed, it should be deleted or irreversibly anonymized within a reasonable operational period.

7. Purposes and legal bases. Information is processed only for purposes such as providing requested app functionality, verifying purchases, restoring entitlements, enforcing promotion limits, preventing fraud and abuse, maintaining security, complying with law, handling support, and serving advertising to free users. Where consent is legally required for advertising or similar processing, consent is requested before that processing. Other processing may rely on performance of a contract, legitimate interests such as security and fraud prevention, or another lawful basis available under applicable law.

8. Service providers and international processing. Google Play, Google Mobile Ads, Google Play Integrity, Cloudflare infrastructure and other processors necessary for the described functions may process technical data in countries other than the user’s own. Their processing is also governed by their own terms and privacy notices. The publisher should use appropriate contractual, organizational and technical safeguards where cross-border-transfer law requires them.

9. Retention. Local financial records remain on the device until the user deletes them, clears the App’s storage, uninstalls the App without preserving a backup, or otherwise removes them. Purchase-verification records are retained only as long as reasonably needed for entitlement, refund/revocation, fraud prevention, support, accounting or legal obligations. Advertising and consent records follow the applicable provider settings and legal retention requirements. No retention period should be longer than necessary for its stated purpose.

10. Security. The App uses measures intended to reduce unauthorized access, including local-storage validation, HTTPS for backend requests, cryptographic hashing of identifiers, server-side purchase verification and production integrity checks. No device, transmission or storage system can be guaranteed absolutely secure. Users should protect their device, Google account and exported files with appropriate security controls.

11. Choices and rights. Depending on location, users may have rights to access, correct, delete, restrict, object to, or obtain a copy of personal data processed by the publisher, and may have the right to withdraw consent without affecting earlier lawful processing. Advertising privacy choices are available in the App when required. Requests concerning publisher-controlled backend data can be submitted using the developer contact shown on Google Play. Requests concerning Google-controlled payment or advertising data may also need to be directed to Google.

12. Children. The App is a personal financial-tracking utility and is not designed or marketed as a child-directed service. Users who are not legally able to enter the relevant agreements in their jurisdiction should use the App only with any consent or supervision required by local law.

13. Changes. This Policy may be updated when functionality, providers or law changes. Material changes should be presented in the App or through another reasonable notice method before or when they take effect where required.

14. Language. Localized versions are provided for accessibility. The English version is the controlling reference for interpretation to the maximum extent permitted by law. This language clause does not waive or reduce any mandatory right that local law gives the user.
''';

  static const String _termsEnglish = '''
TERMS OF USE — LEFFERION PRIME - MIZAN
Effective date: 16 August 2026

1. Agreement and eligibility. By using the App, the user agrees to these Terms and the Privacy Policy. If local law requires parental, guardian or other authorization, the user must obtain it before use. Mandatory legal rights that cannot lawfully be excluded remain unaffected.

2. Purpose of the App. MIZAN is a personal record-keeping and reminder tool for debts, bills, subscriptions, rents, installments, expenses, income, payments and related records. Calculations, reminders, dates, summaries and reports depend on information entered by the user and on device conditions. The App does not provide banking, investment, tax, accounting, legal, credit, debt-collection or other regulated professional advice. Users remain responsible for verifying amounts, due dates, contractual obligations, taxes, fees and decisions with the relevant institution or qualified professional.

3. Free and Premium access. Free access may require continuous internet connectivity, may display advertising, and does not include PDF report export. Premium access removes App-served advertising, permits offline use and enables PDF report export while the entitlement is valid. Temporary Premium may be granted through eligible rewarded advertising or promotions and expires automatically at the stated time. Lifetime Premium is a separate one-time Google Play entitlement with no recurring subscription charge and no preset expiration date, subject to valid ownership, refund/revocation rules, platform availability and these Terms.

4. Advertising. Free users may encounter full-screen advertising only at intended transition points and rewarded advertising when they deliberately request a reward opportunity. Advertising availability, content and targeting may be supplied by third parties such as Google. The publisher does not guarantee that an ad will always be available. Premium users are not intended to receive App-served ads while Premium is valid.

5. User data and backups. The user is responsible for the accuracy of records entered into the App and for maintaining backups appropriate to the importance of those records. Local data can be lost through device failure, factory reset, operating-system behavior, user deletion, storage corruption or other events. CSV exports should be stored securely. The publisher should not be treated as a bank, archival custodian or guaranteed backup provider.

6. Acceptable use. Users may not intentionally bypass Premium controls, advertising gates, purchase validation, promotion limits, Play Integrity checks or other security controls; forge purchase or promotion responses; automate abusive redemption attempts; interfere with the service or another user; distribute modified builds that misrepresent entitlement; introduce malware; or use the App in violation of applicable law. Security research conducted lawfully and responsibly should be reported through the developer contact rather than used to exploit users or the service.

7. Availability and changes. The publisher may maintain, fix, improve or change the App, supported operating-system versions, infrastructure, advertising providers and non-essential features. Reasonable efforts should be made not to remove a paid core entitlement without a legitimate reason. Internet services, Google Play, advertising inventory and third-party infrastructure can be unavailable outside the publisher’s control.

8. Intellectual property and license. Subject to these Terms, the user receives a limited, personal, non-exclusive, non-transferable license to use the App for lawful purposes. The App’s software, branding, original interface assets and other protected material remain with their respective rights holders. These Terms do not transfer ownership of the App to the user.

9. Disclaimer and liability. To the maximum extent permitted by applicable law, the App is provided without a guarantee that every reminder, calculation, export, network check or third-party service will always be uninterrupted or error-free. The publisher is not responsible for losses caused by relying on unverified financial entries, missed external payment obligations, user-provided incorrect information, third-party outages or insecure handling of exported data. Nothing in these Terms excludes liability or remedies that applicable law does not permit to be excluded, including mandatory consumer rights.

10. Suspension and entitlement enforcement. The publisher may restrict server-backed promotional or purchase-verification functions when reasonably necessary to investigate fraud, abuse, tampering or legal requirements. A refunded, charged-back, cancelled, invalid or fraudulently obtained purchase may cease to confer Premium once the status can be reliably verified. Local financial records should not be deleted merely because Premium ends.

11. Governing rules and disputes. These Terms operate together with mandatory laws applicable to the user and the publisher. No clause is intended to force a consumer to give up a mandatory forum, remedy or protection that cannot legally be waived. Before formal proceedings, users are encouraged to contact the publisher through the Google Play developer contact so technical or purchase issues can be investigated.

12. Language and severability. Localized versions are provided for accessibility. The English version is the controlling reference to the maximum extent permitted by applicable law. If a clause is unenforceable, it should be limited or separated only to the extent necessary while the remaining clauses continue to operate.
''';

  static const String _purchaseEnglish = '''
PURCHASE TERMS — LIFETIME AND TEMPORARY PREMIUM
Effective date: 16 August 2026

1. Lifetime Premium product. Lifetime Premium is intended to be offered through Google Play as the one-time, non-consumable product “premium_lifetime”. It is not a subscription, does not renew automatically, and has no recurring subscription fee. The price and currency shown in the Google Play purchase sheet at checkout are the binding store price for that transaction, including any taxes or regional pricing applied by Google or applicable law. The commercial target may be approximately USD 5.00, but the App must display and rely on the current Google Play price rather than hard-coding a currency amount.

2. What Lifetime Premium unlocks. While valid, Lifetime Premium provides an ad-free App experience, offline App use and PDF report export. “Lifetime” means the entitlement has no preset time-based expiry; it does not promise that a particular device, operating system, third-party store or online infrastructure will exist forever. The publisher must not represent the product as a recurring subscription.

3. Automatic restore and account ownership. The App intentionally does not require a visible restore button. On supported Android installations, the App silently checks Google Play ownership when the store is reachable and listens for purchase updates. A verified prior purchase can restore the entitlement after reinstalling the App or moving to another compatible device when Google Play reports the same valid ownership. The user generally needs to use the Google account that owns the purchase. A locally cached verified entitlement may continue to permit Premium offline so that a previously verified purchaser is not forced online on every launch.

4. Verification and acknowledgement. Purchase tokens may be verified by the publisher’s backend against Google Play before permanent Premium is granted. Valid purchases are acknowledged as required by Google Play. Verification is used to prevent forged entitlements, replay attacks and unauthorized Premium activation. Raw payment-card details are not handled by the App.

5. Refunds, withdrawals and mandatory rights. Refund eligibility is governed by Google Play rules, applicable consumer law and any additional publisher obligations. Rules vary by country, purchase type and time since purchase. Nothing in these Purchase Terms removes a statutory cancellation, conformity, refund or other remedy that cannot legally be waived. If Google Play or another authorized process refunds, cancels, reverses or revokes the purchase, Premium access may be removed when the App or backend can reliably verify that ownership is no longer valid.

6. Temporary Premium from rewarded ads. A free user may be offered the opportunity to complete three eligible rewarded ads in the same reward day. After the third verified reward event, the App grants a 24-hour temporary Premium period. Rewarded-ad inventory is not guaranteed, the reward has no cash value, cannot be transferred, and is not a purchased subscription. Premium users do not need and should not see this reward control while Premium remains valid.

7. Promotion codes. ESMANUR is configured to grant seven days of temporary Premium and LEFFERION is configured to grant three days of temporary Premium, subject to server verification. Each of those codes may be redeemed at most once on an eligible device. The App may use a pseudonymous device identifier and Play Integrity to enforce this limit across uninstall/reinstall cycles. Promotion benefits have no cash value, are not transferable, and may be rejected when the device, installation, request integrity, code or prior-redemption status cannot be verified. Promotional periods may coexist with other temporary entitlement only according to the App’s stated extension rules; they do not convert into a refund entitlement.

8. Price changes and promotions. The publisher may change the price offered to future purchasers or introduce, modify or end promotions, subject to Google Play rules and applicable law. A later price change does not create a recurring charge and does not retroactively change a completed one-time purchase.

9. Purchase support. For delivery, restore or entitlement issues, the user should first verify that Google Play is using the account that owns the purchase and that the device is compatible. Support can be requested using the developer contact shown on the Google Play listing. Refund requests may also need to be submitted through Google Play according to the rules applicable to the user’s transaction and location.

10. Language. Localized explanations are provided for accessibility. The English version is the controlling reference for interpretation to the maximum extent permitted by applicable law, without reducing mandatory local consumer rights.
''';

  static const Map<String, String> _privacyOverview = {
    'tr': 'MİZAN finansal kayıtları normal kullanımda cihazda yerel olarak tutar. Kullanıcı CSV veya PDF dışa aktarırsa dosyanın güvenliği seçilen hedefe bağlıdır. Ücretsiz sürüm gerçek internet erişimini kontrol eder ve Google reklamları gösterebilir; gerekli bölgelerde reklam onayı ve gizlilik seçenekleri sunulur. Premium satın alma doğrulamasında Google Play purchase tokenı, promosyonda ise hashlenmiş cihaz kimliği ve production ortamında Play Integrity kullanılabilir. Ödeme kartı bilgileri uygulama tarafından işlenmez. Backend kayıtları yalnız satın alma hakkı, promosyon tek-kullanım kuralı, dolandırıcılık önleme, destek ve yasal gereklilikler için gerekli süre tutulmalıdır. Kullanıcının bulunduğu yere göre erişim, silme, itiraz, düzeltme ve onayı geri çekme hakları olabilir. İngilizce metin esas referanstır; zorunlu yerel haklar saklıdır.',
    'en': 'Core financial records are designed to stay on the device unless you deliberately export or share them. Free mode checks real connectivity and may use Google advertising subject to required consent controls. Purchase verification may send a Google Play purchase token to the publisher backend; promotions may use a hashed app-scoped device identifier and Play Integrity. Payment-card details are handled by Google Play, not the App. Backend data is minimized and retained only for entitlement, promotion enforcement, security, support and legal needs. Applicable privacy rights remain available. The English master below controls interpretation to the extent permitted by law.',
    'es': 'Los registros financieros principales están diseñados para permanecer en el dispositivo salvo que el usuario los exporte o comparta. El modo gratuito comprueba la conexión real y puede usar publicidad de Google con los controles de consentimiento exigidos. La verificación de compras puede enviar el token de Google Play al backend; las promociones pueden usar un identificador seudónimo del dispositivo y Play Integrity. La aplicación no procesa los datos de la tarjeta. Los datos del backend se minimizan y se conservan solo para derechos de acceso, promociones, seguridad, soporte y obligaciones legales. Se mantienen los derechos de privacidad aplicables y el texto inglés es la referencia principal cuando la ley lo permite.',
    'pt-BR': 'Os registros financeiros principais foram projetados para permanecer no dispositivo, salvo quando o usuário decide exportar ou compartilhar. O modo gratuito verifica conectividade real e pode usar anúncios do Google com os controles de consentimento exigidos. A validação da compra pode enviar o token do Google Play ao backend; promoções podem usar um identificador pseudônimo do dispositivo e Play Integrity. O app não processa dados de cartão. Os dados do backend são minimizados e mantidos apenas para direito Premium, promoções, segurança, suporte e obrigações legais. Direitos de privacidade aplicáveis permanecem preservados; o texto em inglês é a referência principal quando permitido por lei.',
    'pt-PT': 'Os registos financeiros principais foram concebidos para permanecer no dispositivo, salvo quando o utilizador decide exportar ou partilhar. O modo gratuito verifica conectividade real e pode usar anúncios Google com os controlos de consentimento exigidos. A validação da compra pode enviar o token Google Play ao backend; promoções podem usar um identificador pseudónimo do dispositivo e Play Integrity. A aplicação não processa dados de cartão. Os dados do backend são minimizados e conservados apenas para direito Premium, promoções, segurança, apoio e obrigações legais. Mantêm-se os direitos de privacidade aplicáveis; o texto inglês é a referência principal quando a lei o permite.',
    'fr': 'Les données financières principales sont conçues pour rester sur l’appareil sauf export ou partage volontaire. Le mode gratuit vérifie l’accès réel à Internet et peut utiliser la publicité Google avec les mécanismes de consentement requis. La vérification d’achat peut transmettre le jeton Google Play au backend ; les promotions peuvent utiliser un identifiant pseudonyme de l’appareil et Play Integrity. L’application ne traite pas les données de carte bancaire. Les données backend sont minimisées et conservées uniquement pour les droits Premium, les promotions, la sécurité, l’assistance et les obligations légales. Les droits de confidentialité applicables restent intacts ; le texte anglais sert de référence lorsque la loi le permet.',
    'de': 'Die zentralen Finanzdaten sind dafür ausgelegt, auf dem Gerät zu bleiben, sofern sie nicht bewusst exportiert oder geteilt werden. Der kostenlose Modus prüft den tatsächlichen Internetzugang und kann Google-Werbung mit den erforderlichen Einwilligungsoptionen verwenden. Zur Kaufprüfung kann ein Google-Play-Kauftoken an das Backend gesendet werden; Promotions können eine pseudonyme Gerätekennung und Play Integrity nutzen. Kartendaten verarbeitet die App nicht. Backend-Daten werden minimiert und nur für Premium-Berechtigung, Promotions, Sicherheit, Support und gesetzliche Pflichten aufbewahrt. Anwendbare Datenschutzrechte bleiben bestehen; soweit rechtlich zulässig ist der englische Text maßgeblich.',
    'it': 'I dati finanziari principali sono progettati per restare sul dispositivo salvo esportazione o condivisione volontaria. La modalità gratuita verifica l’accesso reale a Internet e può usare pubblicità Google con i controlli di consenso richiesti. La verifica dell’acquisto può inviare il token Google Play al backend; le promozioni possono usare un identificatore pseudonimo del dispositivo e Play Integrity. L’app non tratta i dati della carta. I dati backend sono ridotti al minimo e conservati solo per diritti Premium, promozioni, sicurezza, assistenza e obblighi legali. Restano validi i diritti privacy applicabili; il testo inglese è il riferimento principale nei limiti consentiti dalla legge.',
    'nl': 'De financiële kerngegevens zijn bedoeld om op het apparaat te blijven tenzij de gebruiker ze bewust exporteert of deelt. De gratis modus controleert echte internettoegang en kan Google-advertenties gebruiken met de vereiste toestemmingsopties. Voor aankoopverificatie kan een Google Play-aankooptoken naar de backend worden gestuurd; promoties kunnen een pseudonieme apparaat-ID en Play Integrity gebruiken. De app verwerkt geen betaalkaartgegevens. Backendgegevens worden geminimaliseerd en alleen bewaard voor Premium-rechten, promoties, beveiliging, ondersteuning en wettelijke verplichtingen. Toepasselijke privacyrechten blijven gelden; waar toegestaan is de Engelse tekst leidend.',
    'pl': 'Podstawowe dane finansowe są przeznaczone do przechowywania na urządzeniu, chyba że użytkownik świadomie je wyeksportuje lub udostępni. Tryb bezpłatny sprawdza rzeczywisty dostęp do Internetu i może korzystać z reklam Google z wymaganymi mechanizmami zgody. Weryfikacja zakupu może przesłać token Google Play do backendu; promocje mogą używać pseudonimowego identyfikatora urządzenia i Play Integrity. Aplikacja nie przetwarza danych karty płatniczej. Dane backendu są minimalizowane i przechowywane tylko dla uprawnień Premium, promocji, bezpieczeństwa, wsparcia i obowiązków prawnych. Obowiązujące prawa prywatności pozostają zachowane; w dozwolonym zakresie tekst angielski jest rozstrzygający.',
    'ro': 'Datele financiare principale sunt concepute să rămână pe dispozitiv, dacă utilizatorul nu alege să le exporte sau să le partajeze. Modul gratuit verifică accesul real la internet și poate folosi reclame Google cu mecanismele de consimțământ necesare. Verificarea cumpărării poate transmite tokenul Google Play către backend; promoțiile pot utiliza un identificator pseudonim al dispozitivului și Play Integrity. Aplicația nu procesează datele cardului. Datele backend sunt minimizate și păstrate doar pentru dreptul Premium, promoții, securitate, suport și obligații legale. Drepturile de confidențialitate aplicabile rămân valabile; textul englez este referința principală în măsura permisă de lege.',
    'el': 'Τα βασικά οικονομικά δεδομένα έχουν σχεδιαστεί ώστε να παραμένουν στη συσκευή, εκτός αν ο χρήστης επιλέξει εξαγωγή ή κοινοποίηση. Η δωρεάν λειτουργία ελέγχει πραγματική πρόσβαση στο διαδίκτυο και μπορεί να χρησιμοποιεί διαφημίσεις Google με τους απαιτούμενους μηχανισμούς συγκατάθεσης. Η επαλήθευση αγοράς μπορεί να στείλει το token του Google Play στο backend, ενώ οι προωθητικές ενέργειες μπορούν να χρησιμοποιούν ψευδωνυμοποιημένο αναγνωριστικό συσκευής και Play Integrity. Η εφαρμογή δεν επεξεργάζεται στοιχεία κάρτας. Τα δεδομένα backend ελαχιστοποιούνται και διατηρούνται μόνο για Premium, προσφορές, ασφάλεια, υποστήριξη και νομικές υποχρεώσεις. Τα υποχρεωτικά δικαιώματα απορρήτου διατηρούνται.',
    'ru': 'Основные финансовые записи предназначены для хранения на устройстве, если пользователь сам не экспортирует или не передает их. Бесплатный режим проверяет реальный доступ к интернету и может использовать рекламу Google с необходимыми механизмами согласия. Для проверки покупки токен Google Play может передаваться на backend; промокоды могут защищаться псевдонимным идентификатором устройства и Play Integrity. Приложение не обрабатывает данные банковской карты. Backend хранит минимально необходимые данные только для Premium, промокодов, безопасности, поддержки и юридических обязанностей. Применимые права на конфиденциальность сохраняются; английский текст является основным в допустимой законом мере.',
    'uk': 'Основні фінансові записи призначені для зберігання на пристрої, якщо користувач сам не експортує або не поширює їх. Безкоштовний режим перевіряє реальний доступ до Інтернету та може використовувати рекламу Google з необхідними механізмами згоди. Для перевірки покупки токен Google Play може надсилатися на backend; промокоди можуть захищатися псевдонімним ідентифікатором пристрою та Play Integrity. Застосунок не обробляє дані банківської картки. Backend зберігає мінімально необхідні дані лише для Premium, промоакцій, безпеки, підтримки та юридичних обов’язків. Чинні права на приватність зберігаються; англійський текст є основним у межах, дозволених законом.',
    'ar': 'صُممت السجلات المالية الأساسية لتبقى على الجهاز ما لم يختر المستخدم تصديرها أو مشاركتها. يتحقق الوضع المجاني من وجود اتصال فعلي بالإنترنت وقد يستخدم إعلانات Google مع آليات الموافقة المطلوبة. قد يُرسل رمز شراء Google Play إلى الخادم للتحقق من الاستحقاق، وقد تستخدم العروض معرّف جهاز مستعارًا وPlay Integrity. لا يعالج التطبيق بيانات بطاقة الدفع. تُقلل بيانات الخادم إلى الحد اللازم وتُحتفظ بها فقط للاستحقاق والعروض والأمان والدعم والالتزامات القانونية. تبقى حقوق الخصوصية الإلزامية محفوظة، ويكون النص الإنجليزي مرجعًا بالقدر الذي يسمح به القانون.',
    'fa': 'سوابق مالی اصلی برای ماندن روی دستگاه طراحی شده‌اند، مگر اینکه کاربر عمداً آن‌ها را صادر یا اشتراک‌گذاری کند. نسخه رایگان اتصال واقعی اینترنت را بررسی می‌کند و ممکن است با سازوکارهای رضایت لازم از تبلیغات Google استفاده کند. برای تأیید خرید ممکن است توکن Google Play به سرور ارسال شود و برای کدهای تبلیغاتی از شناسه مستعار دستگاه و Play Integrity استفاده شود. برنامه اطلاعات کارت بانکی را پردازش نمی‌کند. داده‌های سرور به حداقل لازم برای حق Premium، تبلیغات، امنیت، پشتیبانی و الزامات قانونی محدود می‌شود. حقوق اجباری حریم خصوصی محفوظ است و متن انگلیسی در حد مجاز قانونی مرجع اصلی است.',
    'he': 'הרשומות הפיננסיות העיקריות מיועדות להישאר במכשיר אלא אם המשתמש בוחר לייצא או לשתף אותן. המצב החינמי בודק גישה אמיתית לאינטרנט ועשוי להשתמש בפרסום של Google בכפוף למנגנוני ההסכמה הנדרשים. לצורך אימות רכישה ניתן לשלוח לשרת אסימון רכישה של Google Play; מבצעים עשויים להשתמש במזהה מכשיר פסאודונימי וב-Play Integrity. האפליקציה אינה מעבדת פרטי כרטיס תשלום. נתוני השרת מצומצמים ונשמרים רק לצורך זכאות Premium, מבצעים, אבטחה, תמיכה וחובות משפטיות. זכויות פרטיות מחייבות נשמרות, והטקסט באנגלית הוא נקודת הייחוס ככל שהחוק מאפשר.',
    'hi': 'मुख्य वित्तीय रिकॉर्ड डिवाइस पर रहने के लिए बनाए गए हैं, जब तक उपयोगकर्ता उन्हें जानबूझकर निर्यात या साझा न करे। मुफ़्त मोड वास्तविक इंटरनेट उपलब्धता जाँचता है और आवश्यक सहमति नियंत्रणों के साथ Google विज्ञापन उपयोग कर सकता है। खरीद सत्यापन के लिए Google Play purchase token backend को भेजा जा सकता है; प्रोमो में छद्मनामित डिवाइस पहचान और Play Integrity का उपयोग हो सकता है। ऐप कार्ड भुगतान विवरण संसाधित नहीं करता। Backend डेटा केवल Premium अधिकार, प्रोमो, सुरक्षा, सहायता और कानूनी आवश्यकताओं तक सीमित रखा जाता है। लागू गोपनीयता अधिकार बने रहते हैं और कानून की अनुमति तक अंग्रेज़ी पाठ मुख्य संदर्भ है।',
    'bn': 'মূল আর্থিক রেকর্ড ডিভাইসেই থাকার জন্য তৈরি, যদি না ব্যবহারকারী ইচ্ছাকৃতভাবে সেগুলো রপ্তানি বা শেয়ার করেন। বিনামূল্যের মোড প্রকৃত ইন্টারনেট সংযোগ পরীক্ষা করে এবং প্রয়োজনীয় সম্মতি নিয়ন্ত্রণসহ Google বিজ্ঞাপন ব্যবহার করতে পারে। কেনাকাটা যাচাইয়ের জন্য Google Play purchase token backend-এ পাঠানো হতে পারে; প্রোমোতে ছদ্মনামযুক্ত ডিভাইস পরিচয় ও Play Integrity ব্যবহার হতে পারে। অ্যাপ পেমেন্ট কার্ডের তথ্য প্রক্রিয়া করে না। Backend ডেটা Premium অধিকার, প্রোমো, নিরাপত্তা, সহায়তা ও আইনি প্রয়োজনের জন্য ন্যূনতম রাখা হয়। প্রযোজ্য গোপনীয়তা অধিকার অক্ষুণ্ণ থাকে এবং আইন অনুমোদন করলে ইংরেজি পাঠ প্রধান রেফারেন্স।',
    'ur': 'بنیادی مالی ریکارڈ ڈیوائس پر رہنے کے لیے بنائے گئے ہیں جب تک صارف خود انہیں برآمد یا شیئر نہ کرے۔ مفت موڈ حقیقی انٹرنیٹ رسائی چیک کرتا ہے اور ضروری رضامندی کے نظام کے ساتھ Google اشتہارات استعمال کر سکتا ہے۔ خرید کی تصدیق کے لیے Google Play purchase token backend کو بھیجا جا سکتا ہے؛ پرومو میں فرضی شناختی ڈیوائس آئی ڈی اور Play Integrity استعمال ہو سکتا ہے۔ ایپ کارڈ کی ادائیگی کی تفصیلات پراسیس نہیں کرتی۔ Backend ڈیٹا Premium حق، پرومو، سکیورٹی، سپورٹ اور قانونی ضرورت تک محدود رکھا جاتا ہے۔ قابل اطلاق رازداری حقوق برقرار رہتے ہیں اور قانون کی اجازت تک انگریزی متن بنیادی حوالہ ہے۔',
    'id': 'Catatan keuangan utama dirancang tetap berada di perangkat kecuali pengguna sengaja mengekspor atau membagikannya. Mode gratis memeriksa akses internet yang nyata dan dapat menggunakan iklan Google dengan mekanisme persetujuan yang diwajibkan. Verifikasi pembelian dapat mengirim token Google Play ke backend; promosi dapat memakai identitas perangkat pseudonim dan Play Integrity. Aplikasi tidak memproses data kartu pembayaran. Data backend diminimalkan dan disimpan hanya untuk hak Premium, promosi, keamanan, dukungan, dan kewajiban hukum. Hak privasi yang berlaku tetap dilindungi; teks bahasa Inggris menjadi rujukan utama sejauh diizinkan hukum.',
    'ms': 'Rekod kewangan utama direka untuk kekal pada peranti kecuali pengguna sengaja mengeksport atau berkongsinya. Mod percuma menyemak akses internet sebenar dan boleh menggunakan iklan Google dengan mekanisme persetujuan yang diwajibkan. Pengesahan pembelian boleh menghantar token Google Play ke backend; promosi boleh menggunakan identiti peranti samaran dan Play Integrity. Aplikasi tidak memproses maklumat kad pembayaran. Data backend diminimumkan dan disimpan hanya untuk hak Premium, promosi, keselamatan, sokongan dan kewajipan undang-undang. Hak privasi yang terpakai kekal terpelihara; teks Inggeris menjadi rujukan utama setakat dibenarkan undang-undang.',
    'fil': 'Ang pangunahing financial records ay idinisenyong manatili sa device maliban kung sadyang i-export o ibahagi ng user. Sinusuri ng free mode ang totoong internet access at maaaring gumamit ng Google ads kasama ang kinakailangang consent controls. Maaaring ipadala ang Google Play purchase token sa backend para sa verification; maaaring gumamit ang promos ng pseudonymous device identity at Play Integrity. Hindi pinoproseso ng app ang payment-card details. Minamaliit ang backend data at itinatago lamang para sa Premium entitlement, promos, security, support at legal obligations. Nananatili ang naaangkop na privacy rights at ang English text ang pangunahing reference kung pinahihintulutan ng batas.',
    'ko': '핵심 금융 기록은 사용자가 직접 내보내거나 공유하지 않는 한 기기에 남도록 설계되었습니다. 무료 모드는 실제 인터넷 연결을 확인하며, 필요한 동의 절차에 따라 Google 광고를 사용할 수 있습니다. 구매 확인을 위해 Google Play 구매 토큰이 backend로 전송될 수 있고, 프로모션에는 가명 처리된 기기 식별자와 Play Integrity가 사용될 수 있습니다. 앱은 결제 카드 정보를 처리하지 않습니다. Backend 데이터는 Premium 권한, 프로모션, 보안, 지원 및 법적 의무에 필요한 범위로 최소화됩니다. 적용되는 개인정보 권리는 유지되며 법이 허용하는 범위에서 영어 문서가 기준입니다.',
    'ja': '主要な金融記録は、ユーザーが明示的にエクスポートまたは共有しない限り、端末内に保持される設計です。無料モードでは実際のインターネット接続を確認し、必要な同意手続に従って Google 広告を利用する場合があります。購入確認のため Google Play の購入トークンを backend に送信することがあり、プロモーションでは仮名化された端末識別子と Play Integrity を利用することがあります。アプリは決済カード情報を処理しません。Backend データは Premium 権利、プロモーション、不正防止、サポート、法的義務に必要な範囲へ最小化されます。適用されるプライバシー権は維持され、法律が許す範囲で英語本文が基準です。',
    'zh': '核心财务记录设计为保存在设备本地，除非用户主动导出或分享。免费模式会检查真实网络连接，并在法律要求的同意机制下使用 Google 广告。购买验证可能把 Google Play 购买令牌发送到 backend；促销可能使用经过假名化的设备标识和 Play Integrity。应用不会处理支付卡信息。Backend 数据会最小化，仅用于 Premium 权限、促销限制、安全、支持和法律义务。适用的隐私权继续有效；在法律允许的范围内，以英文正文作为解释基准。',
    'vi': 'Dữ liệu tài chính cốt lõi được thiết kế để ở lại trên thiết bị trừ khi người dùng chủ động xuất hoặc chia sẻ. Chế độ miễn phí kiểm tra kết nối Internet thực và có thể dùng quảng cáo Google với cơ chế đồng ý bắt buộc. Xác minh mua hàng có thể gửi token Google Play tới backend; khuyến mãi có thể dùng định danh thiết bị giả danh và Play Integrity. Ứng dụng không xử lý dữ liệu thẻ thanh toán. Dữ liệu backend được giảm thiểu và chỉ giữ cho quyền Premium, khuyến mãi, bảo mật, hỗ trợ và nghĩa vụ pháp lý. Các quyền riêng tư áp dụng vẫn được bảo lưu; văn bản tiếng Anh là tham chiếu chính trong phạm vi pháp luật cho phép.',
    'th': 'ข้อมูลการเงินหลักถูกออกแบบให้เก็บอยู่บนอุปกรณ์ เว้นแต่ผู้ใช้จะเลือกส่งออกหรือแชร์เอง โหมดฟรีตรวจสอบการเชื่อมต่ออินเทอร์เน็ตจริงและอาจใช้โฆษณา Google พร้อมกลไกความยินยอมตามที่กฎหมายกำหนด การตรวจสอบการซื้ออาจส่งโทเคน Google Play ไปยัง backend ส่วนโปรโมชันอาจใช้รหัสอุปกรณ์แบบนามแฝงและ Play Integrity แอปไม่ประมวลผลข้อมูลบัตรชำระเงิน ข้อมูล backend จะถูกลดให้เหลือเท่าที่จำเป็นสำหรับสิทธิ Premium โปรโมชัน ความปลอดภัย การสนับสนุน และหน้าที่ตามกฎหมาย สิทธิความเป็นส่วนตัวที่ใช้บังคับยังคงได้รับการคุ้มครอง และใช้ข้อความภาษาอังกฤษเป็นหลักเท่าที่กฎหมายอนุญาต',
    'sw': 'Rekodi kuu za kifedha zimeundwa kubaki kwenye kifaa isipokuwa mtumiaji aamue kuzihamisha au kuzishiriki. Hali ya bure hukagua upatikanaji halisi wa intaneti na inaweza kutumia matangazo ya Google kwa taratibu za idhini zinazohitajika. Uthibitishaji wa ununuzi unaweza kutuma tokeni ya Google Play kwenye backend; ofa zinaweza kutumia kitambulisho bandia cha kifaa na Play Integrity. Programu haichakati taarifa za kadi ya malipo. Data ya backend inapunguzwa na kuhifadhiwa tu kwa haki ya Premium, ofa, usalama, msaada na wajibu wa kisheria. Haki za faragha zinazotumika zinaendelea kulindwa; maandishi ya Kiingereza ndiyo rejea kuu kadiri sheria inavyoruhusu.',
  };

  static const Map<String, String> _termsOverview = {
    'tr': 'MİZAN kişisel finansal kayıt ve hatırlatma aracıdır; banka, yatırım, vergi, hukuk veya profesyonel mali danışmanlık hizmeti değildir. Kullanıcı tutarları, vadeleri ve dış yükümlülükleri kendisi doğrular. Ücretsiz sürüm internet ve reklam gerektirir, PDF vermez; geçerli Premium reklamsız, çevrimdışı ve PDF özelliklidir. Güvenlik, reklam veya satın alma kontrollerini aşmak; sahte entitlement/promosyon üretmek veya değiştirilmiş sürümle hak taklidi yapmak yasaktır. Cihaz arızası veya silinmeye karşı yedek sorumluluğu kullanıcıdadır. Zorunlu tüketici hakları ve kanunen kaldırılamayan sorumluluklar korunur. İngilizce metin esas referanstır.',
    'en': 'MIZAN is a personal financial record and reminder utility, not banking, tax, investment, legal or regulated financial advice. Users must verify amounts, due dates and external obligations themselves. Free use requires connectivity, may include ads and excludes PDF export; valid Premium removes App-served ads, permits offline use and enables PDFs. Attempts to bypass purchase, advertising, promotion or integrity controls, forge entitlement, or distribute deceptive modified builds are prohibited. Users remain responsible for backups. Mandatory consumer protections and non-excludable liabilities remain intact. The English master below is the controlling reference where legally permitted.',
  };

  static const Map<String, String> _purchaseOverview = {
    'tr': 'Ömür boyu Premium Google Play üzerinden tek seferlik non-consumable ürün olarak satılır; abonelik değildir ve otomatik yenilemez. Ödeme anındaki geçerli fiyat Google Play ekranında gösterilen fiyat ve para birimidir; hedef yaklaşık 5 USD olsa da uygulama fiyatı sabit metin olarak yazmaz. Satın alma aynı Google hesabında Google Play sahipliği doğrulandığında otomatik geri yüklenir; görünür restore düğmesi yoktur. Doğrulanmış hak çevrimdışı kullanım için cihazda önbelleğe alınabilir. İade, chargeback veya iptal Google tarafından doğrulanırsa Premium hakkı kaldırılabilir. Üç ödüllü reklam 24 saat geçici Premium sağlar. ESMANUR 7 gün, LEFFERION 3 gün verir ve her kod uygun cihazda en fazla bir kez sunucu doğrulamasıyla kullanılabilir. Zorunlu yerel iade ve tüketici hakları saklıdır.',
    'en': 'Lifetime Premium is a one-time, non-consumable Google Play product, not a subscription and not auto-renewing. The binding checkout price is the price and currency shown by Google Play; the commercial target may be about USD 5 but the App does not hard-code that price. Ownership is restored silently when Google Play confirms the same valid account entitlement, so no visible restore button is required; a verified entitlement may be cached for offline use. A verified refund, chargeback, cancellation or revocation can remove Premium. Three completed rewarded ads grant 24 hours of temporary Premium. ESMANUR grants seven days and LEFFERION three days, each at most once per eligible device after server verification. Mandatory local refund and consumer rights remain unaffected.',
  };

  static String _fallbackOverview(Map<String, String> map, String languageTag) {
    return map[languageTag] ?? map['en']!;
  }

  static LegalDocument document(LegalDocumentType type, String languageTag) {
    switch (type) {
      case LegalDocumentType.privacy:
        return LegalDocument(
          type: type,
          title: 'Privacy Policy',
          localizedOverview: _fallbackOverview(_privacyOverview, languageTag),
          englishMaster: _privacyEnglish,
        );
      case LegalDocumentType.terms:
        return LegalDocument(
          type: type,
          title: 'Terms of Use',
          localizedOverview: _fallbackOverview(_termsOverview, languageTag),
          englishMaster: _termsEnglish,
        );
      case LegalDocumentType.purchase:
        return LegalDocument(
          type: type,
          title: 'Purchase Terms',
          localizedOverview: _fallbackOverview(_purchaseOverview, languageTag),
          englishMaster: _purchaseEnglish,
        );
    }
  }
}
