abstract final class ServerlessLegalOverview {
  static const Map<String, String> _values = {
    'tr':
        'MIZAN finansal kayıtlarınızı cihazınızda yerel tutar; yayıncıya ait hesap, bulut veritabanı veya finansal kayıt sunucusu kullanmaz. Ömür boyu PRO satın alma ve otomatik geri yükleme Google Play satın alma sahipliği üzerinden çalışır. Promosyon kodları uygulamanın içinde kriptografik olarak eşleştirilir ve kullanım durumu cihazda saklanır. Ödüllü reklam ilerlemesi de yereldir; aynı ödül gününde 5 başarılı reklam 24 saat PRO verir. Ücretsiz sürüm internet ve reklam gerektirir, PRO ise reklamsız çevrimdışı kullanım ve PDF dışa aktarma sağlar.',
    'en':
        'MIZAN keeps your financial records locally on your device and does not use a publisher-operated account, cloud database, or financial-record server. Lifetime PRO purchase and silent restore rely on Google Play purchase ownership. Promo codes are matched cryptographically inside the App and redemption state is stored locally. Rewarded-ad progress is also local; 5 successful ads in the applicable reward day grant 24 hours of PRO. Free mode requires internet and ads, while PRO enables ad-free offline use and PDF export.',
    'es':
        'MIZAN guarda tus registros financieros de forma local en el dispositivo y no utiliza una cuenta, base de datos en la nube ni servidor de registros gestionado por el editor. La compra de PRO de por vida y la restauración automática dependen de la propiedad informada por Google Play. Los códigos promocionales se comparan criptográficamente dentro de la aplicación y su uso se guarda localmente. El progreso de anuncios recompensados también es local: 5 anuncios completados en el día de recompensa conceden 24 horas de PRO. El modo gratuito requiere Internet y anuncios; PRO permite uso sin conexión, sin anuncios y exportación PDF.',
    'pt-BR':
        'O MIZAN mantém seus registros financeiros localmente no dispositivo e não usa conta, banco de dados em nuvem ou servidor de registros operado pelo publicador. A compra do PRO vitalício e a restauração automática dependem da titularidade informada pelo Google Play. Os códigos promocionais são comparados criptograficamente dentro do app e o uso é salvo localmente. O progresso dos anúncios recompensados também é local: 5 anúncios concluídos no dia de recompensa liberam 24 horas de PRO. O modo gratuito exige internet e anúncios; o PRO permite uso offline sem anúncios e exportação em PDF.',
    'pt-PT':
        'O MIZAN mantém os registos financeiros localmente no dispositivo e não utiliza conta, base de dados na nuvem ou servidor de registos operado pelo editor. A compra do PRO vitalício e o restauro automático dependem da titularidade indicada pelo Google Play. Os códigos promocionais são comparados criptograficamente dentro da aplicação e a utilização fica guardada localmente. O progresso dos anúncios recompensados também é local: 5 anúncios concluídos no dia de recompensa concedem 24 horas de PRO. O modo gratuito exige Internet e anúncios; o PRO permite utilização offline sem anúncios e exportação PDF.',
    'fr':
        'MIZAN conserve vos données financières localement sur l’appareil et n’utilise ni compte, ni base de données cloud, ni serveur de données financières exploité par l’éditeur. L’achat PRO à vie et la restauration automatique reposent sur la propriété signalée par Google Play. Les codes promotionnels sont comparés cryptographiquement dans l’application et leur utilisation est mémorisée localement. La progression des publicités récompensées est également locale : 5 publicités validées dans la journée de récompense donnent 24 heures de PRO. Le mode gratuit nécessite Internet et des publicités ; PRO permet l’usage hors ligne sans publicité et l’export PDF.',
    'de':
        'MIZAN speichert Ihre Finanzdaten lokal auf dem Gerät und verwendet weder ein vom Anbieter betriebenes Konto noch eine Cloud-Datenbank oder einen Server für Finanzaufzeichnungen. Der Kauf von lebenslangem PRO und die automatische Wiederherstellung richten sich nach dem von Google Play gemeldeten Besitz. Aktionscodes werden innerhalb der App kryptografisch abgeglichen und die Einlösung lokal gespeichert. Auch der Fortschritt bei Rewarded Ads bleibt lokal: 5 erfolgreich abgeschlossene Anzeigen am Belohnungstag gewähren 24 Stunden PRO. Die kostenlose Version benötigt Internet und Werbung; PRO ermöglicht werbefreie Offline-Nutzung und PDF-Export.',
    'it':
        'MIZAN conserva i dati finanziari localmente sul dispositivo e non usa account, database cloud o server di registri finanziari gestiti dall’editore. L’acquisto PRO a vita e il ripristino automatico si basano sulla proprietà comunicata da Google Play. I codici promozionali vengono confrontati crittograficamente nell’app e lo stato di utilizzo è salvato in locale. Anche il progresso degli annunci con premio è locale: 5 annunci completati nel giorno premio concedono 24 ore di PRO. La modalità gratuita richiede Internet e pubblicità; PRO abilita uso offline senza annunci ed esportazione PDF.',
    'nl':
        'MIZAN bewaart uw financiële gegevens lokaal op het apparaat en gebruikt geen door de uitgever beheerd account, cloud-database of server voor financiële gegevens. De aankoop van levenslange PRO en stil herstel zijn gebaseerd op eigendom dat Google Play meldt. Promocodes worden cryptografisch in de app vergeleken en het gebruik wordt lokaal opgeslagen. Ook de voortgang van beloningsadvertenties blijft lokaal: 5 voltooide advertenties op de beloningsdag geven 24 uur PRO. De gratis versie vereist internet en advertenties; PRO biedt advertentievrij offline gebruik en PDF-export.',
    'pl':
        'MIZAN przechowuje dane finansowe lokalnie na urządzeniu i nie korzysta z konta, bazy danych w chmurze ani serwera zapisów finansowych prowadzonego przez wydawcę. Zakup dożywotniego PRO i automatyczne przywracanie opierają się na własności zgłaszanej przez Google Play. Kody promocyjne są porównywane kryptograficznie w aplikacji, a użycie zapisywane lokalnie. Postęp reklam z nagrodą także jest lokalny: 5 ukończonych reklam w dniu nagrody daje 24 godziny PRO. Wersja bezpłatna wymaga Internetu i reklam; PRO umożliwia pracę offline bez reklam i eksport PDF.',
    'ro':
        'MIZAN păstrează înregistrările financiare local pe dispozitiv și nu folosește un cont, o bază de date cloud sau un server de evidență financiară operat de editor. Achiziția PRO pe viață și restaurarea automată se bazează pe dreptul de proprietate raportat de Google Play. Codurile promoționale sunt comparate criptografic în aplicație, iar utilizarea este memorată local. Progresul reclamelor recompensate este tot local: 5 reclame finalizate în ziua de recompensă oferă 24 de ore de PRO. Modul gratuit necesită Internet și reclame; PRO permite folosire offline fără reclame și export PDF.',
    'el':
        'Το MIZAN διατηρεί τα οικονομικά αρχεία τοπικά στη συσκευή και δεν χρησιμοποιεί λογαριασμό, βάση cloud ή διακομιστή οικονομικών αρχείων του εκδότη. Η αγορά ισόβιου PRO και η αυτόματη επαναφορά βασίζονται στην ιδιοκτησία που αναφέρει το Google Play. Οι κωδικοί προσφοράς συγκρίνονται κρυπτογραφικά μέσα στην εφαρμογή και η χρήση αποθηκεύεται τοπικά. Η πρόοδος των rewarded ads είναι επίσης τοπική: 5 ολοκληρωμένες διαφημίσεις στην ημέρα ανταμοιβής δίνουν 24 ώρες PRO. Η δωρεάν έκδοση απαιτεί Internet και διαφημίσεις, ενώ το PRO προσφέρει offline χρήση χωρίς διαφημίσεις και εξαγωγή PDF.',
    'ru':
        'MIZAN хранит финансовые записи локально на устройстве и не использует аккаунт, облачную базу или сервер финансовых данных издателя. Покупка пожизненного PRO и автоматическое восстановление опираются на право владения, которое сообщает Google Play. Промокоды сверяются криптографически внутри приложения, а факт использования сохраняется локально. Прогресс вознаграждаемой рекламы также хранится локально: 5 успешно просмотренных объявлений в день награды дают 24 часа PRO. Бесплатный режим требует Интернет и рекламу; PRO дает работу офлайн без рекламы и экспорт PDF.',
    'uk':
        'MIZAN зберігає фінансові записи локально на пристрої й не використовує обліковий запис, хмарну базу чи сервер фінансових даних видавця. Купівля довічного PRO та автоматичне відновлення спираються на право власності, яке повідомляє Google Play. Промокоди звіряються криптографічно всередині застосунку, а використання зберігається локально. Прогрес винагороджуваної реклами також локальний: 5 завершених оголошень у день винагороди дають 24 години PRO. Безкоштовний режим потребує Інтернет і рекламу; PRO надає офлайн-роботу без реклами та експорт PDF.',
    'ar':
        'يحتفظ MIZAN بالسجلات المالية محليًا على الجهاز ولا يستخدم حسابًا أو قاعدة بيانات سحابية أو خادم سجلات مالية يديره الناشر. يعتمد شراء PRO مدى الحياة والاستعادة التلقائية على ملكية الشراء التي يبلغ عنها Google Play. تتم مطابقة رموز العروض تشفيريًا داخل التطبيق ويُحفظ سجل الاستخدام محليًا. كما يُحفظ تقدم الإعلانات بمكافأة محليًا؛ إكمال ٥ إعلانات ناجحة في يوم المكافأة يمنح 24 ساعة من PRO. يتطلب الوضع المجاني اتصالًا بالإنترنت وإعلانات، بينما يتيح PRO الاستخدام دون اتصال ومن دون إعلانات وتصدير PDF.',
    'fa':
        'MIZAN سوابق مالی را به‌صورت محلی روی دستگاه نگه می‌دارد و از حساب، پایگاه‌داده ابری یا سرور سوابق مالی متعلق به ناشر استفاده نمی‌کند. خرید PRO مادام‌العمر و بازیابی خودکار بر مالکیتی متکی است که Google Play گزارش می‌کند. کدهای تبلیغاتی به‌صورت رمزنگاری‌شده در خود برنامه تطبیق داده می‌شوند و وضعیت استفاده محلی ذخیره می‌شود. پیشرفت تبلیغات پاداشی نیز محلی است؛ تکمیل ۵ تبلیغ موفق در روز پاداش، 24 ساعت PRO می‌دهد. حالت رایگان به اینترنت و تبلیغ نیاز دارد و PRO استفاده آفلاین بدون تبلیغ و خروجی PDF را فعال می‌کند.',
    'he':
        'MIZAN שומר את הרשומות הפיננסיות באופן מקומי במכשיר ואינו משתמש בחשבון, במסד נתונים בענן או בשרת רשומות פיננסיות שמופעל בידי המפרסם. רכישת PRO לכל החיים והשחזור האוטומטי נשענים על הבעלות שמדווח Google Play. קודי מבצע מותאמים קריפטוגרפית בתוך האפליקציה והשימוש נשמר מקומית. גם התקדמות בפרסומות מתוגמלות נשמרת מקומית: השלמת 5 פרסומות ביום התגמול מעניקה 24 שעות PRO. הגרסה החינמית דורשת אינטרנט ופרסומות; PRO מאפשר שימוש לא מקוון ללא פרסומות וייצוא PDF.',
    'hi':
        'MIZAN वित्तीय रिकॉर्ड को डिवाइस पर स्थानीय रूप से रखता है और प्रकाशक द्वारा चलाया गया खाता, क्लाउड डेटाबेस या वित्तीय रिकॉर्ड सर्वर इस्तेमाल नहीं करता। लाइफटाइम PRO खरीद और स्वतः बहाली Google Play द्वारा बताई गई खरीद-स्वामित्व जानकारी पर निर्भर करती है। प्रोमो कोड ऐप के भीतर क्रिप्टोग्राफ़िक रूप से मिलाए जाते हैं और उपयोग की स्थिति स्थानीय रूप से सहेजी जाती है। रिवॉर्ड विज्ञापन की प्रगति भी स्थानीय है; रिवॉर्ड दिन में 5 सफल विज्ञापन 24 घंटे PRO देते हैं। मुफ़्त मोड में इंटरनेट और विज्ञापन आवश्यक हैं, जबकि PRO ऑफ़लाइन, विज्ञापन-मुक्त उपयोग और PDF निर्यात देता है।',
    'bn':
        'MIZAN আর্থিক রেকর্ড ডিভাইসে স্থানীয়ভাবে রাখে এবং প্রকাশকের পরিচালিত অ্যাকাউন্ট, ক্লাউড ডেটাবেস বা আর্থিক রেকর্ড সার্ভার ব্যবহার করে না। আজীবন PRO কেনা ও স্বয়ংক্রিয় পুনরুদ্ধার Google Play যে মালিকানা জানায় তার ওপর নির্ভর করে। প্রোমো কোড অ্যাপের ভেতরে ক্রিপ্টোগ্রাফিকভাবে মেলানো হয় এবং ব্যবহারের অবস্থা স্থানীয়ভাবে রাখা হয়। পুরস্কার বিজ্ঞাপনের অগ্রগতিও স্থানীয়; পুরস্কার দিনে 5টি সফল বিজ্ঞাপন 24 ঘণ্টার PRO দেয়। ফ্রি মোডে ইন্টারনেট ও বিজ্ঞাপন লাগে; PRO অফলাইন, বিজ্ঞাপনমুক্ত ব্যবহার ও PDF এক্সপোর্ট দেয়।',
    'ur':
        'MIZAN مالی ریکارڈ ڈیوائس پر مقامی طور پر رکھتا ہے اور ناشر کا چلایا ہوا اکاؤنٹ، کلاؤڈ ڈیٹابیس یا مالی ریکارڈ سرور استعمال نہیں کرتا۔ لائف ٹائم PRO خرید اور خودکار بحالی Google Play کی بتائی ہوئی خریداری کی ملکیت پر مبنی ہے۔ پرومو کوڈ ایپ کے اندر کرپٹوگرافک طور پر ملائے جاتے ہیں اور استعمال کی حالت مقامی طور پر محفوظ ہوتی ہے۔ انعامی اشتہارات کی پیش رفت بھی مقامی ہے؛ انعامی دن میں 5 کامیاب اشتہارات 24 گھنٹے PRO دیتے ہیں۔ مفت موڈ کے لیے انٹرنیٹ اور اشتہارات لازم ہیں، جبکہ PRO آف لائن، بغیر اشتہار استعمال اور PDF ایکسپورٹ دیتا ہے۔',
    'id':
        'MIZAN menyimpan catatan keuangan secara lokal di perangkat dan tidak menggunakan akun, basis data cloud, atau server catatan keuangan yang dioperasikan penerbit. Pembelian PRO seumur hidup dan pemulihan otomatis bergantung pada kepemilikan yang dilaporkan Google Play. Kode promo dicocokkan secara kriptografis di dalam aplikasi dan status penggunaan disimpan lokal. Progres iklan berhadiah juga lokal; 5 iklan berhasil pada hari hadiah memberikan 24 jam PRO. Mode gratis memerlukan internet dan iklan, sedangkan PRO menyediakan penggunaan offline tanpa iklan dan ekspor PDF.',
    'ms':
        'MIZAN menyimpan rekod kewangan secara setempat pada peranti dan tidak menggunakan akaun, pangkalan data awan atau pelayan rekod kewangan yang dikendalikan penerbit. Pembelian PRO seumur hidup dan pemulihan automatik bergantung pada pemilikan yang dilaporkan Google Play. Kod promosi dipadankan secara kriptografi dalam aplikasi dan status penggunaan disimpan secara setempat. Kemajuan iklan ganjaran juga setempat; 5 iklan berjaya pada hari ganjaran memberikan 24 jam PRO. Mod percuma memerlukan Internet dan iklan, manakala PRO membolehkan penggunaan luar talian tanpa iklan dan eksport PDF.',
    'fil':
        'Pinananatili ng MIZAN ang financial records nang lokal sa device at hindi gumagamit ng publisher-operated account, cloud database, o financial-record server. Ang lifetime PRO purchase at automatic restore ay nakabatay sa ownership na iniulat ng Google Play. Ang promo codes ay cryptographically matched sa loob ng app at lokal na sine-save ang redemption state. Lokal din ang rewarded-ad progress; 5 matagumpay na ads sa reward day ang nagbibigay ng 24 oras na PRO. Kailangan ng internet at ads ang free mode, habang nagbibigay ang PRO ng ad-free offline use at PDF export.',
    'vi':
        'MIZAN lưu dữ liệu tài chính cục bộ trên thiết bị và không dùng tài khoản, cơ sở dữ liệu đám mây hay máy chủ dữ liệu tài chính do nhà phát hành vận hành. Việc mua PRO trọn đời và khôi phục tự động dựa trên quyền sở hữu do Google Play báo cáo. Mã khuyến mãi được đối chiếu bằng mật mã ngay trong ứng dụng và trạng thái sử dụng được lưu cục bộ. Tiến độ quảng cáo có thưởng cũng lưu cục bộ; 5 quảng cáo hoàn tất trong ngày thưởng cấp 24 giờ PRO. Chế độ miễn phí cần Internet và quảng cáo; PRO cho phép dùng ngoại tuyến không quảng cáo và xuất PDF.',
    'th':
        'MIZAN เก็บข้อมูลการเงินไว้ในอุปกรณ์แบบภายในและไม่ใช้บัญชี ฐานข้อมูลคลาวด์ หรือเซิร์ฟเวอร์ข้อมูลการเงินที่ผู้เผยแพร่เป็นผู้ดำเนินการ การซื้อ PRO ตลอดชีพและการกู้คืนอัตโนมัติอาศัยสิทธิ์ความเป็นเจ้าของที่ Google Play รายงาน รหัสโปรโมชันถูกจับคู่ด้วยการเข้ารหัสภายในแอปและบันทึกสถานะการใช้ไว้ในเครื่อง ความคืบหน้าโฆษณาแบบมีรางวัลก็เก็บในเครื่องเช่นกัน; โฆษณาสำเร็จ 5 รายการในวันรางวัลให้ PRO 24 ชั่วโมง โหมดฟรีต้องใช้อินเทอร์เน็ตและโฆษณา ส่วน PRO ใช้งานออฟไลน์แบบไม่มีโฆษณาและส่งออก PDF ได้',
    'sw':
        'MIZAN huhifadhi rekodi za fedha ndani ya kifaa na haitumii akaunti, hifadhidata ya wingu au seva ya rekodi za fedha inayoendeshwa na mchapishaji. Ununuzi wa PRO wa kudumu na urejeshaji wa kiotomatiki hutegemea umiliki unaoripotiwa na Google Play. Misimbo ya promosheni hulinganishwa kwa kriptografia ndani ya programu na hali ya matumizi huhifadhiwa kwenye kifaa. Maendeleo ya matangazo yenye zawadi pia ni ya ndani; matangazo 5 yaliyokamilika katika siku ya zawadi hutoa saa 24 za PRO. Hali ya bure inahitaji Intaneti na matangazo; PRO huruhusu matumizi bila mtandao, bila matangazo na uhamishaji wa PDF.',
    'zh':
        'MIZAN 将财务记录保存在设备本地，不使用由发布者运营的账户、云数据库或财务记录服务器。终身 PRO 购买和自动恢复依赖 Google Play 报告的购买所有权。促销码在应用内通过加密指纹进行匹配，使用状态保存在本地。激励广告进度同样保存在本地；在奖励日完成 5 个有效广告可获得 24 小时 PRO。免费模式需要联网并显示广告；PRO 支持无广告离线使用和 PDF 导出。',
    'ja':
        'MIZAN は金融記録を端末内にローカル保存し、発行者が運営するアカウント、クラウドデータベース、金融記録サーバーを使用しません。Lifetime PRO の購入と自動復元は Google Play が報告する購入所有権に基づきます。プロモコードはアプリ内で暗号学的に照合され、使用状態は端末内に保存されます。リワード広告の進捗もローカル保存され、報酬日の有効な広告を 5 回完了すると 24 時間の PRO が付与されます。無料モードはインターネットと広告が必要で、PRO は広告なしのオフライン利用と PDF 出力を提供します。',
    'ko':
        'MIZAN은 금융 기록을 기기에 로컬로 저장하며 게시자가 운영하는 계정, 클라우드 데이터베이스 또는 금융 기록 서버를 사용하지 않습니다. 평생 PRO 구매와 자동 복원은 Google Play가 보고하는 구매 소유권을 기준으로 합니다. 프로모션 코드는 앱 내부에서 암호학적으로 대조되고 사용 상태는 로컬에 저장됩니다. 보상형 광고 진행도 역시 로컬에 저장되며 보상일에 유효한 광고 5개를 완료하면 24시간 PRO가 제공됩니다. 무료 모드는 인터넷과 광고가 필요하고 PRO는 광고 없는 오프라인 사용과 PDF 내보내기를 제공합니다.',
  };

  static String text(String languageTag) => _values[languageTag] ?? _values['en']!;

  static Set<String> get supportedTags => _values.keys.toSet();
}
