// FILIPINO LOCALIZATION — CORE SLICE. Not registered in runtime until 791/791 is complete.
const Map<String,String> mizanFilipinoCore=<String,String>{
  'MİZAN Aylık Raporu':'Buwanang Ulat ng MİZAN','Aktif':'Aktibo','Yaklaşıyor':'Malapit nang takdang petsa','Gecikmede':'Lampas sa takdang petsa','Tamamlandı':'Tapos','Pasif':'Hindi aktibo',
  'KMH hesabı':'Overdraft account','Kredi kartı':'Credit card','Kredi':'Pautang','Araç kredisi':'Pautang sa sasakyan','Ev kredisi':'Pautang sa bahay','Nakit avans':'Cash advance','Taksitli nakit avans':'Cash advance na hulugan','Özel borç türü':'Pasadyang uri ng utang',
  'Son ödeme tarihi':'Takdang petsa ng bayad','Her ayın belirli günü':'Takdang araw bawat buwan','Taksit ödemesi':'Bayad sa hulugan','Borç kapama':'Buong bayad sa utang','Kısmi ödeme':'Bahagyang bayad','Günde 1 kez':'Isang beses bawat araw','Günde 2 kez':'Dalawang beses bawat araw','Günde 3 kez':'Tatlong beses bawat araw',
  'Cihazın varsayılan bildirim sesi':'Default na tunog ng notification ng device','Sessiz':'Tahimik','Tek seferlik':'Isang beses','Günlük':'Araw-araw','Haftalık':'Lingguhan','Aylık':'Buwanan',
  'Elektrik':'Kuryente','Su':'Tubig','Telefon':'Telepono','İnternet':'Internet','Doğalgaz':'Natural gas','Özel fatura':'Pasadyang bayarin','Tek dönem faturası':'Bayarin para sa isang panahon','Her ay tekrarlayan fatura':'Buwanang paulit-ulit na bayarin','Ev kirası':'Upa sa bahay','Ürün taksiti':'Hulugan sa produkto','Özel oluştur':'Gumawa ng pasadya',
  'Kişi':'Tao','Şirket / Kurum':'Kumpanya / Institusyon','Çek':'Tseke','Senet':'Kasulatan ng pagkakautang','Esnaf / İşletme':'Negosyante / Negosyo','Aile / Yakın':'Pamilya / Malapit na kamag-anak','Diğer':'Iba pa','Tek ödeme':'Isang bayad','İki haftada bir':'Bawat dalawang linggo','Üç aylık':'Kada tatlong buwan','Yıllık':'Taunan','Özel aralık':'Pasadyang pagitan',
  'Dijital hizmet':'Digital na serbisyo','Üyelik':'Membership','Sigorta':'Insurance','Eğitim':'Edukasyon','Bakım / servis':'Maintenance / Serbisyo','Diğer abonelik':'Ibang subscription','Banka borcu':'Utang sa bangko','Kişisel / kurumsal borç':'Personal / pangkumpanyang utang','Fatura':'Bayarin','Abonelik':'Subscription','Kira / taksit':'Upa / Hulugan',
  'Ana sayfa':'Home','Kayıtlar':'Mga tala','Giderler':'Mga gastusin','Raporlar':'Mga ulat','Ayarlar':'Mga setting','Kapat':'Isara','Kaydet':'I-save','Vazgeç':'Kanselahin','Sil':'Burahin','Düzenle':'I-edit','Ekle':'Idagdag','Devam et':'Magpatuloy','Geri':'Bumalik','Tamam':'OK','Onayla':'Kumpirmahin','Aramayı temizle':'I-clear ang paghahanap','Eşleşen sonuç bulunamadı.':'Walang nakitang tugmang resulta.',
  'Dil seç':'Pumili ng wika','Dil ara':'Maghanap ng wika','Ülke seç':'Pumili ng bansa','Ülke adı veya kod ara':'Maghanap ayon sa pangalan o code ng bansa','Para birimi seç':'Pumili ng currency','Ad, ISO kodu veya sembol ara':'Maghanap ayon sa pangalan, ISO code o simbolo','Uygulama dili':'Wika ng app','Ülke / borç bölgesi':'Bansa / Rehiyon ng utang','Varsayılan para birimi':'Default na currency','Kurulumu tamamla':'Tapusin ang setup','MİZAN GLOBAL':'MİZAN GLOBAL',
  'Bu seçimler yalnız ilk kurulumda sorulur. Daha sonra Ayarlar bölümünden değiştirilebilir; mevcut kayıtlar silinmez.':'Itatanong lamang ang mga pagpiling ito sa unang setup. Maaari itong baguhin sa Mga Setting sa ibang pagkakataon nang hindi binubura ang kasalukuyang mga tala.','Yalnızca tamamen entegre edilmiş bir dil seçilebilir.':'Tanging ganap na naka-integrate na wika ang maaaring piliin.','Dil, ülke ve para birimi':'Wika, bansa at currency','Bu seçimleri değiştirmek kayıtları, ödemeleri veya geçmişi silmez.':'Hindi buburahin ng pagbabago sa mga pagpiling ito ang mga tala, bayad o history.','Profil kayıtları korunur':'Pinananatili ang mga tala ng profile','Dil, ülke veya varsayılan para birimi değiştiğinde mevcut kişi, borç, fatura, gider, gelir ve ödeme kayıtları değiştirilmez.':'Kapag binago ang wika, bansa o default na currency, hindi babaguhin ang kasalukuyang mga tao, utang, bayarin, gastusin, kita at mga tala ng bayad.',
  'Bildirim sistemi':'Sistema ng notification','Bildirim izni':'Pahintulot sa notification','Dakik bildirim izni':'Pahintulot sa eksaktong alarm','Açık':'Naka-on','Kapalı':'Naka-off','Dakik teslim için izin gerekli':'Kailangan ang pahintulot para sa eksaktong oras','Bildirim planı bilgisi':'Impormasyon sa iskedyul ng notification','Otomatik senkronizasyon':'Awtomatikong sync','Ödeme hatırlatmaları':'Mga paalala sa pagbabayad','Saat ekle':'Magdagdag ng oras','Ses ve titreşim':'Tunog at vibration','Titreşim açık':'Naka-on ang vibration','Titreşim kapalı':'Naka-off ang vibration','Vade kayıtları değiştirilmez':'Hindi binabago ang mga tala ng takdang petsa','Günlük gider hatırlatmaları':'Araw-araw na paalala sa gastusin','Yerel veri güvenliği':'Seguridad ng lokal na data','Anlık yerel kayıt':'Agarang lokal na pag-save','Doğrulanmış yedek kopya':'Na-verify na backup','CSV yedekleme':'CSV backup','CSV yedeğini dışa aktar':'I-export ang CSV backup','CSV yedeğini mevcut verilerle birleştir':'Pagsamahin ang CSV backup sa kasalukuyang data','İlişkiler korunur':'Pinananatili ang mga ugnayan',
};
