from __future__ import annotations

# Binding, neutral-standard Bengali product terminology for Bangladesh and India.
# These values are acceptance anchors, not a substitute for sentence-level native review.
BENGALI_REQUIRED_CHARACTERS = ('অ', 'ক', 'ত', 'ন', 'ম', 'র')
BENGALI_FORBIDDEN_INVISIBLE = tuple(chr(code) for code in (
    0x200B, 0x200C, 0x200D, 0x200E, 0x200F,
    0x202A, 0x202B, 0x202C, 0x202D, 0x202E,
    0x2066, 0x2067, 0x2068, 0x2069,
))

BENGALI_TERMINOLOGY: dict[str, str] = {
    'Ana sayfa': 'হোম',
    'Kayıtlar': 'রেকর্ড',
    'Giderler': 'খরচ',
    'Raporlar': 'প্রতিবেদন',
    'Ayarlar': 'সেটিংস',
    'Kaydet': 'সংরক্ষণ করুন',
    'Sil': 'মুছুন',
    'Düzenle': 'সম্পাদনা করুন',
    'Devam et': 'চালিয়ে যান',
    'Vazgeç': 'বাতিল করুন',
    'Ekle': 'যোগ করুন',
    'Geri': 'ফিরে যান',
    'İleri': 'পরবর্তী',
    'Kapat': 'বন্ধ করুন',
    'Aç': 'চালু করুন',
    'Ara': 'খুঁজুন',
    'Filtrele': 'ফিল্টার করুন',
    'Sıfırla': 'রিসেট করুন',
    'Onayla': 'নিশ্চিত করুন',
    'İptal': 'বাতিল',
    'Tamam': 'ঠিক আছে',
    'Detaylar': 'বিস্তারিত',
    'Özet': 'সারসংক্ষেপ',
    'Geçmiş': 'ইতিহাস',
    'Takvim': 'ক্যালেন্ডার',
    'Notlar': 'নোট',
    'Kategoriler': 'বিভাগ',
    'Kişiler': 'ব্যক্তি',
    'Tümü': 'সব',
    'Seçili': 'নির্বাচিত',
    'Borç': 'ঋণ',
    'Banka borcu': 'ব্যাংক ঋণ',
    'Kişisel borç': 'ব্যক্তিগত ঋণ',
    'Kurumsal borç': 'ব্যবসায়িক ঋণ',
    'Borç türü': 'ঋণের ধরন',
    'Borç adı': 'ঋণের নাম',
    'Borç ürünü': 'ক্রেডিট পণ্য',
    'Kredi kartı': 'ক্রেডিট কার্ড',
    'Kredi': 'ঋণ',
    'Ev kredisi': 'গৃহঋণ',
    'Araç kredisi': 'গাড়ির ঋণ',
    'KMH hesabı': 'ওভারড্রাফট হিসাব',
    'Nakit avans': 'নগদ অগ্রিম',
    'Taksitli nakit avans': 'কিস্তিতে নগদ অগ্রিম',
    'Çek': 'চেক',
    'Senet': 'প্রতিশ্রুতিপত্র',
    'Ödeme': 'পরিশোধ',
    'Ödeme tutarı': 'পরিশোধের পরিমাণ',
    'Toplam ödeme': 'মোট পরিশোধ',
    'Kalan ödeme': 'বাকি পরিশোধ',
    'Kalan bakiye': 'অবশিষ্ট ব্যালেন্স',
    'Bakiye': 'ব্যালেন্স',
    'Vade': 'পরিশোধের সময়সীমা',
    'Son ödeme tarihi': 'শেষ পরিশোধের তারিখ',
    'Vade tarihi': 'পরিশোধের নির্ধারিত তারিখ',
    'Gecikmiş': 'মেয়াদোত্তীর্ণ',
    'Gecikme': 'বিলম্ব',
    'Gecikme günü': 'বিলম্বের দিন',
    'Gecikme faizi': 'বিলম্ব সুদ',
    'Faiz': 'সুদ',
    'Ana para': 'মূলধন',
    'Kullanılan limit': 'ব্যবহৃত সীমা',
    'Toplam limit': 'মোট সীমা',
    'Kullanılabilir limit': 'উপলভ্য সীমা',
    'Fatura': 'বিল',
    'Elektrik faturası': 'বিদ্যুৎ বিল',
    'Su faturası': 'পানির বিল',
    'Doğalgaz faturası': 'গ্যাস বিল',
    'İnternet faturası': 'ইন্টারনেট বিল',
    'Telefon faturası': 'ফোন বিল',
    'Abonelik': 'সাবস্ক্রিপশন',
    'Kira': 'ভাড়া',
    'Taksit': 'কিস্তি',
    'Kira ve Taksitler': 'ভাড়া ও কিস্তি',
    'Gider': 'খরচ',
    'Gelir': 'আয়',
    'Gider kategorisi': 'খরচের বিভাগ',
    'Gelir kategorisi': 'আয়ের বিভাগ',
    'Tutar': 'পরিমাণ',
    'Para birimi': 'মুদ্রা',
    'Varsayılan para birimi': 'ডিফল্ট মুদ্রা',
    'Döviz kuru': 'বিনিময় হার',
    'İşlem': 'লেনদেন',
    'İşlem tarihi': 'লেনদেনের তারিখ',
    'Ödeme geçmişi': 'পরিশোধের ইতিহাস',
    'Kalan ödeme yükü': 'অবশিষ্ট পরিশোধের দায়',
    'Gecikmiş ödeme yükü': 'মেয়াদোত্তীর্ণ পরিশোধের দায়',
    'Yaklaşan ödeme': 'আসন্ন পরিশোধ',
    'Yaklaşan ödeme yükü': 'আসন্ন পরিশোধের দায়',
    'Ödenen': 'পরিশোধিত',
    'Ödenmedi': 'অপরিশোধিত',
    'Kısmi ödeme': 'আংশিক পরিশোধ',
    'Peşin ödeme': 'অগ্রিম পরিশোধ',
    'Otomatik ödeme': 'স্বয়ংক্রিয় পরিশোধ',
    'Tahsilat': 'আদায়',
    'Alacak': 'পাওনা',
    'Alacaklı': 'পাওনাদার',
    'Borçlu': 'দেনাদার',
    'Müşteri': 'গ্রাহক',
    'Tedarikçi': 'সরবরাহকারী',
    'Banka': 'ব্যাংক',
    'Hesap': 'হিসাব',
    'Hesap numarası': 'হিসাব নম্বর',
    'IBAN': 'IBAN',
    'Kart': 'কার্ড',
    'Kart numarası': 'কার্ড নম্বর',
    'Ekstre': 'বিবরণী',
    'Ekstre tarihi': 'বিবরণীর তারিখ',
    'Kesim tarihi': 'বিবরণী তৈরির তারিখ',
    'Asgari ödeme': 'ন্যূনতম পরিশোধ',
    'Kalan toplam borç': 'মোট অবশিষ্ট ঋণ',
    'Toplam borç': 'মোট ঋণ',
    'Borç bakiyesi': 'ঋণের অবশিষ্ট ব্যালেন্স',
    'Düzenli ödeme': 'নিয়মিত পরিশোধ',
    'Tek seferlik ödeme': 'এককালীন পরিশোধ',
    'Yinelenen ödeme': 'পুনরাবৃত্ত পরিশোধ',
    'Hatırlatma': 'অনুস্মারক',
    'Bildirim': 'বিজ্ঞপ্তি',
    'Bildirimler': 'বিজ্ঞপ্তি',
    'Bildirim izni': 'বিজ্ঞপ্তির অনুমতি',
    'Kesin alarm izni': 'সঠিক সময়ের অ্যালার্মের অনুমতি',
    'Bildirim saati': 'বিজ্ঞপ্তির সময়',
    'Hatırlatma zamanı': 'অনুস্মারকের সময়',
    'Günde bir': 'দিনে একবার',
    'Günde üç kez': 'দিনে তিনবার',
    'Bildirimleri aç': 'বিজ্ঞপ্তি চালু করুন',
    'Bildirimleri kapat': 'বিজ্ঞপ্তি বন্ধ করুন',
    'Planlandı': 'সময়সূচিভুক্ত',
    'Planlanamadı': 'সময়সূচিভুক্ত করা যায়নি',
    'Yaklaşık planlama': 'আনুমানিক সময়সূচি',
    'Dakik planlama': 'সঠিক সময়সূচি',
    'Arka plan': 'পটভূমি',
    'Pil optimizasyonu': 'ব্যাটারি অপ্টিমাইজেশন',
    'İzin gerekli': 'অনুমতি প্রয়োজন',
    'İzin ver': 'অনুমতি দিন',
    'Daha sonra': 'পরে',
    'Bugün': 'আজ',
    'Yarın': 'আগামীকাল',
    'Dün': 'গতকাল',
    'Kalan gün': 'বাকি দিন',
    'Gecikmede': 'বিলম্বিত',
    'Rapor': 'প্রতিবেদন',
    'Aylık rapor': 'মাসিক প্রতিবেদন',
    'Yıllık rapor': 'বার্ষিক প্রতিবেদন',
    'Haftalık rapor': 'সাপ্তাহিক প্রতিবেদন',
    'Tarih aralığı': 'তারিখের পরিসর',
    'Başlangıç tarihi': 'শুরুর তারিখ',
    'Bitiş tarihi': 'শেষের তারিখ',
    'Toplam gider': 'মোট খরচ',
    'Toplam gelir': 'মোট আয়',
    'Net durum': 'নিট অবস্থা',
    'Dağılım': 'বণ্টন',
    'Grafik': 'চার্ট',
    'PDF': 'PDF',
    'CSV': 'CSV',
    'Dışa aktar': 'রপ্তানি করুন',
    'İçe aktar': 'আমদানি করুন',
    'Paylaş': 'শেয়ার করুন',
    'Yedek': 'ব্যাকআপ',
    'Yedek oluştur': 'ব্যাকআপ তৈরি করুন',
    'Yedeği geri yükle': 'ব্যাকআপ পুনরুদ্ধার করুন',
    'Yedekleri birleştir': 'ব্যাকআপ একত্র করুন',
    'Veriler korundu': 'তথ্য সুরক্ষিত আছে',
    'Veri kaybı': 'তথ্য হারানো',
    'Kayıt eklendi': 'রেকর্ড যোগ করা হয়েছে',
    'Kayıt güncellendi': 'রেকর্ড হালনাগাদ হয়েছে',
    'Kayıt silindi': 'রেকর্ড মুছে ফেলা হয়েছে',
    'Son güncelleme': 'সর্বশেষ হালনাগাদ',
    'Dosya': 'ফাইল',
    'Dosya adı': 'ফাইলের নাম',
    'Depolama': 'সংরক্ষণাগার',
    'Dil': 'ভাষা',
    'Ülke': 'দেশ',
    'Borç bölgesi': 'ঋণ অঞ্চল',
    'Tema': 'থিম',
    'Açık tema': 'হালকা থিম',
    'Koyu tema': 'গাঢ় থিম',
    'Sistem teması': 'সিস্টেম থিম',
    'Ücretsiz': 'বিনামূল্যে',
    'Pro': 'প্রো',
    'Ömür boyu': 'আজীবন',
    'Tek seferlik': 'এককালীন',
    'Promosyon kodu': 'প্রচার কোড',
    'Geçersiz kod': 'অবৈধ কোড',
    'Kod kullanıldı': 'কোডটি ব্যবহার করা হয়েছে',
    'İnternet bağlantısı': 'ইন্টারনেট সংযোগ',
    'Çevrimdışı': 'অফলাইন',
    'Çevrimiçi': 'অনলাইন',
    'Hata': 'ত্রুটি',
    'Uyarı': 'সতর্কতা',
    'Başarılı': 'সফল',
    'Başarısız': 'ব্যর্থ',
    'Zorunlu alan': 'আবশ্যিক ঘর',
    'Geçersiz tutar': 'অবৈধ পরিমাণ',
    'Geçersiz tarih': 'অবৈধ তারিখ',
    'Kayıt bulunamadı': 'কোনো রেকর্ড পাওয়া যায়নি',
    'Sonuç bulunamadı': 'কোনো ফল পাওয়া যায়নি',
    'Tekrar dene': 'আবার চেষ্টা করুন',
    'ONAYLIYORUM': 'আমি নিশ্চিত করছি',
}

# Explicitly rejected unnatural or semantically unsafe Bengali copy.
BENGALI_FORBIDDEN_COPY = {
    'বাকি পরিশোধের দায়',  # ambiguous with overdue; use অবশিষ্ট for remaining liability
    'বকেয়া পরিশোধের দায়',  # can mean either outstanding or overdue across regions
    'টেক্সট ওভারফ্লো',
    'রেকর্ডযুক্ত রেকর্ড',
    'আমি CONFIRM করছি',
    'এক - কালীন',
    'স্বয়ংক্রিয় সমতুল্যকরণ',
}

BENGALI_ALLOWED_LATIN_TERMS = {
    'MİZAN GLOBAL', 'MİZAN', 'MIZAN', 'LEFFERION PRIME',
    'Android', 'CSV', 'PDF', 'ISO', 'IBAN', 'BDT', 'INR', 'TRY', 'USD',
    'EUR', 'WhatsApp',
}
