from __future__ import annotations

HEBREW_DIGITS = "0123456789"
HEBREW_REQUIRED_CHARACTERS = ("א", "ב", "מ", "ש", "ת")
HEBREW_FORBIDDEN_LITERAL_BIDI = tuple(
    chr(code)
    for code in (
        0x200E,
        0x200F,
        0x202A,
        0x202B,
        0x202C,
        0x202D,
        0x202E,
        0x2066,
        0x2067,
        0x2068,
        0x2069,
    )
)

# This is a reviewed terminology foundation, not the final 791-key catalog.
# Keys preserve the stable Turkish source vocabulary; values define the
# preferred Israel-oriented Modern Hebrew product wording.
HEBREW_TERMINOLOGY: dict[str, str] = {
    "Ana sayfa": "דף הבית",
    "Kayıtlar": "רשומות",
    "Giderler": "הוצאות",
    "Raporlar": "דוחות",
    "Ayarlar": "הגדרות",
    "Kaydet": "שמירה",
    "Sil": "מחיקה",
    "Düzenle": "עריכה",
    "Devam et": "המשך",
    "Vazgeç": "ביטול",
    "Ekle": "הוספה",
    "Geri": "חזרה",
    "İleri": "הבא",
    "Kapat": "סגירה",
    "Aç": "הפעלה",
    "Ara": "חיפוש",
    "Filtrele": "סינון",
    "Sıfırla": "איפוס",
    "Onayla": "אישור",
    "İptal": "ביטול",
    "Tamam": "אישור",
    "Detaylar": "פרטים",
    "Özet": "סיכום",
    "Geçmiş": "היסטוריה",
    "Takvim": "לוח שנה",
    "Notlar": "הערות",
    "Kategoriler": "קטגוריות",
    "Kişiler": "אנשים",
    "Tümü": "הכול",
    "Seçili": "נבחר",
    "Seçim": "בחירה",
    "Boş durum": "מצב ריק",
    "Borç": "חוב",
    "Banka borcu": "חוב בנקאי",
    "Kişisel borç": "חוב אישי",
    "Kurumsal borç": "חוב עסקי",
    "Borç türü": "סוג חוב",
    "Borç adı": "שם החוב",
    "Borç ürünü": "מוצר אשראי",
    "Kredi kartı": "כרטיס אשראי",
    "Kredi": "הלוואה",
    "Ev kredisi": "משכנתה",
    "Araç kredisi": "הלוואה לרכב",
    "KMH hesabı": "מסגרת משיכת יתר",
    "Nakit avans": "משיכת מזומן באשראי",
    "Taksitli nakit avans": "משיכת מזומן בתשלומים",
    "Çek": "המחאה",
    "Senet": "שטר חוב",
    "Ödeme": "תשלום",
    "Ödeme tutarı": "סכום התשלום",
    "Toplam ödeme": "סך התשלומים",
    "Kalan ödeme": "יתרת התשלום",
    "Kalan bakiye": "יתרה נותרת",
    "Bakiye": "יתרה",
    "Vade": "מועד פירעון",
    "Son ödeme tarihi": "מועד אחרון לתשלום",
    "Vade tarihi": "מועד פירעון",
    "Gecikmiş": "באיחור",
    "Gecikme": "איחור",
    "Gecikme günü": "מספר ימי איחור",
    "Gecikme faizi": "ריבית פיגורים",
    "Faiz": "ריבית",
    "Ana para": "קרן",
    "Kullanılan limit": "מסגרת מנוצלת",
    "Toplam limit": "מסגרת כוללת",
    "Kullanılabilir limit": "מסגרת זמינה",
    "Fatura": "חשבון",
    "Elektrik faturası": "חשבון חשמל",
    "Su faturası": "חשבון מים",
    "Doğalgaz faturası": "חשבון גז",
    "İnternet faturası": "חשבון אינטרנט",
    "Telefon faturası": "חשבון טלפון",
    "Abonelik": "מנוי",
    "Kira": "שכר דירה",
    "Taksit": "תשלום בתשלומים",
    "Kira ve Taksitler": "שכר דירה ותשלומים",
    "Gider": "הוצאה",
    "Gelir": "הכנסה",
    "Gider kategorisi": "קטגוריית הוצאה",
    "Gelir kategorisi": "קטגוריית הכנסה",
    "Tutar": "סכום",
    "Para birimi": "מטבע",
    "Varsayılan para birimi": "מטבע ברירת מחדל",
    "Döviz kuru": "שער חליפין",
    "İşlem": "עסקה",
    "İşlem tarihi": "תאריך העסקה",
    "Ödeme geçmişi": "היסטוריית תשלומים",
    "Kalan ödeme yükü": "התחייבויות תשלום שנותרו",
    "Yaklaşan ödeme": "תשלום קרוב",
    "Yaklaşan ödeme yükü": "התחייבויות תשלום קרובות",
    "Ödenen": "שולם",
    "Ödenmedi": "לא שולם",
    "Kısmi ödeme": "תשלום חלקי",
    "Peşin ödeme": "תשלום מראש",
    "Otomatik ödeme": "תשלום אוטומטי",
    "Tahsilat": "גבייה",
    "Alacak": "חוב לקבל",
    "Alacaklı": "נושה",
    "Borçlu": "חייב",
    "Müşteri": "לקוח",
    "Tedarikçi": "ספק",
    "Banka": "בנק",
    "Hesap": "חשבון",
    "Hesap numarası": "מספר חשבון",
    "IBAN": "IBAN",
    "Kart": "כרטיס",
    "Kart numarası": "מספר כרטיס",
    "Ekstre": "דף פירוט",
    "Ekstre tarihi": "תאריך דף הפירוט",
    "Kesim tarihi": "מועד סגירת החשבון",
    "Asgari ödeme": "תשלום מינימלי",
    "Kalan toplam borç": "סך החוב שנותר",
    "Toplam borç": "סך החוב",
    "Borç bakiyesi": "יתרת חוב",
    "Düzenli ödeme": "תשלום קבוע",
    "Tek seferlik ödeme": "תשלום חד-פעמי",
    "Yinelenen ödeme": "תשלום חוזר",
    "Hatırlatma": "תזכורת",
    "Bildirim": "התראה",
    "Bildirimler": "התראות",
    "Bildirim izni": "הרשאת התראות",
    "Kesin alarm izni": "הרשאה לתזמון מדויק",
    "Bildirim saati": "שעת ההתראה",
    "Hatırlatma zamanı": "זמן התזכורת",
    "Günde bir": "פעם ביום",
    "Günde üç kez": "שלוש פעמים ביום",
    "Bildirimleri aç": "הפעלת התראות",
    "Bildirimleri kapat": "השבתת התראות",
    "Planlandı": "תוזמן",
    "Planlanamadı": "לא ניתן לתזמן",
    "Yaklaşık planlama": "תזמון משוער",
    "Dakik planlama": "תזמון מדויק",
    "Arka plan": "רקע",
    "Pil optimizasyonu": "מיטוב סוללה",
    "İzin gerekli": "נדרשת הרשאה",
    "İzin ver": "מתן הרשאה",
    "Daha sonra": "מאוחר יותר",
    "Bugün": "היום",
    "Yarın": "מחר",
    "Dün": "אתמול",
    "Kalan gün": "ימים שנותרו",
    "Gecikmede": "באיחור",
    "Rapor": "דוח",
    "Aylık rapor": "דוח חודשי",
    "Yıllık rapor": "דוח שנתי",
    "Haftalık rapor": "דוח שבועי",
    "Tarih aralığı": "טווח תאריכים",
    "Başlangıç tarihi": "תאריך התחלה",
    "Bitiş tarihi": "תאריך סיום",
    "Toplam gider": "סך ההוצאות",
    "Toplam gelir": "סך ההכנסות",
    "Net durum": "מאזן נטו",
    "Dağılım": "התפלגות",
    "Grafik": "תרשים",
    "PDF": "PDF",
    "CSV": "CSV",
    "Dışa aktar": "ייצוא",
    "İçe aktar": "ייבוא",
    "Paylaş": "שיתוף",
    "Yedek": "גיבוי",
    "Yedek oluştur": "יצירת גיבוי",
    "Yedeği geri yükle": "שחזור גיבוי",
    "Yedekleri birleştir": "מיזוג גיבויים",
    "Veriler korundu": "הנתונים נשמרו",
    "Veri kaybı": "אובדן נתונים",
    "Kayıt eklendi": "הרשומה נוספה",
    "Kayıt güncellendi": "הרשומה עודכנה",
    "Kayıt silindi": "הרשומה נמחקה",
    "Son güncelleme": "עדכון אחרון",
    "Dosya": "קובץ",
    "Dosya adı": "שם קובץ",
    "Depolama": "אחסון",
    "Yerel depolama": "אחסון מקומי",
    "Gizlilik": "פרטיות",
    "Güvenlik": "אבטחה",
    "Dil": "שפה",
    "Ülke": "מדינה",
    "Bölge": "אזור",
    "İbranice": "עברית",
    "İsrail": "ישראל",
    "Kişi ekle": "הוספת אדם",
    "Kişi düzenle": "עריכת אדם",
    "Kişi sil": "מחיקת אדם",
    "Kayıt sahibi": "בעל הרשומה",
    "Ad": "שם",
    "Soyad": "שם משפחה",
    "Başlık": "כותרת",
    "Açıklama": "תיאור",
    "Not": "הערה",
    "Kategori": "קטגוריה",
    "Yeni kategori": "קטגוריה חדשה",
    "Tema": "ערכת נושא",
    "Açık tema": "מצב בהיר",
    "Koyu tema": "מצב כהה",
    "Sistem teması": "ערכת נושא של המערכת",
    "Uygulama dili": "שפת היישום",
    "Borç bölgesi": "אזור החוב",
    "İlk kurulum": "הגדרה ראשונית",
    "Hakkında": "מידע על היישום",
    "Sürüm": "גרסה",
    "Yasal": "מידע משפטי",
    "Yardım": "עזרה",
    "Destek": "תמיכה",
    "Geri bildirim": "משוב",
    "Hata": "שגיאה",
    "Uyarı": "אזהרה",
    "Başarılı": "הפעולה הושלמה",
    "İşlem başarısız": "הפעולה נכשלה",
    "Tekrar dene": "ניסיון חוזר",
    "Zorunlu alan": "שדה חובה",
    "Geçersiz değer": "ערך לא תקין",
    "Eşleşen sonuç bulunamadı": "לא נמצאו תוצאות תואמות",
    "Kayıt bulunamadı": "לא נמצאו רשומות",
    "Yükleniyor": "בטעינה",
    "Hazır": "מוכן",
    "Çevrimdışı": "לא מקוון",
    "Ocak": "ינואר",
    "Şubat": "פברואר",
    "Mart": "מרץ",
    "Nisan": "אפריל",
    "Mayıs": "מאי",
    "Haziran": "יוני",
    "Temmuz": "יולי",
    "Ağustos": "אוגוסט",
    "Eylül": "ספטמבר",
    "Ekim": "אוקטובר",
    "Kasım": "נובמבר",
    "Aralık": "דצמבר",
    "Pazartesi": "יום שני",
    "Salı": "יום שלישי",
    "Çarşamba": "יום רביעי",
    "Perşembe": "יום חמישי",
    "Cuma": "יום שישי",
    "Cumartesi": "שבת",
    "Pazar": "יום ראשון",
    "Saat": "שעה",
    "Dakika": "דקה",
    "Gün": "יום",
    "Ay": "חודש",
    "Yıl": "שנה",
}

REQUIRED_HEBREW_TERMS = {
    "חוב",
    "תשלום",
    "הוצאה",
    "הכנסה",
    "יתרה",
    "מועד פירעון",
    "באיחור",
    "חשבון",
    "מנוי",
    "שכר דירה",
    "תזכורת",
    "התראה",
    "הרשאת התראות",
    "הרשאה לתזמון מדויק",
    "גיבוי",
    "מיזוג גיבויים",
    "דוח",
    "הגדרות",
    "ייצוא",
    "ייבוא",
    "שחזור גיבוי",
    "מטבע",
    "כרטיס אשראי",
    "הלוואה",
    "משכנתה",
    "מסגרת משיכת יתר",
}
