from __future__ import annotations

HINDI_REQUIRED_CHARACTERS = ('अ', 'क', 'त', 'न', 'म', 'र')
HINDI_FORBIDDEN_INVISIBLE = tuple(chr(code) for code in (
    0x200B, 0x200C, 0x200D, 0x200E, 0x200F,
    0x202A, 0x202B, 0x202C, 0x202D, 0x202E,
    0x2066, 0x2067, 0x2068, 0x2069,
))

# Stable Turkish source vocabulary mapped to preferred India-oriented Hindi.
HINDI_TERMINOLOGY: dict[str, str] = {
    'Ana sayfa': 'मुख्य पृष्ठ',
    'Kayıtlar': 'रिकॉर्ड',
    'Giderler': 'खर्च',
    'Raporlar': 'रिपोर्ट',
    'Ayarlar': 'सेटिंग्स',
    'Kaydet': 'सहेजें',
    'Sil': 'हटाएँ',
    'Düzenle': 'संपादित करें',
    'Devam et': 'जारी रखें',
    'Vazgeç': 'रद्द करें',
    'Ekle': 'जोड़ें',
    'Geri': 'वापस',
    'İleri': 'आगे',
    'Kapat': 'बंद करें',
    'Aç': 'चालू करें',
    'Ara': 'खोजें',
    'Filtrele': 'फ़िल्टर करें',
    'Sıfırla': 'रीसेट करें',
    'Onayla': 'पुष्टि करें',
    'İptal': 'रद्द करें',
    'Tamam': 'ठीक है',
    'Detaylar': 'विवरण',
    'Özet': 'सारांश',
    'Geçmiş': 'इतिहास',
    'Takvim': 'कैलेंडर',
    'Notlar': 'नोट्स',
    'Kategoriler': 'श्रेणियाँ',
    'Kişiler': 'लोग',
    'Tümü': 'सभी',
    'Seçili': 'चुना गया',
    'Borç': 'कर्ज़',
    'Banka borcu': 'बैंक का कर्ज़',
    'Kişisel borç': 'व्यक्तिगत कर्ज़',
    'Kurumsal borç': 'व्यावसायिक कर्ज़',
    'Borç türü': 'कर्ज़ का प्रकार',
    'Borç adı': 'कर्ज़ का नाम',
    'Borç ürünü': 'क्रेडिट उत्पाद',
    'Kredi kartı': 'क्रेडिट कार्ड',
    'Kredi': 'लोन',
    'Ev kredisi': 'होम लोन',
    'Araç kredisi': 'वाहन लोन',
    'KMH hesabı': 'ओवरड्राफ्ट खाता',
    'Nakit avans': 'कैश एडवांस',
    'Taksitli nakit avans': 'किस्तों में कैश एडवांस',
    'Çek': 'चेक',
    'Senet': 'प्रॉमिसरी नोट',
    'Ödeme': 'भुगतान',
    'Ödeme tutarı': 'भुगतान राशि',
    'Toplam ödeme': 'कुल भुगतान',
    'Kalan ödeme': 'बाकी भुगतान',
    'Kalan bakiye': 'बाकी शेष राशि',
    'Bakiye': 'शेष राशि',
    'Vade': 'देय तिथि',
    'Son ödeme tarihi': 'अंतिम भुगतान तिथि',
    'Vade tarihi': 'देय तिथि',
    'Gecikmiş': 'बकाया',
    'Gecikme': 'देरी',
    'Gecikme günü': 'देरी के दिन',
    'Gecikme faizi': 'विलंब ब्याज',
    'Faiz': 'ब्याज',
    'Ana para': 'मूलधन',
    'Kullanılan limit': 'इस्तेमाल की गई सीमा',
    'Toplam limit': 'कुल सीमा',
    'Kullanılabilir limit': 'उपलब्ध सीमा',
    'Fatura': 'बिल',
    'Elektrik faturası': 'बिजली का बिल',
    'Su faturası': 'पानी का बिल',
    'Doğalgaz faturası': 'गैस का बिल',
    'İnternet faturası': 'इंटरनेट बिल',
    'Telefon faturası': 'फ़ोन बिल',
    'Abonelik': 'सदस्यता',
    'Kira': 'किराया',
    'Taksit': 'किस्त',
    'Kira ve Taksitler': 'किराया और किस्तें',
    'Gider': 'खर्च',
    'Gelir': 'आय',
    'Gider kategorisi': 'खर्च की श्रेणी',
    'Gelir kategorisi': 'आय की श्रेणी',
    'Tutar': 'राशि',
    'Para birimi': 'मुद्रा',
    'Varsayılan para birimi': 'डिफ़ॉल्ट मुद्रा',
    'Döviz kuru': 'विनिमय दर',
    'İşlem': 'लेन-देन',
    'İşlem tarihi': 'लेन-देन की तारीख',
    'Ödeme geçmişi': 'भुगतान इतिहास',
    'Kalan ödeme yükü': 'बाकी भुगतान दायित्व',
    'Yaklaşan ödeme': 'आगामी भुगतान',
    'Yaklaşan ödeme yükü': 'आगामी भुगतान दायित्व',
    'Ödenen': 'भुगतान किया गया',
    'Ödenmedi': 'भुगतान नहीं हुआ',
    'Kısmi ödeme': 'आंशिक भुगतान',
    'Peşin ödeme': 'अग्रिम भुगतान',
    'Otomatik ödeme': 'स्वचालित भुगतान',
    'Tahsilat': 'वसूली',
    'Alacak': 'प्राप्य राशि',
    'Alacaklı': 'लेनदार',
    'Borçlu': 'देनदार',
    'Müşteri': 'ग्राहक',
    'Tedarikçi': 'आपूर्तिकर्ता',
    'Banka': 'बैंक',
    'Hesap': 'खाता',
    'Hesap numarası': 'खाता संख्या',
    'IBAN': 'IBAN',
    'Kart': 'कार्ड',
    'Kart numarası': 'कार्ड संख्या',
    'Ekstre': 'स्टेटमेंट',
    'Ekstre tarihi': 'स्टेटमेंट की तारीख',
    'Kesim tarihi': 'बिलिंग तिथि',
    'Asgari ödeme': 'न्यूनतम भुगतान',
    'Kalan toplam borç': 'कुल बाकी कर्ज़',
    'Toplam borç': 'कुल कर्ज़',
    'Borç bakiyesi': 'कर्ज़ की शेष राशि',
    'Düzenli ödeme': 'नियमित भुगतान',
    'Tek seferlik ödeme': 'एकमुश्त भुगतान',
    'Yinelenen ödeme': 'दोहराया जाने वाला भुगतान',
    'Hatırlatma': 'रिमाइंडर',
    'Bildirim': 'सूचना',
    'Bildirimler': 'सूचनाएँ',
    'Bildirim izni': 'सूचना की अनुमति',
    'Kesin alarm izni': 'सटीक अलार्म की अनुमति',
    'Bildirim saati': 'सूचना का समय',
    'Hatırlatma zamanı': 'रिमाइंडर का समय',
    'Günde bir': 'दिन में एक बार',
    'Günde üç kez': 'दिन में तीन बार',
    'Bildirimleri aç': 'सूचनाएँ चालू करें',
    'Bildirimleri kapat': 'सूचनाएँ बंद करें',
    'Planlandı': 'निर्धारित',
    'Planlanamadı': 'निर्धारित नहीं हो सका',
    'Yaklaşık planlama': 'अनुमानित समय-निर्धारण',
    'Dakik planlama': 'सटीक समय-निर्धारण',
    'Arka plan': 'पृष्ठभूमि',
    'Pil optimizasyonu': 'बैटरी अनुकूलन',
    'İzin gerekli': 'अनुमति आवश्यक',
    'İzin ver': 'अनुमति दें',
    'Daha sonra': 'बाद में',
    'Bugün': 'आज',
    'Yarın': 'कल',
    'Dün': 'बीता कल',
    'Kalan gün': 'बाकी दिन',
    'Gecikmede': 'बकाया',
    'Rapor': 'रिपोर्ट',
    'Aylık rapor': 'मासिक रिपोर्ट',
    'Yıllık rapor': 'वार्षिक रिपोर्ट',
    'Haftalık rapor': 'साप्ताहिक रिपोर्ट',
    'Tarih aralığı': 'तारीख सीमा',
    'Başlangıç tarihi': 'आरंभ तिथि',
    'Bitiş tarihi': 'समाप्ति तिथि',
    'Toplam gider': 'कुल खर्च',
    'Toplam gelir': 'कुल आय',
    'Net durum': 'शुद्ध स्थिति',
    'Dağılım': 'वितरण',
    'Grafik': 'चार्ट',
    'PDF': 'PDF',
    'CSV': 'CSV',
    'Dışa aktar': 'निर्यात करें',
    'İçe aktar': 'आयात करें',
    'Paylaş': 'साझा करें',
    'Yedek': 'बैकअप',
    'Yedek oluştur': 'बैकअप बनाएँ',
    'Yedeği geri yükle': 'बैकअप पुनर्स्थापित करें',
    'Yedekleri birleştir': 'बैकअप मिलाएँ',
    'Veriler korundu': 'डेटा सुरक्षित रहा',
    'Veri kaybı': 'डेटा हानि',
    'Kayıt eklendi': 'रिकॉर्ड जोड़ा गया',
    'Kayıt güncellendi': 'रिकॉर्ड अपडेट हुआ',
    'Kayıt silindi': 'रिकॉर्ड हटाया गया',
    'Son güncelleme': 'अंतिम अपडेट',
    'Dosya': 'फ़ाइल',
    'Dosya adı': 'फ़ाइल का नाम',
    'Depolama': 'संग्रहण',
    'Yerel depolama': 'स्थानीय संग्रहण',
    'Gizlilik': 'गोपनीयता',
    'Güvenlik': 'सुरक्षा',
    'Dil': 'भाषा',
    'Ülke': 'देश',
    'Bölge': 'क्षेत्र',
    'Hintçe': 'हिन्दी',
    'Hindistan': 'भारत',
    'Kişi ekle': 'व्यक्ति जोड़ें',
    'Kişi düzenle': 'व्यक्ति संपादित करें',
    'Kişi sil': 'व्यक्ति हटाएँ',
    'Kayıt sahibi': 'रिकॉर्ड का व्यक्ति',
    'Ad': 'नाम',
    'Soyad': 'उपनाम',
    'Başlık': 'शीर्षक',
    'Açıklama': 'विवरण',
    'Not': 'नोट',
    'Kategori': 'श्रेणी',
    'Yeni kategori': 'नई श्रेणी',
    'Tema': 'थीम',
    'Açık tema': 'हल्की थीम',
    'Koyu tema': 'गहरी थीम',
    'Sistem teması': 'सिस्टम थीम',
    'Uygulama dili': 'ऐप की भाषा',
    'Borç bölgesi': 'कर्ज़ क्षेत्र',
    'İlk kurulum': 'प्रारंभिक सेटअप',
    'Arama': 'खोज',
    'Sonuç bulunamadı': 'कोई परिणाम नहीं मिला',
    'Zorunlu alan': 'आवश्यक फ़ील्ड',
    'Geçersiz değer': 'अमान्य मान',
    'Hata': 'त्रुटि',
    'Uyarı': 'चेतावनी',
    'Başarılı': 'सफल',
    'Yükleniyor': 'लोड हो रहा है',
    'Hazırlanıyor': 'तैयार किया जा रहा है',
    'Tekrar dene': 'फिर से प्रयास करें',
    'Bağlantı': 'कनेक्शन',
    'İnternet bağlantısı': 'इंटरनेट कनेक्शन',
    'Çevrimdışı': 'ऑफ़लाइन',
    'Çevrimiçi': 'ऑनलाइन',
}
