from __future__ import annotations

# İran odaklı, bağlamlı Farsça ürün sözlüğü. Bu veri runtime çeviri
# kataloğu değildir; 791 metin hazırlanırken ve denetlenirken bağlayıcı
# terminoloji referansı olarak kullanılır.
PERSIAN_TERMINOLOGY: dict[str, str] = {
    "active": "فعال",
    "approaching": "نزدیک به سررسید",
    "overdue": "معوق",
    "completed": "تکمیل‌شده",
    "inactive": "غیرفعال",
    "home": "خانه",
    "records": "ثبت‌ها",
    "expenses": "هزینه‌ها",
    "reports": "گزارش‌ها",
    "settings": "تنظیمات",
    "save": "ذخیره",
    "delete": "حذف",
    "edit": "ویرایش",
    "add": "افزودن",
    "continue": "ادامه",
    "cancel": "انصراف",
    "confirm": "تأیید",
    "back": "بازگشت",
    "close": "بستن",
    "search": "جست‌وجو",
    "clear_search": "پاک‌کردن جست‌وجو",
    "language": "زبان",
    "country": "کشور",
    "currency": "واحد پول",
    "default_currency": "واحد پول پیش‌فرض",
    "debt_region": "کشور / منطقه بدهی",
    "person": "شخص",
    "company_institution": "شرکت / سازمان",
    "bank": "بانک",
    "bank_debt": "بدهی بانکی",
    "personal_corporate_debt": "بدهی شخصی / سازمانی",
    "debt": "بدهی",
    "debt_type": "نوع بدهی",
    "credit_card": "کارت اعتباری",
    "loan": "وام",
    "vehicle_loan": "وام خودرو",
    "mortgage": "وام مسکن",
    "overdraft_account": "حساب اضافه‌برداشت",
    "cash_advance": "پیش‌دریافت نقدی",
    "installment_cash_advance": "پیش‌دریافت نقدی اقساطی",
    "custom_debt_type": "نوع بدهی دلخواه",
    "creditor": "طلبکار",
    "remaining_debt": "مانده بدهی",
    "total_debt": "کل بدهی",
    "payment": "پرداخت",
    "payments": "پرداخت‌ها",
    "payment_history": "سابقه پرداخت‌ها",
    "payment_plan": "برنامه پرداخت",
    "payment_amount": "مبلغ پرداخت",
    "payment_method": "روش پرداخت",
    "partial_payment": "پرداخت بخشی",
    "pay_off_debt": "تسویه کامل بدهی",
    "installment_payment": "پرداخت قسط",
    "due_date": "تاریخ سررسید",
    "payment_day": "روز پرداخت",
    "overdue_days": "روزهای تأخیر",
    "overdue_payment": "پرداخت معوق",
    "remaining_payment_burden": "تعهدات پرداخت باقی‌مانده",
    "upcoming_payment": "پرداخت پیش رو",
    "bill": "قبض",
    "bills": "قبض‌ها",
    "electricity": "برق",
    "water": "آب",
    "phone": "تلفن",
    "internet": "اینترنت",
    "natural_gas": "گاز",
    "custom_bill": "قبض دلخواه",
    "bill_amount": "مبلغ قبض",
    "billing_period": "دوره قبض",
    "subscriber_number": "شماره اشتراک",
    "contract_number": "شماره قرارداد",
    "subscription": "اشتراک",
    "subscriptions": "اشتراک‌ها",
    "digital_service": "خدمت دیجیتال",
    "membership": "عضویت",
    "insurance": "بیمه",
    "education": "آموزش",
    "maintenance_service": "نگهداری / سرویس",
    "provider": "ارائه‌دهنده",
    "recurrence": "دوره تکرار",
    "rent": "اجاره",
    "installment": "قسط",
    "rent_installment": "اجاره / قسط",
    "home_rent": "اجاره خانه",
    "product_installment": "قسط کالا",
    "landlord_recipient": "مالک / دریافت‌کننده",
    "monthly_rent": "اجاره ماهانه",
    "total_installments": "تعداد کل اقساط",
    "remaining_installments": "اقساط باقی‌مانده",
    "income": "درآمد",
    "income_type": "نوع درآمد",
    "income_amount": "مبلغ درآمد",
    "salary": "حقوق",
    "income_summary": "خلاصه درآمد",
    "net_after_income": "خالص پس از درآمد",
    "expense": "هزینه",
    "daily_expense": "هزینه روزانه",
    "expense_category": "دسته هزینه",
    "expense_amount": "مبلغ هزینه",
    "unit_price": "قیمت واحد",
    "quantity": "تعداد / مقدار",
    "all_spending": "همه مخارج",
    "total_expense": "کل هزینه",
    "normal_expenses": "هزینه‌های عادی",
    "payment_expenses": "هزینه پرداخت‌ها",
    "report": "گزارش",
    "financial_report": "گزارش مالی",
    "report_scope": "محدوده گزارش",
    "report_summary": "خلاصه گزارش",
    "expense_distribution": "توزیع هزینه‌ها",
    "income_details": "جزئیات درآمد",
    "payment_details": "جزئیات پرداخت‌ها",
    "download_pdf": "دریافت PDF",
    "share_pdf": "اشتراک‌گذاری PDF",
    "pdf_report": "گزارش PDF",
    "notification": "اعلان",
    "notifications": "اعلان‌ها",
    "reminder": "یادآوری",
    "payment_reminder": "یادآوری پرداخت",
    "expense_reminder": "یادآوری هزینه",
    "notification_permission": "مجوز اعلان‌ها",
    "exact_alarm_permission": "مجوز زمان‌بندی دقیق",
    "automatic_sync": "همگام‌سازی خودکار",
    "sound_and_vibration": "صدا و لرزش",
    "silent": "بی‌صدا",
    "test_notification": "اعلان آزمایشی",
    "local_data_security": "امنیت داده‌های محلی",
    "instant_local_save": "ذخیره فوری محلی",
    "backup": "نسخه پشتیبان",
    "verified_backup": "نسخه پشتیبان تأییدشده",
    "csv_backup": "نسخه پشتیبان CSV",
    "export_backup": "خروجی‌گرفتن از نسخه پشتیبان",
    "merge_backup": "ادغام نسخه پشتیبان",
    "restore_backup": "بازیابی نسخه پشتیبان",
    "relationships_preserved": "ارتباط‌ها حفظ می‌شوند",
    "note": "یادداشت",
    "notes": "یادداشت‌ها",
    "description": "توضیحات",
    "category": "دسته",
    "amount": "مبلغ",
    "date": "تاریخ",
    "month": "ماه",
    "year": "سال",
    "today": "امروز",
    "this_month": "این ماه",
    "last_30_days": "۳۰ روز گذشته",
    "last_90_days": "۹۰ روز گذشته",
    "all_time": "همه زمان‌ها",
    "no_records": "هیچ ثبتی وجود ندارد",
    "not_specified": "مشخص نشده",
    "archived": "بایگانی‌شده",
    "archive": "بایگانی",
    "restore_from_archive": "خروج از بایگانی",
    "one_time": "یک‌باره",
    "daily": "روزانه",
    "weekly": "هفتگی",
    "monthly": "ماهانه",
    "yearly": "سالانه",
    "custom_interval": "فاصله دلخواه",
}

PERSIAN_REQUIRED_CHARACTERS = ("ی", "ک")
PERSIAN_FORBIDDEN_SYSTEM_CHARACTERS = ("ي", "ى", "ك", "ے", "ہ", "ھ", "ں", "ٹ", "ڈ", "ڑ")
PERSIAN_DIGITS = "۰۱۲۳۴۵۶۷۸۹"
ARABIC_INDIC_DIGITS = "٠١٢٣٤٥٦٧٨٩"
WESTERN_DIGITS = "0123456789"

# Başlangıç kapsamındaki görünür ürün dili kontrolü için temel terimler.
REQUIRED_TERMS = {
    "بدهی",
    "پرداخت",
    "قبض",
    "اشتراک",
    "اجاره",
    "قسط",
    "درآمد",
    "هزینه",
    "گزارش",
    "تنظیمات",
    "یادآوری",
    "نسخه پشتیبان",
    "تاریخ سررسید",
    "مانده",
}
