abstract final class MonetizationStrings {
  static const Map<String, Map<String, String>> _values = {
    'tr': {
      'premium': 'Premium',
      'premiumSubtitle': 'Reklamsız, çevrimdışı kullanım ve PDF raporları',
      'lifetimePremium': 'Ömür boyu Premium',
      'temporaryPremium': 'Süreli Premium',
      'freePlan': 'Ücretsiz sürüm',
      'premiumActive': 'Premium aktif',
      'remaining': 'Kalan süre',
      'lifetime': 'Süresiz',
      'buyLifetime': 'Ömür boyu Premium satın al',
      'playPrice': 'Fiyat Google Play tarafından gösterilir.',
      'benefitNoAds': 'Reklamsız uygulama deneyimi',
      'benefitOffline': 'İnternetsiz kullanım',
      'benefitPdf': 'PDF raporlarını kaydetme ve paylaşma',
      'restoreInfo': 'Önceki satın alımlar Google Play hesabından otomatik olarak geri yüklenir. Ayrı bir geri yükleme düğmesi gerekmez.',
      'rewardTitle': '1 günlük Premium kazan',
      'rewardSubtitle': 'Bugün 3 ödüllü reklamı tamamla ve 24 saat Premium kazan.',
      'watchReward': 'Ödüllü reklam izle',
      'rewardProgress': 'Bugünkü ilerleme',
      'promoTitle': 'Promosyon kodu',
      'promoHint': 'Kodu gir',
      'promoApply': 'Kodu kullan',
      'promoAccepted': 'Promosyon kodu uygulandı.',
      'promoAlreadyUsed': 'Bu kod bu cihazda daha önce kullanılmış.',
      'promoInvalid': 'Promosyon kodu geçersiz.',
      'promoUnavailable': 'Promosyon servisi şu anda yapılandırılmamış.',
      'promoNetwork': 'Promosyon kodu doğrulanamadı. İnternet bağlantını kontrol et.',
      'internetRequired': 'Bu işlem için internet bağlantısı gerekli.',
      'purchaseUnavailable': 'Google Play satın alma ürünü şu anda kullanılamıyor.',
      'privacyOptions': 'Reklam gizlilik seçenekleri',
      'privacyPolicy': 'Gizlilik Politikası',
      'terms': 'Kullanım Koşulları',
      'purchaseTerms': 'Satın Alma Koşulları',
    },
    'en': {
      'premium': 'Premium',
      'premiumSubtitle': 'Ad-free, offline access and PDF reports',
      'lifetimePremium': 'Lifetime Premium',
      'temporaryPremium': 'Temporary Premium',
      'freePlan': 'Free version',
      'premiumActive': 'Premium active',
      'remaining': 'Time remaining',
      'lifetime': 'No expiration',
      'buyLifetime': 'Buy Lifetime Premium',
      'playPrice': 'The price is displayed by Google Play.',
      'benefitNoAds': 'Ad-free app experience',
      'benefitOffline': 'Offline use',
      'benefitPdf': 'Save and share PDF reports',
      'restoreInfo': 'Previous purchases are restored automatically from your Google Play account. No separate restore button is required.',
      'rewardTitle': 'Earn 1 day of Premium',
      'rewardSubtitle': 'Complete 3 rewarded ads today to receive 24 hours of Premium.',
      'watchReward': 'Watch rewarded ad',
      'rewardProgress': 'Today’s progress',
      'promoTitle': 'Promo code',
      'promoHint': 'Enter code',
      'promoApply': 'Redeem code',
      'promoAccepted': 'Promo code applied.',
      'promoAlreadyUsed': 'This code has already been used on this device.',
      'promoInvalid': 'The promo code is invalid.',
      'promoUnavailable': 'The promotion service is not configured right now.',
      'promoNetwork': 'The promo code could not be verified. Check your internet connection.',
      'internetRequired': 'An internet connection is required for this action.',
      'purchaseUnavailable': 'The Google Play purchase product is currently unavailable.',
      'privacyOptions': 'Ad privacy options',
      'privacyPolicy': 'Privacy Policy',
      'terms': 'Terms of Use',
      'purchaseTerms': 'Purchase Terms',
    },
    'es': {
      'premium': 'Premium', 'premiumSubtitle': 'Sin anuncios, acceso sin conexión e informes PDF', 'lifetimePremium': 'Premium de por vida', 'temporaryPremium': 'Premium temporal', 'freePlan': 'Versión gratuita', 'premiumActive': 'Premium activo', 'remaining': 'Tiempo restante', 'lifetime': 'Sin caducidad', 'buyLifetime': 'Comprar Premium de por vida', 'playPrice': 'Google Play muestra el precio.', 'benefitNoAds': 'Experiencia sin anuncios', 'benefitOffline': 'Uso sin conexión', 'benefitPdf': 'Guardar y compartir informes PDF', 'restoreInfo': 'Las compras anteriores se restauran automáticamente desde tu cuenta de Google Play. No hace falta un botón de restauración.', 'rewardTitle': 'Gana 1 día de Premium', 'rewardSubtitle': 'Completa 3 anuncios con recompensa hoy para obtener 24 horas de Premium.', 'watchReward': 'Ver anuncio con recompensa', 'rewardProgress': 'Progreso de hoy', 'promoTitle': 'Código promocional', 'promoHint': 'Introduce el código', 'promoApply': 'Canjear código', 'promoAccepted': 'Código promocional aplicado.', 'promoAlreadyUsed': 'Este código ya se utilizó en este dispositivo.', 'promoInvalid': 'El código promocional no es válido.', 'promoUnavailable': 'El servicio de promociones no está configurado.', 'promoNetwork': 'No se pudo verificar el código. Comprueba tu conexión.', 'internetRequired': 'Se necesita conexión a Internet para esta acción.', 'purchaseUnavailable': 'La compra de Google Play no está disponible en este momento.', 'privacyOptions': 'Opciones de privacidad de anuncios', 'privacyPolicy': 'Política de privacidad', 'terms': 'Términos de uso', 'purchaseTerms': 'Condiciones de compra',
    },
    'pt-BR': {
      'premium': 'Premium', 'premiumSubtitle': 'Sem anúncios, uso offline e relatórios em PDF', 'lifetimePremium': 'Premium vitalício', 'temporaryPremium': 'Premium temporário', 'freePlan': 'Versão gratuita', 'premiumActive': 'Premium ativo', 'remaining': 'Tempo restante', 'lifetime': 'Sem expiração', 'buyLifetime': 'Comprar Premium vitalício', 'playPrice': 'O preço é exibido pelo Google Play.', 'benefitNoAds': 'Experiência sem anúncios', 'benefitOffline': 'Uso offline', 'benefitPdf': 'Salvar e compartilhar relatórios em PDF', 'restoreInfo': 'Compras anteriores são restauradas automaticamente pela sua conta do Google Play. Não é necessário um botão separado de restauração.', 'rewardTitle': 'Ganhe 1 dia de Premium', 'rewardSubtitle': 'Conclua 3 anúncios recompensados hoje e receba 24 horas de Premium.', 'watchReward': 'Assistir anúncio recompensado', 'rewardProgress': 'Progresso de hoje', 'promoTitle': 'Código promocional', 'promoHint': 'Digite o código', 'promoApply': 'Resgatar código', 'promoAccepted': 'Código promocional aplicado.', 'promoAlreadyUsed': 'Este código já foi usado neste dispositivo.', 'promoInvalid': 'O código promocional é inválido.', 'promoUnavailable': 'O serviço de promoções não está configurado.', 'promoNetwork': 'Não foi possível verificar o código. Verifique sua conexão.', 'internetRequired': 'É necessária conexão com a internet para esta ação.', 'purchaseUnavailable': 'A compra no Google Play está indisponível no momento.', 'privacyOptions': 'Opções de privacidade de anúncios', 'privacyPolicy': 'Política de Privacidade', 'terms': 'Termos de Uso', 'purchaseTerms': 'Termos de Compra',
    },
    'pt-PT': {
      'premium': 'Premium', 'premiumSubtitle': 'Sem anúncios, utilização offline e relatórios PDF', 'lifetimePremium': 'Premium vitalício', 'temporaryPremium': 'Premium temporário', 'freePlan': 'Versão gratuita', 'premiumActive': 'Premium ativo', 'remaining': 'Tempo restante', 'lifetime': 'Sem expiração', 'buyLifetime': 'Comprar Premium vitalício', 'playPrice': 'O preço é apresentado pelo Google Play.', 'benefitNoAds': 'Experiência sem anúncios', 'benefitOffline': 'Utilização offline', 'benefitPdf': 'Guardar e partilhar relatórios PDF', 'restoreInfo': 'As compras anteriores são restauradas automaticamente através da sua conta Google Play. Não é necessário um botão separado de restauro.', 'rewardTitle': 'Ganhe 1 dia de Premium', 'rewardSubtitle': 'Conclua 3 anúncios recompensados hoje e receba 24 horas de Premium.', 'watchReward': 'Ver anúncio recompensado', 'rewardProgress': 'Progresso de hoje', 'promoTitle': 'Código promocional', 'promoHint': 'Introduza o código', 'promoApply': 'Resgatar código', 'promoAccepted': 'Código promocional aplicado.', 'promoAlreadyUsed': 'Este código já foi utilizado neste dispositivo.', 'promoInvalid': 'O código promocional é inválido.', 'promoUnavailable': 'O serviço de promoções não está configurado.', 'promoNetwork': 'Não foi possível verificar o código. Verifique a ligação.', 'internetRequired': 'É necessária uma ligação à Internet para esta ação.', 'purchaseUnavailable': 'A compra no Google Play não está disponível neste momento.', 'privacyOptions': 'Opções de privacidade de anúncios', 'privacyPolicy': 'Política de Privacidade', 'terms': 'Termos de Utilização', 'purchaseTerms': 'Termos de Compra',
    },
    'fr': {
      'premium': 'Premium', 'premiumSubtitle': 'Sans publicité, accès hors ligne et rapports PDF', 'lifetimePremium': 'Premium à vie', 'temporaryPremium': 'Premium temporaire', 'freePlan': 'Version gratuite', 'premiumActive': 'Premium actif', 'remaining': 'Temps restant', 'lifetime': 'Sans expiration', 'buyLifetime': 'Acheter Premium à vie', 'playPrice': 'Le prix est affiché par Google Play.', 'benefitNoAds': 'Expérience sans publicité', 'benefitOffline': 'Utilisation hors ligne', 'benefitPdf': 'Enregistrer et partager les rapports PDF', 'restoreInfo': 'Les achats précédents sont restaurés automatiquement depuis votre compte Google Play. Aucun bouton de restauration distinct n’est nécessaire.', 'rewardTitle': 'Gagnez 1 jour de Premium', 'rewardSubtitle': 'Terminez 3 publicités récompensées aujourd’hui pour obtenir 24 heures de Premium.', 'watchReward': 'Voir une publicité récompensée', 'rewardProgress': 'Progression du jour', 'promoTitle': 'Code promotionnel', 'promoHint': 'Saisir le code', 'promoApply': 'Utiliser le code', 'promoAccepted': 'Code promotionnel appliqué.', 'promoAlreadyUsed': 'Ce code a déjà été utilisé sur cet appareil.', 'promoInvalid': 'Le code promotionnel est invalide.', 'promoUnavailable': 'Le service de promotion n’est pas configuré.', 'promoNetwork': 'Impossible de vérifier le code. Vérifiez votre connexion.', 'internetRequired': 'Une connexion Internet est requise pour cette action.', 'purchaseUnavailable': 'L’achat Google Play est actuellement indisponible.', 'privacyOptions': 'Options de confidentialité publicitaire', 'privacyPolicy': 'Politique de confidentialité', 'terms': 'Conditions d’utilisation', 'purchaseTerms': 'Conditions d’achat',
    },
    'de': {
      'premium': 'Premium', 'premiumSubtitle': 'Werbefrei, offline nutzbar und PDF-Berichte', 'lifetimePremium': 'Premium auf Lebenszeit', 'temporaryPremium': 'Zeitlich begrenztes Premium', 'freePlan': 'Kostenlose Version', 'premiumActive': 'Premium aktiv', 'remaining': 'Verbleibende Zeit', 'lifetime': 'Unbegrenzt', 'buyLifetime': 'Premium auf Lebenszeit kaufen', 'playPrice': 'Der Preis wird von Google Play angezeigt.', 'benefitNoAds': 'Werbefreie Nutzung', 'benefitOffline': 'Offline-Nutzung', 'benefitPdf': 'PDF-Berichte speichern und teilen', 'restoreInfo': 'Frühere Käufe werden automatisch über dein Google-Play-Konto wiederhergestellt. Eine separate Wiederherstellen-Schaltfläche ist nicht erforderlich.', 'rewardTitle': '1 Tag Premium erhalten', 'rewardSubtitle': 'Schließe heute 3 Rewarded Ads ab und erhalte 24 Stunden Premium.', 'watchReward': 'Rewarded Ad ansehen', 'rewardProgress': 'Heutiger Fortschritt', 'promoTitle': 'Aktionscode', 'promoHint': 'Code eingeben', 'promoApply': 'Code einlösen', 'promoAccepted': 'Aktionscode angewendet.', 'promoAlreadyUsed': 'Dieser Code wurde auf diesem Gerät bereits verwendet.', 'promoInvalid': 'Der Aktionscode ist ungültig.', 'promoUnavailable': 'Der Aktionsdienst ist derzeit nicht eingerichtet.', 'promoNetwork': 'Der Code konnte nicht geprüft werden. Prüfe die Internetverbindung.', 'internetRequired': 'Für diese Aktion ist eine Internetverbindung erforderlich.', 'purchaseUnavailable': 'Der Google-Play-Kauf ist derzeit nicht verfügbar.', 'privacyOptions': 'Datenschutzoptionen für Werbung', 'privacyPolicy': 'Datenschutzerklärung', 'terms': 'Nutzungsbedingungen', 'purchaseTerms': 'Kaufbedingungen',
    },
    'it': {
      'premium': 'Premium', 'premiumSubtitle': 'Senza pubblicità, uso offline e report PDF', 'lifetimePremium': 'Premium a vita', 'temporaryPremium': 'Premium temporaneo', 'freePlan': 'Versione gratuita', 'premiumActive': 'Premium attivo', 'remaining': 'Tempo rimanente', 'lifetime': 'Senza scadenza', 'buyLifetime': 'Acquista Premium a vita', 'playPrice': 'Il prezzo è mostrato da Google Play.', 'benefitNoAds': 'Esperienza senza pubblicità', 'benefitOffline': 'Uso offline', 'benefitPdf': 'Salva e condividi report PDF', 'restoreInfo': 'Gli acquisti precedenti vengono ripristinati automaticamente dal tuo account Google Play. Non serve un pulsante di ripristino separato.', 'rewardTitle': 'Ottieni 1 giorno di Premium', 'rewardSubtitle': 'Completa 3 annunci con premio oggi per ricevere 24 ore di Premium.', 'watchReward': 'Guarda annuncio con premio', 'rewardProgress': 'Progresso di oggi', 'promoTitle': 'Codice promozionale', 'promoHint': 'Inserisci il codice', 'promoApply': 'Riscatta codice', 'promoAccepted': 'Codice promozionale applicato.', 'promoAlreadyUsed': 'Questo codice è già stato usato su questo dispositivo.', 'promoInvalid': 'Il codice promozionale non è valido.', 'promoUnavailable': 'Il servizio promozioni non è configurato.', 'promoNetwork': 'Impossibile verificare il codice. Controlla la connessione.', 'internetRequired': 'Per questa azione è necessaria una connessione Internet.', 'purchaseUnavailable': 'L’acquisto Google Play non è al momento disponibile.', 'privacyOptions': 'Opzioni privacy annunci', 'privacyPolicy': 'Informativa sulla privacy', 'terms': 'Condizioni d’uso', 'purchaseTerms': 'Condizioni di acquisto',
    },
    'nl': {
      'premium': 'Premium', 'premiumSubtitle': 'Zonder advertenties, offline gebruik en PDF-rapporten', 'lifetimePremium': 'Levenslang Premium', 'temporaryPremium': 'Tijdelijk Premium', 'freePlan': 'Gratis versie', 'premiumActive': 'Premium actief', 'remaining': 'Resterende tijd', 'lifetime': 'Geen vervaldatum', 'buyLifetime': 'Levenslang Premium kopen', 'playPrice': 'De prijs wordt door Google Play getoond.', 'benefitNoAds': 'Advertentievrije ervaring', 'benefitOffline': 'Offline gebruik', 'benefitPdf': 'PDF-rapporten opslaan en delen', 'restoreInfo': 'Eerdere aankopen worden automatisch hersteld via je Google Play-account. Een aparte herstelknop is niet nodig.', 'rewardTitle': 'Verdien 1 dag Premium', 'rewardSubtitle': 'Voltooi vandaag 3 beloonde advertenties en ontvang 24 uur Premium.', 'watchReward': 'Beloonde advertentie bekijken', 'rewardProgress': 'Voortgang vandaag', 'promoTitle': 'Promotiecode', 'promoHint': 'Voer code in', 'promoApply': 'Code inwisselen', 'promoAccepted': 'Promotiecode toegepast.', 'promoAlreadyUsed': 'Deze code is al op dit apparaat gebruikt.', 'promoInvalid': 'De promotiecode is ongeldig.', 'promoUnavailable': 'De promotieservice is niet ingesteld.', 'promoNetwork': 'De code kon niet worden gecontroleerd. Controleer je verbinding.', 'internetRequired': 'Voor deze actie is een internetverbinding vereist.', 'purchaseUnavailable': 'De Google Play-aankoop is momenteel niet beschikbaar.', 'privacyOptions': 'Privacyopties voor advertenties', 'privacyPolicy': 'Privacybeleid', 'terms': 'Gebruiksvoorwaarden', 'purchaseTerms': 'Aankoopvoorwaarden',
    },
    'pl': {
      'premium': 'Premium', 'premiumSubtitle': 'Bez reklam, tryb offline i raporty PDF', 'lifetimePremium': 'Premium bezterminowe', 'temporaryPremium': 'Premium czasowe', 'freePlan': 'Wersja bezpłatna', 'premiumActive': 'Premium aktywne', 'remaining': 'Pozostały czas', 'lifetime': 'Bez terminu ważności', 'buyLifetime': 'Kup Premium bezterminowe', 'playPrice': 'Cena jest wyświetlana przez Google Play.', 'benefitNoAds': 'Korzystanie bez reklam', 'benefitOffline': 'Działanie offline', 'benefitPdf': 'Zapisywanie i udostępnianie raportów PDF', 'restoreInfo': 'Poprzednie zakupy są automatycznie przywracane z konta Google Play. Osobny przycisk przywracania nie jest potrzebny.', 'rewardTitle': 'Zdobądź 1 dzień Premium', 'rewardSubtitle': 'Obejrzyj dziś 3 reklamy z nagrodą, aby otrzymać 24 godziny Premium.', 'watchReward': 'Obejrzyj reklamę z nagrodą', 'rewardProgress': 'Dzisiejszy postęp', 'promoTitle': 'Kod promocyjny', 'promoHint': 'Wpisz kod', 'promoApply': 'Wykorzystaj kod', 'promoAccepted': 'Kod promocyjny zastosowany.', 'promoAlreadyUsed': 'Ten kod był już użyty na tym urządzeniu.', 'promoInvalid': 'Kod promocyjny jest nieprawidłowy.', 'promoUnavailable': 'Usługa promocji nie jest skonfigurowana.', 'promoNetwork': 'Nie udało się zweryfikować kodu. Sprawdź połączenie.', 'internetRequired': 'Do tej czynności wymagane jest połączenie z Internetem.', 'purchaseUnavailable': 'Zakup Google Play jest obecnie niedostępny.', 'privacyOptions': 'Opcje prywatności reklam', 'privacyPolicy': 'Polityka prywatności', 'terms': 'Warunki użytkowania', 'purchaseTerms': 'Warunki zakupu',
    },
    'ro': {
      'premium': 'Premium', 'premiumSubtitle': 'Fără reclame, utilizare offline și rapoarte PDF', 'lifetimePremium': 'Premium pe viață', 'temporaryPremium': 'Premium temporar', 'freePlan': 'Versiune gratuită', 'premiumActive': 'Premium activ', 'remaining': 'Timp rămas', 'lifetime': 'Fără expirare', 'buyLifetime': 'Cumpără Premium pe viață', 'playPrice': 'Prețul este afișat de Google Play.', 'benefitNoAds': 'Experiență fără reclame', 'benefitOffline': 'Utilizare offline', 'benefitPdf': 'Salvare și partajare rapoarte PDF', 'restoreInfo': 'Achizițiile anterioare sunt restaurate automat din contul Google Play. Nu este necesar un buton separat de restaurare.', 'rewardTitle': 'Câștigă 1 zi de Premium', 'rewardSubtitle': 'Finalizează astăzi 3 reclame cu recompensă și primești 24 de ore Premium.', 'watchReward': 'Vezi reclamă cu recompensă', 'rewardProgress': 'Progresul de azi', 'promoTitle': 'Cod promoțional', 'promoHint': 'Introdu codul', 'promoApply': 'Folosește codul', 'promoAccepted': 'Cod promoțional aplicat.', 'promoAlreadyUsed': 'Acest cod a fost deja folosit pe acest dispozitiv.', 'promoInvalid': 'Codul promoțional nu este valid.', 'promoUnavailable': 'Serviciul promoțional nu este configurat.', 'promoNetwork': 'Codul nu a putut fi verificat. Verifică conexiunea.', 'internetRequired': 'Este necesară o conexiune la internet pentru această acțiune.', 'purchaseUnavailable': 'Achiziția Google Play nu este disponibilă momentan.', 'privacyOptions': 'Opțiuni de confidențialitate pentru reclame', 'privacyPolicy': 'Politica de confidențialitate', 'terms': 'Condiții de utilizare', 'purchaseTerms': 'Condiții de achiziție',
    },
    'el': {
      'premium': 'Premium', 'premiumSubtitle': 'Χωρίς διαφημίσεις, χρήση εκτός σύνδεσης και αναφορές PDF', 'lifetimePremium': 'Premium εφ’ όρου ζωής', 'temporaryPremium': 'Προσωρινό Premium', 'freePlan': 'Δωρεάν έκδοση', 'premiumActive': 'Το Premium είναι ενεργό', 'remaining': 'Υπόλοιπος χρόνος', 'lifetime': 'Χωρίς λήξη', 'buyLifetime': 'Αγορά Premium εφ’ όρου ζωής', 'playPrice': 'Η τιμή εμφανίζεται από το Google Play.', 'benefitNoAds': 'Χρήση χωρίς διαφημίσεις', 'benefitOffline': 'Χρήση εκτός σύνδεσης', 'benefitPdf': 'Αποθήκευση και κοινοποίηση αναφορών PDF', 'restoreInfo': 'Οι προηγούμενες αγορές επαναφέρονται αυτόματα από τον λογαριασμό Google Play. Δεν απαιτείται ξεχωριστό κουμπί επαναφοράς.', 'rewardTitle': 'Κέρδισε 1 ημέρα Premium', 'rewardSubtitle': 'Ολοκλήρωσε 3 διαφημίσεις με ανταμοιβή σήμερα και πάρε 24 ώρες Premium.', 'watchReward': 'Προβολή διαφήμισης με ανταμοιβή', 'rewardProgress': 'Σημερινή πρόοδος', 'promoTitle': 'Κωδικός προσφοράς', 'promoHint': 'Εισαγωγή κωδικού', 'promoApply': 'Εξαργύρωση κωδικού', 'promoAccepted': 'Ο κωδικός προσφοράς εφαρμόστηκε.', 'promoAlreadyUsed': 'Αυτός ο κωδικός έχει ήδη χρησιμοποιηθεί σε αυτή τη συσκευή.', 'promoInvalid': 'Ο κωδικός προσφοράς δεν είναι έγκυρος.', 'promoUnavailable': 'Η υπηρεσία προσφορών δεν έχει ρυθμιστεί.', 'promoNetwork': 'Δεν ήταν δυνατή η επαλήθευση του κωδικού. Ελέγξτε τη σύνδεση.', 'internetRequired': 'Απαιτείται σύνδεση στο διαδίκτυο για αυτή την ενέργεια.', 'purchaseUnavailable': 'Η αγορά Google Play δεν είναι διαθέσιμη αυτή τη στιγμή.', 'privacyOptions': 'Επιλογές απορρήτου διαφημίσεων', 'privacyPolicy': 'Πολιτική απορρήτου', 'terms': 'Όροι χρήσης', 'purchaseTerms': 'Όροι αγοράς',
    },
    'ru': {
      'premium': 'Premium', 'premiumSubtitle': 'Без рекламы, офлайн-доступ и PDF-отчёты', 'lifetimePremium': 'Бессрочный Premium', 'temporaryPremium': 'Временный Premium', 'freePlan': 'Бесплатная версия', 'premiumActive': 'Premium активен', 'remaining': 'Осталось времени', 'lifetime': 'Без срока действия', 'buyLifetime': 'Купить бессрочный Premium', 'playPrice': 'Цена отображается Google Play.', 'benefitNoAds': 'Без рекламы', 'benefitOffline': 'Работа без интернета', 'benefitPdf': 'Сохранение и отправка PDF-отчётов', 'restoreInfo': 'Предыдущие покупки автоматически восстанавливаются из аккаунта Google Play. Отдельная кнопка восстановления не требуется.', 'rewardTitle': 'Получить 1 день Premium', 'rewardSubtitle': 'Просмотрите сегодня 3 рекламы с вознаграждением и получите 24 часа Premium.', 'watchReward': 'Смотреть рекламу с наградой', 'rewardProgress': 'Прогресс за сегодня', 'promoTitle': 'Промокод', 'promoHint': 'Введите код', 'promoApply': 'Активировать код', 'promoAccepted': 'Промокод применён.', 'promoAlreadyUsed': 'Этот код уже использовался на данном устройстве.', 'promoInvalid': 'Промокод недействителен.', 'promoUnavailable': 'Сервис промокодов пока не настроен.', 'promoNetwork': 'Не удалось проверить код. Проверьте подключение.', 'internetRequired': 'Для этого действия требуется интернет.', 'purchaseUnavailable': 'Покупка через Google Play сейчас недоступна.', 'privacyOptions': 'Настройки конфиденциальности рекламы', 'privacyPolicy': 'Политика конфиденциальности', 'terms': 'Условия использования', 'purchaseTerms': 'Условия покупки',
    },
    'uk': {
      'premium': 'Premium', 'premiumSubtitle': 'Без реклами, офлайн-доступ і PDF-звіти', 'lifetimePremium': 'Безстроковий Premium', 'temporaryPremium': 'Тимчасовий Premium', 'freePlan': 'Безкоштовна версія', 'premiumActive': 'Premium активний', 'remaining': 'Залишок часу', 'lifetime': 'Без строку дії', 'buyLifetime': 'Придбати безстроковий Premium', 'playPrice': 'Ціну показує Google Play.', 'benefitNoAds': 'Без реклами', 'benefitOffline': 'Робота без інтернету', 'benefitPdf': 'Збереження та поширення PDF-звітів', 'restoreInfo': 'Попередні покупки автоматично відновлюються з облікового запису Google Play. Окрема кнопка відновлення не потрібна.', 'rewardTitle': 'Отримати 1 день Premium', 'rewardSubtitle': 'Перегляньте сьогодні 3 реклами з винагородою й отримайте 24 години Premium.', 'watchReward': 'Переглянути рекламу з винагородою', 'rewardProgress': 'Прогрес за сьогодні', 'promoTitle': 'Промокод', 'promoHint': 'Введіть код', 'promoApply': 'Активувати код', 'promoAccepted': 'Промокод застосовано.', 'promoAlreadyUsed': 'Цей код уже використовувався на цьому пристрої.', 'promoInvalid': 'Промокод недійсний.', 'promoUnavailable': 'Сервіс промокодів ще не налаштований.', 'promoNetwork': 'Не вдалося перевірити код. Перевірте з’єднання.', 'internetRequired': 'Для цієї дії потрібне підключення до Інтернету.', 'purchaseUnavailable': 'Покупка Google Play зараз недоступна.', 'privacyOptions': 'Параметри конфіденційності реклами', 'privacyPolicy': 'Політика конфіденційності', 'terms': 'Умови використання', 'purchaseTerms': 'Умови придбання',
    },
    'ar': {
      'premium': 'بريميوم', 'premiumSubtitle': 'بدون إعلانات، استخدام دون اتصال وتقارير PDF', 'lifetimePremium': 'بريميوم مدى الحياة', 'temporaryPremium': 'بريميوم مؤقت', 'freePlan': 'الإصدار المجاني', 'premiumActive': 'بريميوم نشط', 'remaining': 'الوقت المتبقي', 'lifetime': 'بلا انتهاء', 'buyLifetime': 'شراء بريميوم مدى الحياة', 'playPrice': 'يعرض Google Play السعر.', 'benefitNoAds': 'تجربة بلا إعلانات', 'benefitOffline': 'استخدام دون اتصال', 'benefitPdf': 'حفظ تقارير PDF ومشاركتها', 'restoreInfo': 'تُستعاد المشتريات السابقة تلقائيًا من حساب Google Play. لا يلزم زر استعادة منفصل.', 'rewardTitle': 'احصل على يوم واحد من بريميوم', 'rewardSubtitle': 'أكمل 3 إعلانات بمكافأة اليوم لتحصل على 24 ساعة من بريميوم.', 'watchReward': 'مشاهدة إعلان بمكافأة', 'rewardProgress': 'تقدم اليوم', 'promoTitle': 'رمز ترويجي', 'promoHint': 'أدخل الرمز', 'promoApply': 'استخدام الرمز', 'promoAccepted': 'تم تطبيق الرمز الترويجي.', 'promoAlreadyUsed': 'تم استخدام هذا الرمز سابقًا على هذا الجهاز.', 'promoInvalid': 'الرمز الترويجي غير صالح.', 'promoUnavailable': 'خدمة العروض غير مهيأة حاليًا.', 'promoNetwork': 'تعذر التحقق من الرمز. تحقق من اتصال الإنترنت.', 'internetRequired': 'يلزم اتصال بالإنترنت لهذا الإجراء.', 'purchaseUnavailable': 'عملية الشراء عبر Google Play غير متاحة حاليًا.', 'privacyOptions': 'خيارات خصوصية الإعلانات', 'privacyPolicy': 'سياسة الخصوصية', 'terms': 'شروط الاستخدام', 'purchaseTerms': 'شروط الشراء',
    },
    'fa': {
      'premium': 'پریمیوم', 'premiumSubtitle': 'بدون تبلیغ، استفاده آفلاین و گزارش‌های PDF', 'lifetimePremium': 'پریمیوم مادام‌العمر', 'temporaryPremium': 'پریمیوم موقت', 'freePlan': 'نسخه رایگان', 'premiumActive': 'پریمیوم فعال است', 'remaining': 'زمان باقی‌مانده', 'lifetime': 'بدون انقضا', 'buyLifetime': 'خرید پریمیوم مادام‌العمر', 'playPrice': 'قیمت توسط Google Play نمایش داده می‌شود.', 'benefitNoAds': 'تجربه بدون تبلیغ', 'benefitOffline': 'استفاده آفلاین', 'benefitPdf': 'ذخیره و اشتراک گزارش‌های PDF', 'restoreInfo': 'خریدهای قبلی به‌طور خودکار از حساب Google Play بازیابی می‌شوند و دکمه بازیابی جداگانه لازم نیست.', 'rewardTitle': '۱ روز پریمیوم بگیرید', 'rewardSubtitle': 'امروز ۳ تبلیغ جایزه‌دار را کامل کنید و ۲۴ ساعت پریمیوم بگیرید.', 'watchReward': 'مشاهده تبلیغ جایزه‌دار', 'rewardProgress': 'پیشرفت امروز', 'promoTitle': 'کد تخفیف', 'promoHint': 'کد را وارد کنید', 'promoApply': 'استفاده از کد', 'promoAccepted': 'کد اعمال شد.', 'promoAlreadyUsed': 'این کد قبلاً روی این دستگاه استفاده شده است.', 'promoInvalid': 'کد نامعتبر است.', 'promoUnavailable': 'سرویس کدها فعلاً پیکربندی نشده است.', 'promoNetwork': 'کد تأیید نشد. اتصال اینترنت را بررسی کنید.', 'internetRequired': 'برای این کار اتصال اینترنت لازم است.', 'purchaseUnavailable': 'خرید Google Play در حال حاضر در دسترس نیست.', 'privacyOptions': 'گزینه‌های حریم خصوصی تبلیغات', 'privacyPolicy': 'سیاست حریم خصوصی', 'terms': 'شرایط استفاده', 'purchaseTerms': 'شرایط خرید',
    },
    'he': {
      'premium': 'Premium', 'premiumSubtitle': 'ללא פרסומות, שימוש לא מקוון ודוחות PDF', 'lifetimePremium': 'Premium לכל החיים', 'temporaryPremium': 'Premium זמני', 'freePlan': 'גרסה חינמית', 'premiumActive': 'Premium פעיל', 'remaining': 'זמן שנותר', 'lifetime': 'ללא תפוגה', 'buyLifetime': 'רכישת Premium לכל החיים', 'playPrice': 'המחיר מוצג על ידי Google Play.', 'benefitNoAds': 'שימוש ללא פרסומות', 'benefitOffline': 'שימוש לא מקוון', 'benefitPdf': 'שמירה ושיתוף של דוחות PDF', 'restoreInfo': 'רכישות קודמות משוחזרות אוטומטית מחשבון Google Play. אין צורך בכפתור שחזור נפרד.', 'rewardTitle': 'קבל יום Premium', 'rewardSubtitle': 'השלם היום 3 פרסומות מתוגמלות וקבל 24 שעות Premium.', 'watchReward': 'צפייה בפרסומת מתוגמלת', 'rewardProgress': 'התקדמות היום', 'promoTitle': 'קוד קידום', 'promoHint': 'הזן קוד', 'promoApply': 'מימוש קוד', 'promoAccepted': 'קוד הקידום הופעל.', 'promoAlreadyUsed': 'הקוד הזה כבר שומש במכשיר זה.', 'promoInvalid': 'קוד הקידום אינו תקין.', 'promoUnavailable': 'שירות הקידום אינו מוגדר כרגע.', 'promoNetwork': 'לא ניתן לאמת את הקוד. בדוק את החיבור.', 'internetRequired': 'נדרש חיבור לאינטרנט לפעולה זו.', 'purchaseUnavailable': 'הרכישה דרך Google Play אינה זמינה כרגע.', 'privacyOptions': 'אפשרויות פרטיות לפרסומות', 'privacyPolicy': 'מדיניות פרטיות', 'terms': 'תנאי שימוש', 'purchaseTerms': 'תנאי רכישה',
    },
    'hi': {
      'premium': 'प्रीमियम', 'premiumSubtitle': 'विज्ञापन-मुक्त, ऑफ़लाइन उपयोग और PDF रिपोर्ट', 'lifetimePremium': 'आजीवन प्रीमियम', 'temporaryPremium': 'अस्थायी प्रीमियम', 'freePlan': 'मुफ़्त संस्करण', 'premiumActive': 'प्रीमियम सक्रिय', 'remaining': 'शेष समय', 'lifetime': 'कोई समाप्ति नहीं', 'buyLifetime': 'आजीवन प्रीमियम खरीदें', 'playPrice': 'कीमत Google Play द्वारा दिखाई जाती है।', 'benefitNoAds': 'विज्ञापन-मुक्त अनुभव', 'benefitOffline': 'ऑफ़लाइन उपयोग', 'benefitPdf': 'PDF रिपोर्ट सहेजें और साझा करें', 'restoreInfo': 'पिछली खरीदारी आपके Google Play खाते से अपने-आप पुनर्स्थापित होती है। अलग रिस्टोर बटन की आवश्यकता नहीं है।', 'rewardTitle': '1 दिन का प्रीमियम पाएं', 'rewardSubtitle': 'आज 3 रिवॉर्डेड विज्ञापन पूरे करें और 24 घंटे का प्रीमियम पाएं।', 'watchReward': 'रिवॉर्डेड विज्ञापन देखें', 'rewardProgress': 'आज की प्रगति', 'promoTitle': 'प्रोमो कोड', 'promoHint': 'कोड दर्ज करें', 'promoApply': 'कोड उपयोग करें', 'promoAccepted': 'प्रोमो कोड लागू हुआ।', 'promoAlreadyUsed': 'यह कोड इस डिवाइस पर पहले उपयोग हो चुका है।', 'promoInvalid': 'प्रोमो कोड अमान्य है।', 'promoUnavailable': 'प्रमोशन सेवा अभी कॉन्फ़िगर नहीं है।', 'promoNetwork': 'कोड सत्यापित नहीं हो सका। इंटरनेट कनेक्शन जांचें।', 'internetRequired': 'इस कार्य के लिए इंटरनेट कनेक्शन आवश्यक है।', 'purchaseUnavailable': 'Google Play खरीद अभी उपलब्ध नहीं है।', 'privacyOptions': 'विज्ञापन गोपनीयता विकल्प', 'privacyPolicy': 'गोपनीयता नीति', 'terms': 'उपयोग की शर्तें', 'purchaseTerms': 'खरीद की शर्तें',
    },
    'bn': {
      'premium': 'প্রিমিয়াম', 'premiumSubtitle': 'বিজ্ঞাপনমুক্ত, অফলাইন ব্যবহার ও PDF রিপোর্ট', 'lifetimePremium': 'আজীবন প্রিমিয়াম', 'temporaryPremium': 'সাময়িক প্রিমিয়াম', 'freePlan': 'বিনামূল্যের সংস্করণ', 'premiumActive': 'প্রিমিয়াম সক্রিয়', 'remaining': 'বাকি সময়', 'lifetime': 'মেয়াদহীন', 'buyLifetime': 'আজীবন প্রিমিয়াম কিনুন', 'playPrice': 'মূল্য Google Play দেখায়।', 'benefitNoAds': 'বিজ্ঞাপনমুক্ত অভিজ্ঞতা', 'benefitOffline': 'অফলাইন ব্যবহার', 'benefitPdf': 'PDF রিপোর্ট সংরক্ষণ ও শেয়ার', 'restoreInfo': 'আগের কেনাকাটা আপনার Google Play অ্যাকাউন্ট থেকে স্বয়ংক্রিয়ভাবে পুনরুদ্ধার হয়। আলাদা রিস্টোর বোতাম দরকার নেই।', 'rewardTitle': '১ দিনের প্রিমিয়াম পান', 'rewardSubtitle': 'আজ ৩টি রিওয়ার্ডেড বিজ্ঞাপন সম্পন্ন করে ২৪ ঘণ্টার প্রিমিয়াম পান।', 'watchReward': 'রিওয়ার্ডেড বিজ্ঞাপন দেখুন', 'rewardProgress': 'আজকের অগ্রগতি', 'promoTitle': 'প্রোমো কোড', 'promoHint': 'কোড লিখুন', 'promoApply': 'কোড ব্যবহার করুন', 'promoAccepted': 'প্রোমো কোড প্রয়োগ হয়েছে।', 'promoAlreadyUsed': 'এই কোডটি এই ডিভাইসে আগে ব্যবহার হয়েছে।', 'promoInvalid': 'প্রোমো কোডটি সঠিক নয়।', 'promoUnavailable': 'প্রোমোশন সেবা এখন কনফিগার করা নেই।', 'promoNetwork': 'কোড যাচাই করা যায়নি। ইন্টারনেট সংযোগ পরীক্ষা করুন।', 'internetRequired': 'এই কাজের জন্য ইন্টারনেট সংযোগ প্রয়োজন।', 'purchaseUnavailable': 'Google Play কেনাকাটা এখন উপলভ্য নয়।', 'privacyOptions': 'বিজ্ঞাপন গোপনীয়তা বিকল্প', 'privacyPolicy': 'গোপনীয়তা নীতি', 'terms': 'ব্যবহারের শর্তাবলি', 'purchaseTerms': 'ক্রয়ের শর্তাবলি',
    },
    'ur': {
      'premium': 'پریمیم', 'premiumSubtitle': 'بغیر اشتہارات، آف لائن استعمال اور PDF رپورٹس', 'lifetimePremium': 'تاحیات پریمیم', 'temporaryPremium': 'عارضی پریمیم', 'freePlan': 'مفت ورژن', 'premiumActive': 'پریمیم فعال ہے', 'remaining': 'باقی وقت', 'lifetime': 'بغیر میعاد', 'buyLifetime': 'تاحیات پریمیم خریدیں', 'playPrice': 'قیمت Google Play دکھاتا ہے۔', 'benefitNoAds': 'اشتہارات سے پاک تجربہ', 'benefitOffline': 'آف لائن استعمال', 'benefitPdf': 'PDF رپورٹس محفوظ اور شیئر کریں', 'restoreInfo': 'پچھلی خریداریاں آپ کے Google Play اکاؤنٹ سے خودکار طور پر بحال ہوتی ہیں۔ الگ ریسٹور بٹن کی ضرورت نہیں۔', 'rewardTitle': '1 دن کا پریمیم حاصل کریں', 'rewardSubtitle': 'آج 3 انعامی اشتہارات مکمل کریں اور 24 گھنٹے کا پریمیم حاصل کریں۔', 'watchReward': 'انعامی اشتہار دیکھیں', 'rewardProgress': 'آج کی پیش رفت', 'promoTitle': 'پرومو کوڈ', 'promoHint': 'کوڈ درج کریں', 'promoApply': 'کوڈ استعمال کریں', 'promoAccepted': 'پرومو کوڈ لاگو ہو گیا۔', 'promoAlreadyUsed': 'یہ کوڈ اس ڈیوائس پر پہلے استعمال ہو چکا ہے۔', 'promoInvalid': 'پرومو کوڈ درست نہیں۔', 'promoUnavailable': 'پروموشن سروس ابھی ترتیب نہیں دی گئی۔', 'promoNetwork': 'کوڈ کی تصدیق نہیں ہو سکی۔ انٹرنیٹ کنکشن چیک کریں۔', 'internetRequired': 'اس عمل کے لیے انٹرنیٹ کنکشن ضروری ہے۔', 'purchaseUnavailable': 'Google Play خریداری اس وقت دستیاب نہیں۔', 'privacyOptions': 'اشتہاری رازداری کے اختیارات', 'privacyPolicy': 'رازداری کی پالیسی', 'terms': 'استعمال کی شرائط', 'purchaseTerms': 'خریداری کی شرائط',
    },
    'id': {
      'premium': 'Premium', 'premiumSubtitle': 'Tanpa iklan, penggunaan offline, dan laporan PDF', 'lifetimePremium': 'Premium seumur hidup', 'temporaryPremium': 'Premium sementara', 'freePlan': 'Versi gratis', 'premiumActive': 'Premium aktif', 'remaining': 'Sisa waktu', 'lifetime': 'Tanpa kedaluwarsa', 'buyLifetime': 'Beli Premium seumur hidup', 'playPrice': 'Harga ditampilkan oleh Google Play.', 'benefitNoAds': 'Pengalaman tanpa iklan', 'benefitOffline': 'Penggunaan offline', 'benefitPdf': 'Simpan dan bagikan laporan PDF', 'restoreInfo': 'Pembelian sebelumnya dipulihkan otomatis dari akun Google Play Anda. Tombol pemulihan terpisah tidak diperlukan.', 'rewardTitle': 'Dapatkan Premium 1 hari', 'rewardSubtitle': 'Selesaikan 3 iklan berhadiah hari ini untuk mendapatkan Premium selama 24 jam.', 'watchReward': 'Tonton iklan berhadiah', 'rewardProgress': 'Progres hari ini', 'promoTitle': 'Kode promo', 'promoHint': 'Masukkan kode', 'promoApply': 'Gunakan kode', 'promoAccepted': 'Kode promo diterapkan.', 'promoAlreadyUsed': 'Kode ini sudah pernah digunakan di perangkat ini.', 'promoInvalid': 'Kode promo tidak valid.', 'promoUnavailable': 'Layanan promosi belum dikonfigurasi.', 'promoNetwork': 'Kode tidak dapat diverifikasi. Periksa koneksi internet.', 'internetRequired': 'Koneksi internet diperlukan untuk tindakan ini.', 'purchaseUnavailable': 'Pembelian Google Play saat ini tidak tersedia.', 'privacyOptions': 'Opsi privasi iklan', 'privacyPolicy': 'Kebijakan Privasi', 'terms': 'Ketentuan Penggunaan', 'purchaseTerms': 'Ketentuan Pembelian',
    },
    'ms': {
      'premium': 'Premium', 'premiumSubtitle': 'Tanpa iklan, penggunaan luar talian dan laporan PDF', 'lifetimePremium': 'Premium seumur hidup', 'temporaryPremium': 'Premium sementara', 'freePlan': 'Versi percuma', 'premiumActive': 'Premium aktif', 'remaining': 'Baki masa', 'lifetime': 'Tiada tamat tempoh', 'buyLifetime': 'Beli Premium seumur hidup', 'playPrice': 'Harga dipaparkan oleh Google Play.', 'benefitNoAds': 'Pengalaman tanpa iklan', 'benefitOffline': 'Penggunaan luar talian', 'benefitPdf': 'Simpan dan kongsi laporan PDF', 'restoreInfo': 'Pembelian terdahulu dipulihkan secara automatik melalui akaun Google Play anda. Butang pulih berasingan tidak diperlukan.', 'rewardTitle': 'Dapatkan Premium 1 hari', 'rewardSubtitle': 'Lengkapkan 3 iklan berganjaran hari ini untuk menerima Premium selama 24 jam.', 'watchReward': 'Tonton iklan berganjaran', 'rewardProgress': 'Kemajuan hari ini', 'promoTitle': 'Kod promosi', 'promoHint': 'Masukkan kod', 'promoApply': 'Tebus kod', 'promoAccepted': 'Kod promosi digunakan.', 'promoAlreadyUsed': 'Kod ini telah digunakan pada peranti ini.', 'promoInvalid': 'Kod promosi tidak sah.', 'promoUnavailable': 'Perkhidmatan promosi belum dikonfigurasi.', 'promoNetwork': 'Kod tidak dapat disahkan. Semak sambungan internet.', 'internetRequired': 'Sambungan internet diperlukan untuk tindakan ini.', 'purchaseUnavailable': 'Pembelian Google Play tidak tersedia buat masa ini.', 'privacyOptions': 'Pilihan privasi iklan', 'privacyPolicy': 'Dasar Privasi', 'terms': 'Terma Penggunaan', 'purchaseTerms': 'Terma Pembelian',
    },
    'fil': {
      'premium': 'Premium', 'premiumSubtitle': 'Walang ads, offline na paggamit at PDF reports', 'lifetimePremium': 'Lifetime Premium', 'temporaryPremium': 'Pansamantalang Premium', 'freePlan': 'Libreng bersyon', 'premiumActive': 'Aktibo ang Premium', 'remaining': 'Natitirang oras', 'lifetime': 'Walang expiration', 'buyLifetime': 'Bumili ng Lifetime Premium', 'playPrice': 'Ipinapakita ng Google Play ang presyo.', 'benefitNoAds': 'Walang ads na karanasan', 'benefitOffline': 'Offline na paggamit', 'benefitPdf': 'Mag-save at mag-share ng PDF reports', 'restoreInfo': 'Awtomatikong ibinabalik ang mga naunang purchase mula sa iyong Google Play account. Hindi kailangan ng hiwalay na restore button.', 'rewardTitle': 'Kumuha ng 1 araw na Premium', 'rewardSubtitle': 'Kumpletuhin ang 3 rewarded ads ngayong araw para sa 24 oras na Premium.', 'watchReward': 'Manood ng rewarded ad', 'rewardProgress': 'Progress ngayong araw', 'promoTitle': 'Promo code', 'promoHint': 'Ilagay ang code', 'promoApply': 'I-redeem ang code', 'promoAccepted': 'Nailapat ang promo code.', 'promoAlreadyUsed': 'Nagamit na ang code na ito sa device na ito.', 'promoInvalid': 'Hindi valid ang promo code.', 'promoUnavailable': 'Hindi pa naka-configure ang promotion service.', 'promoNetwork': 'Hindi ma-verify ang code. Suriin ang internet connection.', 'internetRequired': 'Kailangan ng internet connection para sa aksyong ito.', 'purchaseUnavailable': 'Hindi available sa ngayon ang Google Play purchase.', 'privacyOptions': 'Ad privacy options', 'privacyPolicy': 'Patakaran sa Privacy', 'terms': 'Mga Tuntunin ng Paggamit', 'purchaseTerms': 'Mga Tuntunin sa Pagbili',
    },
    'ko': {
      'premium': '프리미엄', 'premiumSubtitle': '광고 없음, 오프라인 사용 및 PDF 보고서', 'lifetimePremium': '평생 프리미엄', 'temporaryPremium': '기간제 프리미엄', 'freePlan': '무료 버전', 'premiumActive': '프리미엄 활성', 'remaining': '남은 시간', 'lifetime': '만료 없음', 'buyLifetime': '평생 프리미엄 구매', 'playPrice': '가격은 Google Play에서 표시됩니다.', 'benefitNoAds': '광고 없는 앱 경험', 'benefitOffline': '오프라인 사용', 'benefitPdf': 'PDF 보고서 저장 및 공유', 'restoreInfo': '이전 구매는 Google Play 계정에서 자동으로 복원됩니다. 별도의 복원 버튼이 필요하지 않습니다.', 'rewardTitle': '프리미엄 1일 받기', 'rewardSubtitle': '오늘 보상형 광고 3개를 완료하면 프리미엄 24시간을 받습니다.', 'watchReward': '보상형 광고 보기', 'rewardProgress': '오늘의 진행 상황', 'promoTitle': '프로모션 코드', 'promoHint': '코드 입력', 'promoApply': '코드 사용', 'promoAccepted': '프로모션 코드가 적용되었습니다.', 'promoAlreadyUsed': '이 코드는 이 기기에서 이미 사용되었습니다.', 'promoInvalid': '프로모션 코드가 올바르지 않습니다.', 'promoUnavailable': '프로모션 서비스가 아직 구성되지 않았습니다.', 'promoNetwork': '코드를 확인할 수 없습니다. 인터넷 연결을 확인하세요.', 'internetRequired': '이 작업에는 인터넷 연결이 필요합니다.', 'purchaseUnavailable': '현재 Google Play 구매를 사용할 수 없습니다.', 'privacyOptions': '광고 개인정보 보호 옵션', 'privacyPolicy': '개인정보 처리방침', 'terms': '이용약관', 'purchaseTerms': '구매 조건',
    },
    'ja': {
      'premium': 'プレミアム', 'premiumSubtitle': '広告なし・オフライン利用・PDFレポート', 'lifetimePremium': '永久プレミアム', 'temporaryPremium': '期間限定プレミアム', 'freePlan': '無料版', 'premiumActive': 'プレミアム有効', 'remaining': '残り時間', 'lifetime': '期限なし', 'buyLifetime': '永久プレミアムを購入', 'playPrice': '価格は Google Play に表示されます。', 'benefitNoAds': '広告なしの利用体験', 'benefitOffline': 'オフライン利用', 'benefitPdf': 'PDFレポートの保存と共有', 'restoreInfo': '以前の購入は Google Play アカウントから自動的に復元されます。復元ボタンは必要ありません。', 'rewardTitle': 'プレミアム1日分を獲得', 'rewardSubtitle': '本日、リワード広告を3本完了すると24時間のプレミアムを獲得できます。', 'watchReward': 'リワード広告を見る', 'rewardProgress': '本日の進捗', 'promoTitle': 'プロモコード', 'promoHint': 'コードを入力', 'promoApply': 'コードを使用', 'promoAccepted': 'プロモコードを適用しました。', 'promoAlreadyUsed': 'このコードはこの端末ですでに使用されています。', 'promoInvalid': 'プロモコードが無効です。', 'promoUnavailable': 'プロモーションサービスは現在設定されていません。', 'promoNetwork': 'コードを確認できませんでした。インターネット接続を確認してください。', 'internetRequired': 'この操作にはインターネット接続が必要です。', 'purchaseUnavailable': '現在 Google Play 購入を利用できません。', 'privacyOptions': '広告のプライバシー設定', 'privacyPolicy': 'プライバシーポリシー', 'terms': '利用規約', 'purchaseTerms': '購入条件',
    },
    'zh': {
      'premium': '高级版', 'premiumSubtitle': '无广告、离线使用和 PDF 报告', 'lifetimePremium': '终身高级版', 'temporaryPremium': '限时高级版', 'freePlan': '免费版', 'premiumActive': '高级版已启用', 'remaining': '剩余时间', 'lifetime': '永久有效', 'buyLifetime': '购买终身高级版', 'playPrice': '价格由 Google Play 显示。', 'benefitNoAds': '无广告体验', 'benefitOffline': '离线使用', 'benefitPdf': '保存和分享 PDF 报告', 'restoreInfo': '以前的购买会通过您的 Google Play 账号自动恢复，无需单独的恢复按钮。', 'rewardTitle': '获得 1 天高级版', 'rewardSubtitle': '今天完成 3 个激励广告，即可获得 24 小时高级版。', 'watchReward': '观看激励广告', 'rewardProgress': '今日进度', 'promoTitle': '优惠码', 'promoHint': '输入代码', 'promoApply': '兑换代码', 'promoAccepted': '优惠码已应用。', 'promoAlreadyUsed': '此代码已在该设备上使用过。', 'promoInvalid': '优惠码无效。', 'promoUnavailable': '促销服务当前尚未配置。', 'promoNetwork': '无法验证代码，请检查网络连接。', 'internetRequired': '此操作需要互联网连接。', 'purchaseUnavailable': 'Google Play 购买目前不可用。', 'privacyOptions': '广告隐私选项', 'privacyPolicy': '隐私政策', 'terms': '使用条款', 'purchaseTerms': '购买条款',
    },
    'vi': {
      'premium': 'Premium', 'premiumSubtitle': 'Không quảng cáo, dùng ngoại tuyến và báo cáo PDF', 'lifetimePremium': 'Premium trọn đời', 'temporaryPremium': 'Premium có thời hạn', 'freePlan': 'Bản miễn phí', 'premiumActive': 'Premium đang hoạt động', 'remaining': 'Thời gian còn lại', 'lifetime': 'Không hết hạn', 'buyLifetime': 'Mua Premium trọn đời', 'playPrice': 'Giá do Google Play hiển thị.', 'benefitNoAds': 'Trải nghiệm không quảng cáo', 'benefitOffline': 'Sử dụng ngoại tuyến', 'benefitPdf': 'Lưu và chia sẻ báo cáo PDF', 'restoreInfo': 'Các giao dịch mua trước đây được tự động khôi phục từ tài khoản Google Play. Không cần nút khôi phục riêng.', 'rewardTitle': 'Nhận 1 ngày Premium', 'rewardSubtitle': 'Hoàn thành 3 quảng cáo có thưởng hôm nay để nhận 24 giờ Premium.', 'watchReward': 'Xem quảng cáo có thưởng', 'rewardProgress': 'Tiến độ hôm nay', 'promoTitle': 'Mã khuyến mãi', 'promoHint': 'Nhập mã', 'promoApply': 'Đổi mã', 'promoAccepted': 'Đã áp dụng mã khuyến mãi.', 'promoAlreadyUsed': 'Mã này đã được dùng trên thiết bị này.', 'promoInvalid': 'Mã khuyến mãi không hợp lệ.', 'promoUnavailable': 'Dịch vụ khuyến mãi hiện chưa được cấu hình.', 'promoNetwork': 'Không thể xác minh mã. Hãy kiểm tra kết nối Internet.', 'internetRequired': 'Cần kết nối Internet cho thao tác này.', 'purchaseUnavailable': 'Giao dịch mua Google Play hiện không khả dụng.', 'privacyOptions': 'Tùy chọn quyền riêng tư quảng cáo', 'privacyPolicy': 'Chính sách quyền riêng tư', 'terms': 'Điều khoản sử dụng', 'purchaseTerms': 'Điều khoản mua hàng',
    },
    'th': {
      'premium': 'พรีเมียม', 'premiumSubtitle': 'ไม่มีโฆษณา ใช้งานออฟไลน์ และรายงาน PDF', 'lifetimePremium': 'พรีเมียมตลอดชีพ', 'temporaryPremium': 'พรีเมียมชั่วคราว', 'freePlan': 'เวอร์ชันฟรี', 'premiumActive': 'พรีเมียมใช้งานอยู่', 'remaining': 'เวลาที่เหลือ', 'lifetime': 'ไม่หมดอายุ', 'buyLifetime': 'ซื้อพรีเมียมตลอดชีพ', 'playPrice': 'ราคาแสดงโดย Google Play', 'benefitNoAds': 'ประสบการณ์แบบไม่มีโฆษณา', 'benefitOffline': 'ใช้งานออฟไลน์', 'benefitPdf': 'บันทึกและแชร์รายงาน PDF', 'restoreInfo': 'การซื้อก่อนหน้าจะถูกกู้คืนโดยอัตโนมัติจากบัญชี Google Play ของคุณ โดยไม่ต้องมีปุ่มกู้คืนแยก', 'rewardTitle': 'รับพรีเมียม 1 วัน', 'rewardSubtitle': 'ดูโฆษณาแบบมีรางวัลให้ครบ 3 รายการวันนี้เพื่อรับพรีเมียม 24 ชั่วโมง', 'watchReward': 'ดูโฆษณาแบบมีรางวัล', 'rewardProgress': 'ความคืบหน้าวันนี้', 'promoTitle': 'รหัสโปรโมชั่น', 'promoHint': 'กรอกรหัส', 'promoApply': 'ใช้รหัส', 'promoAccepted': 'ใช้รหัสโปรโมชั่นแล้ว', 'promoAlreadyUsed': 'รหัสนี้เคยใช้บนอุปกรณ์นี้แล้ว', 'promoInvalid': 'รหัสโปรโมชั่นไม่ถูกต้อง', 'promoUnavailable': 'ยังไม่ได้ตั้งค่าบริการโปรโมชั่น', 'promoNetwork': 'ไม่สามารถตรวจสอบรหัสได้ โปรดตรวจสอบอินเทอร์เน็ต', 'internetRequired': 'ต้องเชื่อมต่ออินเทอร์เน็ตสำหรับการดำเนินการนี้', 'purchaseUnavailable': 'ขณะนี้การซื้อผ่าน Google Play ไม่พร้อมใช้งาน', 'privacyOptions': 'ตัวเลือกความเป็นส่วนตัวของโฆษณา', 'privacyPolicy': 'นโยบายความเป็นส่วนตัว', 'terms': 'ข้อกำหนดการใช้งาน', 'purchaseTerms': 'ข้อกำหนดการซื้อ',
    },
    'sw': {
      'premium': 'Premium', 'premiumSubtitle': 'Bila matangazo, matumizi nje ya mtandao na ripoti za PDF', 'lifetimePremium': 'Premium ya maisha yote', 'temporaryPremium': 'Premium ya muda', 'freePlan': 'Toleo la bure', 'premiumActive': 'Premium imewashwa', 'remaining': 'Muda uliobaki', 'lifetime': 'Haina mwisho', 'buyLifetime': 'Nunua Premium ya maisha yote', 'playPrice': 'Bei inaonyeshwa na Google Play.', 'benefitNoAds': 'Matumizi bila matangazo', 'benefitOffline': 'Matumizi nje ya mtandao', 'benefitPdf': 'Hifadhi na shiriki ripoti za PDF', 'restoreInfo': 'Ununuzi wa awali unarejeshwa kiotomatiki kutoka akaunti yako ya Google Play. Hakuna haja ya kitufe tofauti cha kurejesha.', 'rewardTitle': 'Pata Premium ya siku 1', 'rewardSubtitle': 'Kamilisha matangazo 3 yenye zawadi leo ili upate Premium kwa saa 24.', 'watchReward': 'Tazama tangazo lenye zawadi', 'rewardProgress': 'Maendeleo ya leo', 'promoTitle': 'Msimbo wa ofa', 'promoHint': 'Weka msimbo', 'promoApply': 'Tumia msimbo', 'promoAccepted': 'Msimbo wa ofa umetumika.', 'promoAlreadyUsed': 'Msimbo huu tayari umetumika kwenye kifaa hiki.', 'promoInvalid': 'Msimbo wa ofa si sahihi.', 'promoUnavailable': 'Huduma ya ofa haijasanidiwa kwa sasa.', 'promoNetwork': 'Msimbo haukuweza kuthibitishwa. Angalia muunganisho wa intaneti.', 'internetRequired': 'Muunganisho wa intaneti unahitajika kwa kitendo hiki.', 'purchaseUnavailable': 'Ununuzi wa Google Play haupatikani kwa sasa.', 'privacyOptions': 'Chaguo za faragha za matangazo', 'privacyPolicy': 'Sera ya Faragha', 'terms': 'Masharti ya Matumizi', 'purchaseTerms': 'Masharti ya Ununuzi',
    },
  };

  static String text(String languageTag, String key) {
    final normalized = switch (languageTag) {
      'pt_BR' || 'pt-br' => 'pt-BR',
      'pt_PT' || 'pt-pt' => 'pt-PT',
      'de-DE' => 'de',
      'it-IT' => 'it',
      'nl-NL' => 'nl',
      'pl-PL' => 'pl',
      'ro-RO' => 'ro',
      'el-GR' => 'el',
      'ru-RU' => 'ru',
      'uk-UA' => 'uk',
      'ar-SA' => 'ar',
      'fa-IR' => 'fa',
      'he-IL' => 'he',
      'hi-IN' => 'hi',
      'bn-BD' => 'bn',
      'ur-PK' => 'ur',
      'id-ID' => 'id',
      'ms-MY' => 'ms',
      'fil-PH' => 'fil',
      'ko-KR' => 'ko',
      'ja-JP' => 'ja',
      'zh-CN' => 'zh',
      'vi-VN' => 'vi',
      'th-TH' => 'th',
      'sw-TZ' => 'sw',
      _ => languageTag,
    };
    return _values[normalized]?[key] ?? _values['en']![key] ?? key;
  }

  static Set<String> get supportedLanguageTags => _values.keys.toSet();
}
